### ISSUE TITLE
Maybe bug: descheduler don't evict  PVC pods

### ISSUE THREAD

**Issue by mtt0** [kubernetes-sigs/descheduler#1001]
**What version of descheduler are you using?**

descheduler version: 0.25.1

**Does this issue reproduce with the latest release?**

Yes

**Which descheduler CLI options are you using?**

```yaml
              - "--policy-config-file"
              - "/policy-dir/policy.yaml"
              - "--v"
              - "4"
```

**Please provide a copy of your descheduler policy config file**

<details><summary><code> descheduler policy config file </code></summary><br><pre>
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    maxNoOfPodsToEvictPerNode: 5
    strategies:
      "RemoveDuplicates":
         enabled: true
         params:
           namespaces:
             exclude:
               - "kube-system"
               - "rook-ceph"
               - "lxcfs"
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
         params:
           namespaces:
             exclude:
               - "kube-system"
               - "rook-ceph"
               - "lxcfs"
      "RemovePodsViolatingNodeAffinity":
         enabled: true
         params:
           namespaces:
             exclude:
               - "kube-system"
               - "rook-ceph"
               - "lxcfs"
           nodeAffinityType:
           - requiredDuringSchedulingIgnoredDuringExecution
      "RemovePodsViolatingNodeTaints":
         enabled: true
         params:
           namespaces:
             exclude:
               - "kube-system"
               - "rook-ceph"
               - "lxcfs"
      "RemoveFailedPods":
         enabled: true
         params:
           failedPods:
             includingInitContainers: true
             excludeOwnerKinds:
               - "Job"
             minPodLifetimeSeconds: 3600
      "LowNodeUtilization":
         enabled: true
         params:
           namespaces:
             exclude:
               - "kube-system"
               - "rook-ceph"
               - "lxcfs"
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 40
               "memory": 40
               "pods": 40
             targetThresholds:
               "cpu" : 60
               "memory": 60
               "pods": 60
</pre></details>

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

Deployed the descheduler with the above policy + use verbosity lv 4.

**What did you expect to see?**

Evict overload nodes' pods

**What did you see instead?**

Descheduler logs:

```
I1111 14:30:33.813346       1 defaultevictor.go:188] "Pod fails the following checks" pod="examsystem-develop/examsystem-778db55464-5hqwz" checks="pod has local storage and descheduler is not configured with evictLocalStoragePods"
```

But the deployment `examsystem-develop/examsystem` **is using PVC, not local storage on node**

<details><summary><code>examsystem-develop yaml</code></summary><br><pre>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 0.1.5
    checksum/config: c079a22a20e7a2fd299f05637677be13569b2ac3feee8e9284943b3c9a548993
    meta.helm.sh/release-name: examsystem-develop
    meta.helm.sh/release-namespace: examsystem-develop
  labels:
    app.kubernetes.io/instance: examsystem-develop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: examsystem
    app.kubernetes.io/version: 0.1.5
    helm.sh/chart: examsystem-0.1.5
  name: examsystem
  namespace: examsystem-develop
  resourceVersion: '146441668'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: examsystem-develop
      app.kubernetes.io/name: examsystem
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: examsystem-develop
        app.kubernetes.io/name: examsystem
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: examsystem
          image: 'xxxx.xxx/exam-system/server:0.1.5'
          imagePullPolicy: IfNotPresent
          name: examsystem
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 20m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: uploadFile
              name: examsystem-0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: examsystem-0
          persistentVolumeClaim:
            claimName: examsystem-0
</pre></details>

https://github.com/kubernetes-sigs/descheduler/issues/1001#tasklist-block-9fa3108b-b44d-475b-91b6-d3b3ee3d4497

**Comment by damemi** [comment]
Hi @mtt0, your deployment spec looks like this shouldn't be happening, as [that error message](https://github.com/kubernetes-sigs/descheduler/blob/v0.25.1/pkg/framework/plugins/defaultevictor/defaultevictor.go#L115) only comes after [this check](https://github.com/kubernetes-sigs/descheduler/blob/v0.25.1/pkg/utils/pod.go#L98-L106) that checks that a pod's volumes don't have `HostPath` or `EmptyDir` set (which yours don't).

Could you share the yaml from one of the actual pods that's failing eviction (instead of the deployment)? I'm wondering if there is something mutating the pod to set these fields
