### ISSUE TITLE
Open workload datasets and benchmarking models

### ISSUE THREAD

**Issue by wisaaco** [kubernetes-sigs/descheduler#1002]
Hello,

I work in academia and I would like to evaluate some descheduler models but I have not found any workload real or emulated that can use for that purpose. 

I hope not to bother with this question in this channel, but in many academic studies - the ones I have been able to read - the scenarios presented are relatively small. I would like to apply strategies on representative ecosystems and workloads and even devise some benchmarking models.  

I welcome any suggestions in this regard. 

Best regards,
Isaac

**Comment by a7i** [comment]
Hi Iassc,
What would the dataset contain?
What would the benchmark model consist of?

**Comment by wisaaco** [comment]
Hello,
We are working on a research project to improve job allocation and scheduling in Kubernetes-related computing infrastructures. Therefore, it would be ideal to have datasets where data on related problems (jobs, QoS needs, temporal metrics, allocation and scheduling decisions, etc.) are available.
We intend to improve these algorithms to competitively improve current solutions (cost reduction, energy consumption, etc.) and also to be able to generate benchmarking models for evaluation or simulation in other ecosystems.

Best
