### ISSUE TITLE
Node Filtering Not available in LowNodeUtilization and HighNodeUtilization

### ISSUE THREAD

**Issue by sandy0509187** [kubernetes-sigs/descheduler#1005]
Creating an issue to check if there is any plan or roadmap to include Node level filtering in policies LowNodeUtilization and HighNodeUtilization in upcoming releases . Since we have few critical nodes like control plane , etcd and service mesh nodes in K8s cluster and need to safeguard all workloads running on them from descheduler eviction actions . 
With current available filtering its not fulfilling the purpose to exclude nodes during eviction run . 

Early update would be appreciated  .

**Comment by jenciso** [comment]
It seems that it will be available in the next version. Check this PR already merged https://github.com/kubernetes-sigs/descheduler/pull/967

**Comment by damemi** [comment]
@knelasevero will the filtering in #967 be accessible through the v1alpha1 api config or is that only going to work with v1alpha2?

**Comment by knelasevero** [comment]
You can use the same 'Namespaces' field of the v1alpha1 config to filter namespaces. 

https://github.com/kubernetes-sigs/descheduler/pull/999/files#r1020344073

**Comment by damemi** [comment]
/close
since this will be in the next release
