### ISSUE TITLE
Helm chart version update to v0.26.0

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#1020]

**Comment by damemi** [comment]
note merging this will be blocked on #1021 (https://github.com/kubernetes-sigs/descheduler/blob/master/docs/release-guide.md#flowchart)

**Comment by damemi** [comment]
@JaneLiuL if you're still available for this, we are ready for the helm chart change

**Comment by JaneLiuL** [comment]
sure, raise now

**Comment by JaneLiuL** [comment]
sorry for so late for my home have some network issue
