### ISSUE TITLE
Create v0.26.0 git tag on master

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#1021]

**Comment by a7i** [comment]
@damemi I don't have permission to push a tag, what's the status on this?

**Comment by damemi** [comment]
@a7i I should have provided more description... I decided to hold on the release while most of our maintainers were out for the holidays. I self-assigned this to hold it for that reason.

There is a separate ACL for write permission to the repo, which we should add you to. For the future though, we need to make sure there is consensus among the maintainers before trying to push directly to the repo.

Now that people are filtering back in for the new year, I'll get back on these last few steps for v0.26

**Comment by a7i** [comment]
Sounds good @damemi, and happy NY!

**Comment by damemi** [comment]
Tag pushed, closing this 🚀
