### ISSUE TITLE
Whether to support scheduling notification？

### ISSUE THREAD

**Issue by dok8s** [kubernetes-sigs/descheduler#1024]
Hello, if there is a rescheduling action during the scheduling process, how to realize the notification by email, SMS or webhook?

**Comment by seanmalloy** [comment]
When the descheduler evicts a pod a k8s event is created. There is also an option to enable Prometheus metrics.

**Comment by damemi** [comment]
To add to @seanmalloy's comment, if you are tracking the descheduler's prometheus metrics you can set up a tool like [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) to send an alert to slack, pagerduty, email, etc.
