### ISSUE TITLE
Strategy Weight

### ISSUE THREAD

**Issue by jklaw90** [kubernetes-sigs/descheduler#1025]
**Is your feature request related to a problem? Please describe.**

I was looking to make a custom descheduler plugin, but I realized i didn't know how to specify strategy order. 
I noticed there was a [weight](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/api/v1alpha1/types.go#L64) config in the api but i don't think its actually being used? It looks like we iterate over the map of names which would be random?

**Describe the solution you'd like**

Implement weight for strategies. I was specifically thinking of doing something at the start and end of descheduling. 
There might be a better way of doing this that already existed, it just wasn't clear from the docs.

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version:

**Additional context**

**Comment by damemi** [comment]
I don't think that weight field is implemented anywhere and looks like it was added years ago (maybe never used?)

I don't believe we were planning a config for ordering which strategies run first (@ingvagabund can you confirm?) This might have been implicitly handled by the order in which strategies are enabled in the config, but I don't know if that list is guaranteed to stay in the same order when it converts to a Go struct.

Still, this should be something we make sure is handled in v1alpha2. I don't think adding this will be a significant challenge, but thank you for calling it out @jklaw90

**Comment by ingvagabund** [comment]
Yes. The new v1alpha2 configuration is expected to honor the order of strategies/plugins.  The order in which the plugins are enabled will affect the order in which the extension points are executed.

**Comment by a7i** [comment]
v1alpha2 is now released and supported
/close
