### ISSUE TITLE
Run duration metric

### ISSUE THREAD

**Issue by jklaw90** [kubernetes-sigs/descheduler#1037]
**Is your feature request related to a problem? Please describe.**
When trying to tune the run interval I'm not quite sure how long the descheduler run loop takes on average. 

**Describe the solution you'd like**
It'd be nice to have some metrics around the duration of the run. Also could be nice to have some idea of each particular strategy run time too.

**Describe alternatives you've considered**
Look at logs to determine this.

**What version of descheduler are you using?**

descheduler version: 1.25.X

**Additional context**

**Comment by damemi** [comment]
+1, it would be great to report some more metrics on the performance of the descheduler itself

**Comment by harshanarayana** [comment]
@damemi I was thinking they can both be exported as Histogram metrics with a bucket config of `0.05, 0.025, 0.01, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 25` ?
