### ISSUE TITLE
Operator Lifecycle Manager Catalog for Kube Descheduler

### ISSUE THREAD

**Issue by marandalucas** [kubernetes-sigs/descheduler#1045]
**Describe the solution you'd like**
_NEW FEATURE REQUEST:_

**We would like to handle kube-descheduler with Operator Lifecycle Manager.**

_Nowadays, in our experience is very useful to handle all the operators with Operator Lifecycle Manager.
OLM provides rich update mechanisms to keep Kubernetes native applications up to date automatically._

**_For example, the open source project called "External Secrets Tool" has been created and deployed an Operator to deploy through OLM._**
=> https://artifacthub.io/packages/olm/community-operators/external-secrets-operator

That's very useful because we just need to subscribe to the catalogue instead of creating automation with helm or Kubernetes manifest to deploy and update it. 

For now, we are provisioning the following resources with OLM (The unique resource that we would like to deploy in the same way would be "kube-descheduler"):

- [External Secrets Operator](https://artifacthub.io/packages/olm/community-operators/external-secrets-operator)
- [RabbitMQ Cluster Operator](https://artifacthub.io/packages/olm/community-operators/rabbitmq-cluster-operator)
- [MongoDB Operator](https://artifacthub.io/packages/olm/community-operators/mongodb-enterprise)
- [Prometheus Operator](https://artifacthub.io/packages/olm/community-operators/prometheus)
- [Grafana Operator](https://artifacthub.io/packages/olm/community-operators/grafana-operator)

**What version of descheduler are you using?**
descheduler version:  v0.26.0

**What's your thought?**

Congratulation on this awesome project!
Thanks in advance

**Comment by marandalucas** [comment]
Hi! Is there already something on the table?

**Comment by damemi** [comment]
@marandalucas no, unfortunately this isn't a top priority for the project at this time
