### ISSUE TITLE
[Tracking Issue] Enrich the Descheduler Metrics

### ISSUE THREAD

**Issue by Dentrax** [kubernetes-sigs/descheduler#1047]
As a contributor and end-user of Descheduler, we rollout it over 300+ Kubernetes clusters. I can clearly see that one of the improvement point of the Descheduler is metrics. Since Descheduler provides limited number of metrics, sometimes it can also be challenging to observe and monitor internal metrics in production. (Especially during HPA, a bunch of node(s) add/remove, etc.) I'm proposing we should prioritize the observability topics.

There is already going discussions on some issues and PRs spread around, so that I just wanted to gather all of them in one umbrella to boost awareness and make easy to track:

* [ ] - #503
* [ ] - #919
* [ ] - #905
* [ ] - #951 (PR: #958)
* [ ] - #1037 (PR: #1041)
* [ ] - #1046

Dropping some closed PRs for reference:

* #648
* #859

**Comment by harshanarayana** [comment]
I can take a stab at #1046 once we have some more metrics generated for the strategies that are required.
