### ISSUE TITLE
When node iohang, can desceduler autoscale new pod to satisfy all traffic

### ISSUE THREAD

**Issue by sigezhao** [kubernetes-sigs/descheduler#1052]
Recently，I meet k8s node iohang problem，then pod on the iohang node can not be  evicted and can not service incoming traffic。

The remain pod is overload， and most of my traffic failed。

When node iohang, can desceduler autoscale new pod to satisfy all traffic？

**Comment by damemi** [comment]
Hi @sigezhao,
I'm not familiar with node iohang and couldn't find anything about it. But from your description, I don't think descheduler will do what you're looking for. It mainly works on evicting pods, not autoscaling or creating new ones. You may be interested in [horizontal pod autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)?
