### ISSUE TITLE
Change in 'Reason' of Events

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#1055]
**What version of descheduler are you using?**

descheduler version:
v0.26.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
In the previous versions of Descheduler, the event Reason was `Descheduled`. However, that has now been changed to the plugin name. Was this intended? Event is structured for the most part and we were relying on certain matches.

**What did you expect to see?**

```
LAST SEEN   TYPE      REASON                                        OBJECT                                                                             MESSAGE
6m35s       Normal    Descheduled                                   pod/<REDACTED>                                  pod evicted from REDACTED.compute.internal node by sigs.k8s.io/descheduler
```

**What did you see instead?**
```
LAST SEEN   TYPE      REASON                                        OBJECT                                                                             MESSAGE
6m35s       Normal    RemovePodsViolatingTopologySpreadConstraint   pod/<REDACTED>                                  pod evicted from REDACTED.compute.internal node by sigs.k8s.io/descheduler
```

**Comment by damemi** [comment]
Maybe related to changes in https://github.com/kubernetes-sigs/descheduler/issues/1053 that also affected the metrics labels?

We should add tests for events and metrics to prevent this in the future. We've done a lot of reorganizing with the framework changes and while we test for primary functionality, it's signals like this that can be easily missed.

**Comment by a7i** [comment]
for sure related. I'm assuming that we don't want to change back again, so these are here to stay now?
