### ISSUE TITLE
Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [containerdenynottrustedimage] C1002: Pod/descheduler-27889110-tjmwf/descheduler: Container using not trusted image: k8s.gcr.io/descheduler/descheduler:v0.25.0

### ISSUE THREAD

**Issue by Ramprasad2019** [kubernetes-sigs/descheduler#1056]
**What version of descheduler are you using?**

descheduler version:
v0.25.0

**Does this issue reproduce with the latest release?**

yes
**Which descheduler CLI options are you using?**

we have installed it in aks cluster through helm chart using terraform code
**Please provide a copy of your descheduler policy config file**

deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: true
    RemovePodsHavingTooManyRestarts:
      enabled: true
      params:
        podsHavingTooManyRestarts:
          podRestartThreshold: 100
          includingInitContainers: true
    RemovePodsViolatingNodeTaints:
      enabled: true
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: true
    LowNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
    HighNodeUtilization:
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
            cpu : 20
            memory: 20
            pods: 20        
nodeSelector: 
  kubernetes.azure.com/agentpool: abstrlayer

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**
descheduler should be up and running 

**What did you see instead?** getting the below error
Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [containerdenynottrustedimage] C1002: Pod/descheduler-27889110-tjmwf/descheduler: Container using not trusted image: k8s.gcr.io/descheduler/descheduler:v0.25.0 [poddenywithoutnodeselector] P1001: Pod/descheduler-27889110-tjmwf: Missing required nodeSelector: agentpool

**Comment by seanmalloy** [comment]
@Ramprasad2019 what Gatekeeper constraints and constraint templates do you have configured? Did you create custom gatekeeper constraints and constraint templates yourself or are these some sort of defaults provided by AKS?

**Comment by Ramprasad2019** [comment]
@seanmalloy  we have created customized gatekeeper constriants and constraint templates ourselves . could you please help why we are getting these errors? also please help on this error 
poddenywithoutnodeselector] P1001: Pod/descheduler-27889110-tjmwf: Missing required nodeSelector: agentpool

**Comment by Ramprasad2019** [comment]
any update please?

**Comment by seanmalloy** [comment]
Based on the error messages and information provided this does not seem to be a bug with the descheduler or descheduler helm chart.

It looks like there are two Gatekeeper Constraints/ConstraintTemplates preventing the descheduler pod from being created. As indicated previously in this issue these are custom developed Constraints/ConstraintTemplates. It looks like you need to change the nodeSelector to fix one of the errors.

/remove-label bug
