### ISSUE TITLE
Taint nodes based on custom conditions

### ISSUE THREAD

**Issue by bbatha** [kubernetes-sigs/descheduler#1060]
**Is your feature request related to a problem? Please describe.**

I have deployed the `node-problem-detector` and I would like to use it in conjunction with this project to cordon and ultimately drain nodes that fail its included conditions as well as custom conditions I add via `node-problem-detector`s custom plugin support. [The documentation on this project strongly alludes to this being possible](https://github.com/kubernetes-sigs/descheduler/pull/740), [but the dependent PR on `node-problem-detector` has been rejected. ](https://github.com/kubernetes/node-problem-detector/pull/565)

**Describe the solution you'd like**

I would like nodes failing to meet custom conditions to be tainted with `Condition=NoSchedule`

**Describe alternatives you've considered**

Having the node-problem detector do it [but that won't be merged upstream](https://github.com/kubernetes/node-problem-detector/pull/565).
[Draino](https://github.com/planetlabs/draino), Doesn't seem to have active maintenance and overlaps this project's goals considerably.

**What version of descheduler are you using?**

descheduler version: n/a

**Additional context**

**Comment by seanmalloy** [comment]
@bbatha thanks for opening this issue.

I'll try to take a look at this. I read through all of the linked issues and PRs. My first step will be to get both the descheduler and NPD documentation updated to accurately reflect the current state. After that I'll see where/if this feature should be added.

**Comment by btiernay** [comment]
> The documentation on this project strongly alludes to this being possible, but the dependent PR on node-problem-detector has been rejected.

@bbatha Are you sure about that? It appears as though there is an active code review in https://github.com/kubernetes/node-problem-detector/pull/565

**Comment by bbatha** [comment]
That pr was recently reopened from the thread it seemed the project maintainers disagreed with the direction. 

Regardless this feature does not currently exist. I would be thrilled if that merged an fulfilled the requirements of this ticket.
