### ISSUE TITLE
Add k8s compatibility warnings to logs

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#1062]
We document our k8s version compatibility in the Readme, but it would be helpful to users to have this logged directly in the descheduler when it's running. Something like: `Warning: Descheduler version XX is not supported on your version of Kubernetes (YY). See compatibility docs for more info: https://github.com/kubernetes-sigs/descheduler#compatibility-matrix`

Though I don't know if it's possible to self-detect what version of kubernetes we're running on, which is necessary for this

**Comment by a7i** [comment]
Good idea!

We should be able to use the `discoveryClient` like [here](https://github.com/kubernetes/kubernetes/blob/v1.26.1/staging/src/k8s.io/kubectl/pkg/cmd/version/version.go#L139)

And use the skew logic [here](https://github.com/kubernetes/kubernetes/blob/v1.26.1/staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go#L34)

**Comment by JaneLiuL** [comment]
may I have a try on this issue?
/assign

**Comment by damemi** [comment]
Thanks @JaneLiuL!

**Comment by damemi** [comment]
Fixed by https://github.com/kubernetes-sigs/descheduler/pull/1063
/close
