### ISSUE TITLE
Descheduler is killing pods mid request which is causing outages

### ISSUE THREAD

**Issue by gallowaystorm** [kubernetes-sigs/descheduler#1064]
**What version of descheduler are you using?**

descheduler version:
version    = "0.24.1" # APP VERSION v0.24.1

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
Using Helm

**Please provide a copy of your descheduler policy config file**

```terraform
resource "helm_release" "descheduler" {
  chart      = local.service_name
  name       = "${local.service_name}-${var.environment}"
  namespace  = local.namespace
  repository = "https://kubernetes-sigs.github.io/descheduler/"
  version    = "0.24.1" # APP VERSION v0.24.1

  # Uncomment headers config below when this has been fixed:

  # https://github.com/kubernetes-sigs/descheduler/issues/965#issuecomment-1262683721
  # Reason for commenting is due to workaround in DD that relates to issue #676 noted in comments

  # set {
  #   name  = "cmdOptions.skip-headers"
  #   value = ""
  # }

  set {
    name  = "schedule"
    value = "*/30 * * * *"
    # sets the timing of the cronjob that fires off descheduler
  }

  set {
    name  = "deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.targetThresholds.cpu"
    value = 70
    # set the cpu threshold in which a node is considered "OVER Utilized" (over x%)
  }

  set {
    name  = "deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.targetThresholds.memory"
    value = 70
    # set the memory threshold in which a node is considered "OVER Utilized" (over x%)
  }

  set {
    name  = "deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.thresholds.cpu"
    value = 10
    # set the cpu threshold in which a node is considered "UNDER Utilized" (under x%)
  }

  set {
    name  = "deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.thresholds.memory"
    value = 20
    # set the memory threshold in which a node is considered "UNDER Utilized" (under x%)
  }


  set {
    name  = "deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.thresholds.pods"
    value = 5
    # set the pod threshold in which a node is considered "UNDER Utilized" (under x amount of pods)
  }

  set {
    name  = "deschedulerPolicy.strategies.RemoveDuplicates.enabled"
    value = true
    # Enable Pod Restarts to be monitored
  }
  set {
    name  = "deschedulerPolicy.strategies.RemoveDuplicates.params.nodeFit"
    value = true
    # If set to true the descheduler will consider whether or not the pods that meet eviction criteria will fit on other nodes before evicting them
  }

  set {
    name  = "deschedulerPolicy.strategies.RemovePodsViolatingTopologySpreadConstraint.enabled"
    value = true
    # Enable Toplogy Spread Constratins to be taken into consideration ## temp sent to false until nodefit works
  }

  set {
    name  = "deschedulerPolicy.strategies.RemovePodsViolatingTopologySpreadConstraint.params.includeSoftConstraints"
    value = true
    # Allow our soft constraints for Toplogy Spread Constratins to be taken into consideration
  }
  set {
    name  = "deschedulerPolicy.strategies.RemovePodsViolatingTopologySpreadConstraint.params.nodeFit"
    value = true
    # If set to true the descheduler will consider whether or not the pods that meet eviction criteria will fit on other nodes before evicting them
  }

  set {
    name  = "deschedulerPolicy.strategies.RemovePodsHavingTooManyRestarts.enabled"
    value = true
    # Enable Pod Restarts to be monitored
  }

  set {
    name  = "deschedulerPolicy.strategies.RemovePodsHavingTooManyRestarts.params.podsHavingTooManyRestarts.podRestartThreshold"
    value = 100
    # Set the threshold for when the service removes a pod based off number of restarts
  }
}
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

```bash
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:32:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Everytime the descheduler kills a pod, it does it forcefully.  This gives no time for the pod to finish any requests nor allow kubernetes to stop routing traffic to it.

**What did you expect to see?**
The pods are evicted gracefully.

**What did you see instead?**
Outages caused by pods forcefully deleting

**Comment by damemi** [comment]
Hi @gallowaystorm, the descheduler uses the native [eviction api](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/) to remove pods, rather than directly killing pods by force. This api respects graceful shutdown policies like `terminationGracePeriodSeconds` (which is 30s by default, but I suppose it is possible that your workloads may need longer than that). Have you tried setting a longer termination grace period on your pods to help them clean up before being evicted?

**Comment by gallowaystorm** [comment]
We have a termination grace period of 90 set already.  The issue we see is that with Pod Topology Constratin set to 1 pod per node, if we ever go above 3 pods (we have min of 3 nodes), the extra 2 pods keep switching back and forth and never stop.  Node fit seems to work in very certain cases, but for the most part it does not because the other nodes technically have space to house them.  With the descheduler set to run every 2 mins, its constantly switching those 2 extra pods back and forth which causes outages.  We upped the scheduler to run every 30 mins instead but that does not solve the issue, just band-aids it.

**Comment by damemi** [comment]
Ah, that's a different issue then. You're right that NodeFit does not check the topology constraints (see https://github.com/kubernetes-sigs/descheduler#node-fit-filtering for what it does consider)

We merged an update to help with this kind of eviction loop in the topology constraints strategy in https://github.com/kubernetes-sigs/descheduler/pull/836, which was available starting in v0.25.0 of descheduler. 

I see that you're currently on descheduler v0.24.1, so you may want to try updating to v0.25.0 to see if that helps. Descheduler v0.25 is still within the support range for your k8s version 1.22, so there shouldn't be any other issues with upgrading. Please let us know if this helps or you run into any other problems with that.

**Comment by gallowaystorm** [comment]
Understood.  Thanks!

**Comment by damemi** [comment]
@gallowaystorm hope that helped, and if you have a chance let us know if it fixed your problem. thanks!
