### ISSUE TITLE
Re-allocation pod when a node is died

### ISSUE THREAD

**Issue by meocong** [kubernetes-sigs/descheduler#1070]
Hi, I have a problem in re-scheduling pod. When one node is died, all pods in that node will be in Terminating state and will not re-allocate to another node, it will be danger when a master pod was in that node, I think descheduler can help but it ignored the node when running

My current solution is force delete all pod in that node using: 
```
for p in $(kubectl get pods -n device | grep Terminating | awk '{print $1}'); do kubectl delete pod $p -n device --grace-period=0 --force;done
```

I used the lastest helm version of descheduler

**Comment by a7i** [comment]
Descheduler currently uses the eviction API (as opposed to DELETE). This would be a change in behavior so will require some discussions.

My organization also has a similar use-case and we have implemented a custom solution that deletes the stuck Pods. It would be ideal to consolidate it all into Descheduler.

Open to feedback from other maintainers on whether we should support this.
