### ISSUE TITLE
issue with following strategy : RemovePodsViolatingTopologySpreadConstraint 

### ISSUE THREAD

**Issue by LAVA-KUMAR** [kubernetes-sigs/descheduler#1088]
I am trying the above strategy with scale down scenario ( decreasing replica count) to check whether is respecting maxskew constraint or not  , but always i am seeing number of evicted pods is zero , can anyone please help with this . Thanks in advance.

**Comment by damemi** [comment]
Hi, can you share more information please? Your descheduler config, which version of descheduler+k8s you are running, and if possible a sample pod or deployment spec would be helpful. Thanks!

**Comment by LAVA-KUMAR** [comment]
Yes ,  k8s version : 1.22 , and descheduler version : 0.23 ,

following is de-scheduler configMap: 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemovePodsViolatingTopologySpreadConstraint":
         enabled: true
         params:
            includeSoftConstraints: false
            
            
   Following is the topology spread constraint spec : 
        spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: test-app

**Comment by LAVA-KUMAR** [comment]
sharing the sample logs that i am getting  : 
I0313 12:00:53.613868       1 node.go:165] "Pod does not fit on node" pod="test/test-65b77f57c8-fx6wv" node="ip-10-104-34-44.ec2.internal"
I0313 12:00:53.613889       1 node.go:169] "Pod fits on node" pod="test/test-65b77f57c8-fx6wv" node="ip-10-104-44-184.ec2.internal"

above logs i am getting but at the end  always i am getting evicted pods count=0, is it expected only? 
my expectation here is if the evicted pod count is some number ( not zero) then some pod eviction is happening to balance the pods according to the maxskew but it is always giving evicted pod count is zero.

**Comment by LAVA-KUMAR** [comment]
Yes ran like above now able to see the proper logs , thank you so much for the quick help .

**Comment by damemi** [comment]
@LAVA-KUMAR was that able to resolve your issue? If so I'll close this. Feel free to reopen if you need more assistance
/close

**Comment by LAVA-KUMAR** [comment]
Yes able to resolve the issue . Thanks for the help.

**Comment by LAVA-KUMAR** [comment]
Hi following is my ploicy:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    evictLocalStoragePods: true
    maxNoOfPodsToEvictPerNode: 2
    strategies:
      "RemovePodsViolatingTopologySpreadConstraint":
         enabled: true
         params:
            labelSelector:
              matchLabels:
                app: test
            includeSoftConstraints: false
            
            
    q1)   Even I have applied the label filter for the app "test" ,  descheduler tries to check the pods related to the other apps also . Am I applying label filter properly ?
       
    q2) here I have added the constraint called : maxNoOfPodsToEvictPerNode: 2 , even though I am applying this constraint , it seems it's evicting more than two pods and also getting following error in the logs :
    topologyspreadconstraint.go:182] "Error evicting pod" err="Maximum number 2 of evicted pods per \"ip-10-109-44-197.ec2. what is this log saying?

**Comment by damemi** [comment]
For 1) are the pods actually being evicted or just checked? The evictor might be looking at these pods but then ignoring them once it sees the labels

2) similar question, are the pods actually being evicted? That error message indicates that the descheduler is ignoring those pods because it has already hit the maximum limit

Can you share your full descheduler log? There could be a lot more context there

**Comment by LAVA-KUMAR** [comment]
Hi, for the following response that you have given : " are the pods actually being evicted or just checked? The evictor might be looking at these pods but then ignoring them once it sees the labels"

Is there any way can configure such way that descheduler(evictor) only looks for the pods that are configured through labels , because it may give extra throttling right ?  is there any way we can avoid checking the pods that are not  related to the label that we set ? Thanks in advance .

**Comment by LAVA-KUMAR** [comment]
@damemi  can you please respond to the above query .

**Comment by damemi** [comment]
No, for some strategies like topology spreading, the descheduler needs to at least know about all of the pods in the topology in order to calculate the skew accurately. It then filters out which pods to evict based on the labels that match the selector. There isn't a good way to run this strategy against only a subset of a topology. You might want to think about placing those pods you are concerned with in their own separate topology instead.

**Comment by LAVA-KUMAR** [comment]
Yes got it thank you for the response  , but let say I have a deployment called app name is  : test , let say this deployment  have 5 replicas  , where my topology spread constraint defined in following way :
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: test
and consider I have two zones called (us-east-1a, us-east-b),  now the expectations is zone-a should contains 3 replicas ad zone-b contains 2 replicas now in this case it is balanced according to maxskew across zones .

Now if it is imbalanced means de-scheduler should do the balance and try to evict the pods to do the balance( this is the expectation here )  . Now to do this it is enough to check the pods which are related to the  label filter that we set right?
am I missing anything here ?  Can you please confirm this

**Comment by LAVA-KUMAR** [comment]
Yes got it thank you for the response  , but let say I have a deployment called app name is  : test , let say this deployment  have 5 replicas  , where my topology spread constraint defined in following way :
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: test
and consider I have two zones called (us-east-1a, us-east-b),  now the expectations is zone-a should contains 3 replicas ad zone-b contains 2 replicas now in this case it is balanced according to maxskew across zones .

Now if it is imbalanced means de-scheduler should do the balance and try to evict the pods to do the balance( this is the expectation here )  . Now to do this it is enough to check the pods which are related to the  label filter that we set right?
am I missing anything here ?  Can you please confirm this

**Comment by damemi** [comment]
Yes, using the label selector will limit the descheduler to checking pods with that label.

**Comment by LAVA-KUMAR** [comment]
And also can you please confirm the following queries actually I am testing in staging eks cluster from last one week few things I have observed and have few queries prior to moving to production can you please confirm this .

q1) I saw that few times even though it is balanced across zones it did the eviction some times  , I am sharing the policy config and topology spread constraint config that I have used :

Policy :
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    evictLocalStoragePods: true
    strategies:
      "RemovePodsViolatingTopologySpreadConstraint":
         enabled: true
         params:
          labelSelector:
            matchLabels:
              app: test
          includeSoftConstraints: false
          
          
 Topology config for the app test :
     spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: proxy
              
  So across the  zones if there is imbalance pods according to maxskew acorss the zones then it should the balance this is expectation here .
Am I configuring properly the descheduler policy here , if anything miss configured in the policy config please correct me .


q2)  how many nodes descheduler can handle inside a single eks cluster with configured resources . 
Thanks in advance.

**Comment by damemi** [comment]
@LAVA-KUMAR can you share the logs from your descheduler? Preferably at log level `v=4` if possible. There is not much I can do to debug your issue without seeing what is happening.

I do notice that your descheduler labelselector has `app: test` and your topology config has `app: proxy`. This could be the problem.

For q2) we don't have an exact max load but you can expect performance to degrade proportionally in very large clusters.

**Comment by LAVA-KUMAR** [comment]
"I do notice that your descheduler labelselector has app: test and your topology config has app: proxy. This could be the problem".
Sorry here this is wrongly typed , app name was here "test" both places . Thanks.

**Comment by damemi** [comment]
That's interesting, is it always the 2 `logstash-production/common-logstash-prod` pods that are evicted? Maybe you could share the pod yaml for those pods which might tell us more.

> Here in my app i have replica count as 6 ( in one zone it has 4 and other zone it has 2 which was actually balanced according to the maxskew 1 that was set) .

Maybe this was a typo, but 4 & 2 is not balanced with maxskew=1. Still, it should only be trying to evict 1 pod to balance them

**Comment by LAVA-KUMAR** [comment]
Hope this helps :
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
spec:
  revisionHistoryLimit: 5
  replicas: 0
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: common
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1a
                      - us-east-1b

**Comment by LAVA-KUMAR** [comment]
Hi make , any update on above ?
