### ISSUE TITLE
Skipping eviction for pod, doesn't tolerate node taint....

### ISSUE THREAD

**Issue by medicol69** [kubernetes-sigs/descheduler#1091]
Hello, I've installed the descheduler v0.23. version on a k8 1.23.15 version,  and I have a lot logs saying this:

"Pods on node" node="worker3" allPods=58 nonRemovablePods=16 removablePods=42
""Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
"**Skipping eviction for pod, doesn't tolerate node taint...."**, 

what does that actually men ("**Skipping eviction for pod**")??? I did look at the code a bit but just wanted to check with you if I have to setup some taints on my deployments to give scheduler a heads up to erase some pods.

Tnx a bunch!

**Comment by damemi** [comment]
Hi @medicol69,
This means that your pod could be evicted, but all of the possible nodes that would be better for it have taints which the pod doesn't tolerate. You can either add a toleration to the pod, or remove the taints from these nodes.

**Comment by medicol69** [comment]
Tnx, but the thing is that the worker nodes don't have any taints!

**Comment by damemi** [comment]
Do any of your nodes have taints? The descheduler doesn't distinguish between worker and master nodes for instance.

This message comes from LowNodeUtilization, so it sounds like you're using that strategy. It's possible then that all of your worker nodes are overutilized, so the descheduler is seeing a master node as underutilized. But if the master node is tainted, then you'll see the message above.

If you have a full descheduler log, that would give a lot more information about the situation. It's tough to debug from this one line.

**Comment by medicol69** [comment]
Yes, I've seen the master nodes in the logs, is there a way to exclude them?

**Comment by damemi** [comment]
It's just like a k8s node selector (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector), so it's based on node labels. ie `labelA=value` will select the nodes that have `labelA` = `value`

**Comment by medicol69** [comment]
ah zo, so all the worker nodes need to have a distinct label, so It can just select them, it won't work with a list of all different labels, right?
