### ISSUE TITLE
underutilized nodes are not detectable

### ISSUE THREAD

**Issue by deenu7724** [kubernetes-sigs/descheduler#1094]
**What version of descheduler are you using?**

descheduler version: v0.25.1

**Does this issue reproduce with the latest release?** yes

**Which descheduler CLI options are you using?** 
[descheduler-64cfdf7f6c-n2xq5.log](https://github.com/kubernetes-sigs/descheduler/files/11007995/descheduler-64cfdf7f6c-n2xq5.log)
 No

**Please provide a copy of your descheduler policy config file**

apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 60
           "memory": 60
           "pods": 10
         targetThresholds:
           "cpu" : 80
           "memory": 80
           "pods": 28

**What k8s version are you using (`kubectl version`)?**
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version 

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
</pre></details>

**What did you do?**
I copied the git repo and run the command to deploy it as deployment.

**What did you expect to see?**
it should have shown the nodes which is having resources less than 60% should consider as underutilized but it show as appropriate utilized 

**What did you see instead?**

I0318 08:31:10.369732       1 nodeutilization.go:202] "Node is appropriately utilized" node="ip-10-0-1-10.ec2.internal" usage=map[cpu:1310m memory:8448Mi pods:6] usagePercentage=map[cpu:33.41836734693877 memory:27.47757580038873 pods:10.344827586206897]
I0318 08:31:10.369991       1 nodeutilization.go:199] "Node is overutilized" node="ip-10-0-1-23.ec2.internal" usage=map[cpu:1510m memory:1706Mi pods:19] usagePercentage=map[cpu:78.23834196891191 memory:11.310234594863086 pods:65.51724137931035]
I0318 08:31:10.370166       1 nodeutilization.go:199] "Node is overutilized" node="ip-10-0-1-239.ec2.internal" usage=map[cpu:1510m memory:1786Mi pods:19] usagePercentage=map[cpu:78.23834196891191 memory:11.840609019006724 pods:65.51724137931035]
I0318 08:31:10.370359       1 nodeutilization.go:199] "Node is overutilized" node="ip-10-0-1-40.ec2.internal" usage=map[cpu:1820m memory:1764Mi pods:19] usagePercentage=map[cpu:94.30051813471502 memory:11.694756052367223 pods:65.51724137931035]
I0318 08:31:10.370522       1 nodeutilization.go:199] "Node is overutilized" node="ip-10-0-2-188.ec2.internal" usage=map[cpu:1510m memory:1706Mi pods:20] usagePercentage=map[cpu:78.23834196891191 memory:11.310234594863086 pods:68.96551724137932]
I0318 08:31:10.370716       1 nodeutilization.go:199] "Node is overutilized" node="ip-10-0-2-197.ec2.internal" usage=map[cpu:1410m memory:1636Mi pods:18] usagePercentage=map[cpu:73.05699481865285 memory:10.846156973737402 pods:62.06896551724138]
I0318 08:31:10.370897       1 nodeutilization.go:199] "Node is overutilized" node="ip-10-0-2-214.ec2.internal" usage=map[cpu:1410m memory:3044Mi pods:13] usagePercentage=map[cpu:73.05699481865285 memory:20.180746838665435 pods:44.827586206896555]
I0318 08:31:10.371066       1 lownodeutilization.go:135] "Criteria for a node under utilization" CPU=70 Mem=60 Pods=10
I0318 08:31:10.371214       1 lownodeutilization.go:136] "Number of underutilized nodes" totalNumber=0
I0318 08:31:10.371366       1 lownodeutilization.go:149] "Criteria for a node above target utilization" CPU=80 Mem=80 Pods=28
I0318 08:31:10.371515       1 lownodeutilization.go:150] "Number of overutilized nodes" totalNumber=6

**Comment by deenu7724** [comment]
I did the changes suggested by you and it worked and getting the node underutilized but still pods are not being moved. Following is logs please have a look and suggest a fix for it

[Uploading descheduler-7d8b9cb5b-7h25t.log…]()

**Comment by damemi** [comment]
@deenu7724 for some reason the link you shared doesn't work for me

It's possible that the pods might not be evictable for some reason (see https://github.com/kubernetes-sigs/descheduler#pod-evictions). If you run at log level `v=4` it will print any reasons for that
