### ISSUE TITLE
Does cordon evict the pods of the configured node

### ISSUE THREAD

**Issue by lcroms** [kubernetes-sigs/descheduler#1114]
I am contacting you because an issue occurred during the recent eks version upgrade.

After upgrading the cluster version of eks, we planned to replace the node through pod redistribution after setting cordon for node, but as soon as cordon was set, all pods of the corresponding node were removed. is being figured out. Does the decheduler forcefully remove the pod from the node where the cordon is set and assign it to another node?

If so, I wonder if it is possible to disable that feature.

**Comment by damemi** [comment]
Are you using the [RemovePodsViolatingNodeTaints](https://github.com/kubernetes-sigs/descheduler/tree/v0.26.0#removepodsviolatingnodetaints) strategy? If so, you can either use the `excludedTaints` field to exclude the `node.kubernetes.io/unschedulable` taint (this is what `kubectl cordon` applies to the node), or set a `nodeSelector` in the [top-level descheduler config](https://github.com/kubernetes-sigs/descheduler/tree/v0.26.0#policy-and-strategies) to exclude the cordoned node from descheduling.

**Comment by lcroms** [comment]
@damemi 
Thank you.
Let's apply those settings.
