### ISSUE TITLE
Upgrade from 1.24.1 to 1.25.0 is failing with no kind \"eviction\" is registered for version \"policy/v1\"

### ISSUE THREAD

**Issue by jainasanthosh2023** [kubernetes-sigs/descheduler#1140]
Recently I try upgrading from 1.24.1 to 1.25.0 using helm chart with old working values.yaml.

I do see the below error appear when it tries to evict the pods.

"error evicting pod" err="eviction in version \"v1\" cannot be handled as a eviction: no kind \"eviction\" is registered for version \"policy/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30\""

Just I would like to understand, are there any breaking changes with 1.25.0. If so do i need to update any.

Kubernetes Version: v1.18.17

as per the compatibility matrix given in the documentation, 1.24 should not work but is working. So I just would like to check if this error is due to old kubernetes version?, If so I am ok.

**Comment by a7i** [comment]
/king support

`policy/v1beta1` is removed in Kubernetes 1.25, so Descheduler v0.25 uses `policy/v1` from v0.25 and onwards.

Please view the compatibility matrix [here](https://github.com/kubernetes-sigs/descheduler#compatibility-matrix) and note that Descheduler honors a 3 version skew. Meaning that if you are on Kubernetes 1.18, only supported Descheduler versions are 0.16, 0.17, and 0.18

**Comment by jainasanthosh2023** [comment]
Thank you very much for your explanation.
