### ISSUE TITLE
What does "evicted" mean?

### ISSUE THREAD

**Issue by marandalucas** [kubernetes-sigs/descheduler#1153]
**What does "evicted" mean?**

We are confused about the evicted meaning. 

Imagine the scenario below:

- A Kubernetes Deployment with only 1 replica.
- Descheduler for some reason needs to evict the pod with a single replica.
- Does Descheduler kill the pod? 
- Does the Descheduler roll out the pod based on the default Kubernetes strategy of RollingUpdate?

We are concerned about the "Descheduler" behaviour. We have workloads with only one replica, we want to make sure Descheduler won't kill them directly.

Thank you so much

**Comment by damemi** [comment]
Descheduler uses the [Eviction API](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/) to request pod evictions. This means it respects things like pod disruption budgets and termination grace periods before the pod is deleted. Essentially, once it makes the request, the actual deletion is up to k8s to handle. There are other options in the [descheduler evictor](https://github.com/kubernetes-sigs/descheduler#evictor-plugin-configuration-default-evictor) to make this even stricter, such as setting a priority threshold.

Descheduler does not roll out any new pods, that is entirely up to the pod's owning controller to handle. It only initiates evictions.
