### ISSUE TITLE
Is it based on kubectl top node CPU & memory?

### ISSUE THREAD

**Issue by mossuchida** [kubernetes-sigs/descheduler#118]
While I am using this descheduler, I have noticed that the log shows the exactly the same number of memory utilization for many nodes. Also, each node shows exactly the same number of CPU util & memory util in the log. it seems like descheduler is calculating the utilization from resource requests & limits?
I was hoping it is utilizing the kubectl top nodes to calculating current utilization (which should reflect the results in the log with dynamically changing % of CPU & memory util at the moment).  Please clarify how is it calculating the current node resource utilization.

e.g. here is the data that I am talking:  in the log, I see this: Node “172.16.4.3" is appropriately utilized with usage: api.ResourceThresholds{“cpu”:52.5, “memory”:32.080248132547204, “pods”:41.25} but kubectl top node shows 172.16.4.3    2025m        25%       8699Mi          55% - meaning CPU 25%, memory 55% utilized 
Also, many of my pods are showing memory utilization exactly same as "memory":4.193744917801392

**Comment by aveshagarwal** [comment]
@mossuchida descheduler follows what kube-scheduler does. As kube-scheduler works based on pods requests, descheduler also works based on pods requests. IMO, making descheduler work on real time utilization (like kubectl top) without kube-scheduler working on real time usage might lead to mismatch how pods are evicted by descheduler and then how replacement pods are scheduled by kube-scheduler.

But as soon as kube-scheduler starts supporting real time usage, descheduler would start that too.

**Comment by AndresPineros** [comment]
I don't understand why is the descheduler using the "requests". For me the idea of the descheduler was to balance the cluster when the requests where not properly assigned, for example, a service wasn't expected to consume 5Gi of RAM and a limit wasn't set for it. Balancing using the requests is already done by the Kubernetes scheduler, right? So, what is the point of the descheduler then?

**Comment by aveshagarwal** [comment]
> I don't understand why is the descheduler using the "requests". For me the idea of the descheduler was to balance the cluster when the requests where not properly assigned, for example, a service wasn't expected to consume 5Gi of RAM and a limit wasn't set for it. 

Descheduler only evicts pods but kube-scheduler does the actual scheduling of replacement pods. So if Descheduler acted based on anything other than requests, it would lead to mismatch between Descheduler and kube-scheduler as kube-scheduler would still schedule based on requests.   

>Balancing using the requests is already done by the Kubernetes scheduler, right?

kube-scheduler tries to balance only at the admission time for incoming pods, it does not rebalance already admitted pods.


> Without real-time the descheduler only tries to fill empty nodes, it doesn't try to save loaded nodes that are about to die due to resources.

No, descheduler does both as far as cluster has capacity. It tries to move pods from loaded nodes to less loaded nodes.

**Comment by tmwtp** [comment]
> > I don't understand why is the descheduler using the "requests". For me the idea of the descheduler was to balance the cluster when the requests where not properly assigned, for example, a service wasn't expected to consume 5Gi of RAM and a limit wasn't set for it.
> 
> Descheduler only evicts pods but kube-scheduler does the actual scheduling of replacement pods. So if Descheduler acted based on anything other than requests, it would lead to mismatch between Descheduler and kube-scheduler as kube-scheduler would still schedule based on requests.
> 
> > Balancing using the requests is already done by the Kubernetes scheduler, right?
> 
> kube-scheduler tries to balance only at the admission time for incoming pods, it does not rebalance already admitted pods.
> 
> > Without real-time the descheduler only tries to fill empty nodes, it doesn't try to save loaded nodes that are about to die due to resources.
> 
> No, descheduler does both as far as cluster has capacity. It tries to move pods from loaded nodes to less loaded nodes.

@aveshagarwal - I am reading the Rescheduler-Design-Implementation (https://docs.google.com/document/d/1KXw02Q0cOF1MUrdpPNiug0yGZlixvPg2SwBycrT5DkE/edit) and saw it should support also the HighNodeUtilization option.

Per your above answer i understand that the descheduler should avict pods from nodes that reached high thresholds. 

This is what i am trying to achieve but cannot seem to get that to work :(

Any idea how does a policy that balances HighNodeUtilization nodes should be defined ?

Thank you

Roiy

**Comment by AndresPineros** [comment]
@tmwtp Hey, I think I found what we were looking for. Not a 100% sure though:
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/
https://docs.okd.io/latest/admin_guide/out_of_resource_handling.html

Some arguments in the Kubelet actually allow to evict pods from nodes under pressure. Mixing this with the descheduler (they way it works right now, not with real time resources) seems like a great combo.

**Comment by InAnimaTe** [comment]
Can someone clear this up for me then? So Descheduler literally does nothing for real node metrics, only acting on container `resource.requests`? So if I don't have any `resources` defined for my deployments, Descheduler won't help me in any way?

A little disheartening to be honest.

**Comment by aveshagarwal** [comment]
> Can someone clear this up for me then? So Descheduler literally does nothing for real node metrics, only acting on container resource.requests? So if I don't have any resources defined for my deployments, Descheduler won't help me in any way?

Kubernetes's core/default scheduler does scheduling based on resource.requests, and Descheduler follows it.

**Comment by InAnimaTe** [comment]
Thanks for clearing that up. Really, that's the best you can do. I kind of just assumed otherwise since I really have a usecase for something that can help when we have so many services which don't have `resources` defined.

**Comment by sidharthsurana** [comment]
/remove-lifecycle rotten

Is there any near term plans to add this support?
