### ISSUE TITLE
Strategy - Exclude Namespaces

### ISSUE THREAD

**Issue by maw1146** [kubernetes-sigs/descheduler#1185]
Hi,
I'm not sure if this is a bug or I'm doing something wrong.

In the HelmRelease values, I setup different strategies and applied the param to exclude namespaces, however it still tries to evict pods in these namespaces.

Here couple of examples:
`        RemovePodsViolatingTopologySpreadConstraint:
          enabled: true
          params:
            namespaces:
              exclude:
                - "istio-system"
                - "vsphere-csi"
            includeSoftConstraints: false
        LowNodeUtilization:
          enabled: true
          params:
            namespaces:
              exclude:
                - "istio-system"
                - "vsphere-csi"
            nodeResourceUtilizationThresholds:
              thresholds:
                # cpu: 15
                # memory: 20
                # pods: 10
                cpu: 30
                memory: 40
                pods: 25
              targetThresholds:
                cpu: 45
                memory: 50
                pods: 30`

**Comment by maw1146** [comment]
Here maybe is better:
        RemovePodsViolatingTopologySpreadConstraint:
          enabled: true
          params:
            namespaces:
              exclude:
                - "istio-system"
                - "vsphere-csi"
            includeSoftConstraints: false
        LowNodeUtilization:
          enabled: true
          params:
            namespaces:
              exclude:
                - "istio-system"
                - "vsphere-csi"
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 30
                memory: 40
                pods: 25
              targetThresholds:
                cpu: 45
                memory: 50
                pods: 30

**Comment by damemi** [comment]
@maw1146 could you provide the whole descheduler config? You can also wrap it in 3 backticks (```) for multiline code to preserve indentation

**Comment by dvdmuckle** [comment]
I feel this may be similar to an issue my team is currently running into, except with `namespaces.include`. I can paste our helm config here, or I can open up a new issue.

**Comment by damemi** [comment]
@dvdmuckle sure, feel free to post your config here. If you have descheduler logs too, that would also help
