### ISSUE TITLE
TopologySpreadConstraint calculations do not fully respect node selectors, node affinity policy, and/or node taints policy

### ISSUE THREAD

**Issue by MarcPow** [kubernetes-sigs/descheduler#1204]
descheduler version: 0.27.1
k8s version: v1.26.3
policy: RemovePodsViolatingTopologySpreadConstraint

Simple example:  When running in a cluster with both Windows and Linux nodes, if a pod has a single-os node selector, but topologyBalanceNodeFit is false, the introduction of nodes of the other OS will throw off balance computations and introduce additional churn.

**Comment by a7i** [comment]
Addressed in #1218
