### ISSUE TITLE
StatefulSet Not Balancing via RemovePodsViolatingTopologySpreadConstraint

### ISSUE THREAD

**Issue by pauliandraper** [kubernetes-sigs/descheduler#1212]
**What version of descheduler are you using?**

descheduler version: v0.27.1

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
N/A

**Please provide a copy of your descheduler policy config file**

`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: DefaultEvictor
          args:
            evictLocalStoragePods: true
            ignorePvcPods: true
        - name: "RemovePodsViolatingTopologySpreadConstraint"
          args:
            includeSoftConstraints: true
            namespaces:
              include:
              - "testing"
        plugins:
          balance:
            enabled:
              - "RemovePodsViolatingTopologySpreadConstraint"
          deschedule:
            enabled:`

**What k8s version are you using (`kubectl version`)?**
1.25.6 (AKS)
<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**
When testing descheduler in our development environment, I've come across a problem whereby one of our StatefulSets won't balance. Other similar pods are balancing acceptably, but despite there being other suitable nodes within a node pool with the appropriate taints it won't move.

In our dev environment, the StatefulSet has 2 replicas, with a maxSkew of 1. A deployment with the same pod count on the same node pool was evicted and rescheduled, but this one wasn't.

I've attempted to slowly add the same settings to a new StatefulSet to try and replicate the issue, but I've been unable to so far.

Here is the StatefulSet in question.;
`apiVersion: apps/v1

kind: StatefulSet
metadata:
  name: placeholder-testing
  namespace: testing
  labels:
    app: testing
spec:
  replicas: #{ReplicaCount}#
  selector:
    matchLabels:
      app: testing
  serviceName: placeholder-testing
  template:
    metadata:
      labels:
        app: testing
        tags.datadoghq.com/env: #{branch}#-#{location}#
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: placeholder-testing
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - integrations
                - integrations2
      containers:
      - name: placeholder-testingservice
        image: #{RegistryName}#/placeholder.testingservice:latest
        resources:
          requests:
            memory: #{testingServiceMemoryRequest}#
          limits:
            memory: #{testingServiceMemoryLimit}#
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: DD_SERVICE
            value: placeholder-testingservice
          - name: DD_VERSION
            value: "#{Release.Artifacts._placeholder.testingService.BuildId}#"
        ports:
        - containerPort: 13000
          name: admin-port
        - containerPort: 13013
          name: sendsms-port
        volumeMounts:
          - name: testing-conf
            mountPath: "/etc/testing"
            subPathExpr: $(POD_NAME)
          - name: testing-log
            mountPath: "/var/log/testingarchive"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /usr/bin/livenessProbe.bash
          periodSeconds: 3
          timeoutSeconds: 2
          initialDelaySeconds: 20
        startupProbe:
          exec:
            command:
            - /bin/bash
            - /usr/bin/livenessProbe.bash           
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 15
      - name: placeholder-testingmonitor
        image: #{RegistryName}#/placeholder-testingmonitor:latest
        resources:
          requests:
            memory: #{testingMonitorMemoryRequest}#
          limits:
            memory: #{testingMonitorMemoryLimit}#
        env:
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
            secretKeyRef:
              name: testingservicesecrets
              key: AppInsightsInstrumentationKey
        - name: testingBaseUri
          value: http://localhost:13000
        - name: EventGrid__Topic
          value: #{EventGridTopic}# 
        - name: EventGrid__AccessKey
          valueFrom:
            secretKeyRef:
              name: testingservicesecrets
              key: EventGridAccessKey
        - name: DD_SERVICE
          value: placeholder-testingmonitor
        - name: DD_VERSION
          value: "#{Release.Artifacts._placeholder.testingMonitor.BuildId}#"              
        - name: CORECLR_ENABLE_PROFILING
          value: "1"
        - name: CORECLR_PROFILER
          value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
        - name: CORECLR_PROFILER_PATH
          value: "/app/datadog/linux-x64/Datadog.Trace.ClrProfiler.Native.so"
        - name: DD_DOTNET_TRACER_HOME
          value: "/app/datadog"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: DD_API_KEY
          value: #{DataDogApiKey}#
        - name: DD_SITE
          value: #{DataDogSite}#
        - name: DD_LOGS_DIRECT_SUBMISSION_INTEGRATIONS
          value: "ILogger"
        - name: DD_TRACE_SAMPLE_RATE
          value: "#{DataDogSampleRate}#"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          periodSeconds: 3
          timeoutSeconds: 2
      tolerations:
      - key: "requiresVPNAccess"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: testing-conf
        azureFile:
          secretName: testingservicesecrets
          shareName: testingconf
          readOnly: true
      - name: testing-log
        azureFile:
          secretName: testingservicesecrets
          shareName: testinglog`

I've attempted stage-by-stage creating a new StatefulSet which has the same settings, but I've not managed to replicate it so far.

**What did you expect to see?**
One of the 2 pods to be evicted and moved to the other server.

**What did you see instead?**
None of the pods for the given StatefulSet were moved;
`I0801 13:13:41.463965       1 topologyspreadconstraint.go:202] "Skipping topology constraint because it is already balanced" constraint={MaxSkew:1 TopologyKey:topology.kubernetes.io/zone WhenUnsatisfiable:ScheduleAnyway LabelSelector:&LabelSelector{MatchLabels:map[string]string{app: placeholder-testing,},MatchExpressions:[]LabelSelectorRequirement{},} MinDomains:<nil> NodeAffinityPolicy:<nil> NodeTaintsPolicy:<nil> MatchLabelKeys:[]}`

**Comment by a7i** [comment]
Hi @pauliandraper Any chance that there are more pods in the same namespace with the label `app=placeholder-testing`?

**Comment by pauliandraper** [comment]
Apologies for the slow response. No, the only ones in this namespace with that label are all created from the same statefulset, as above.

**Comment by a7i** [comment]
@pauliandraper if you could use ``` to ensure that tabs and spaces are preserved, it would be great.

What I noticed in your StatefulSet definition that the `topologySpreadConstraints`'s `matchLabels` do not match the Pod's `labels`.

```yaml
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: ScheduleAnyway
  labelSelector:
    matchLabels:
      app: placeholder-testing
```
Note that above is using `app: placeholder-testing` while the Pod's definition below uses `app: testing`

```yaml
template:
  metadata:
    labels:
      app: testing
```

As a result, Descheduler's logic will not match any of the StatefulSet Pods to balance.

**Comment by a7i** [comment]
Feel free to reopen if the solution above did not fix it
