### ISSUE TITLE
Nodes resource mismatch

### ISSUE THREAD

**Issue by 19bcs2405** [kubernetes-sigs/descheduler#1234]
I have install descheduler on my cluster. kubectl top node command gives different output than descheduler.
Descheduler shows All nodes are underutilized. but when used kubectl top node command, its show many off nodes are on 100% utilization.

How to fix this bug. Please guide me.

**Comment by a7i** [comment]
/kind support

@19bcs2405 Per README:

> [LowNodeUtilization](https://github.com/kubernetes-sigs/descheduler#lownodeutilization) Spreads pods according to pods resource requests and node resources available

> [HighNodeUtilization](https://github.com/kubernetes-sigs/descheduler#highnodeutilization) Spreads pods according to pods resource requests and node resources available

As the description suggests, these strategies do not consider actual utilization but rather resource allocation (poor naming). `kubectl top` looks at actual resource utilization.

There are a few open PRs that look at utilization such as:
https://github.com/kubernetes-sigs/descheduler/pull/1092
https://github.com/kubernetes-sigs/descheduler/pull/1087

Given that they behave correctly, I am going to close this issue but feel free to reopen if you think there is a bug.

**Comment by a7i** [comment]
That's what these PRs do (as new Plugins):
https://github.com/kubernetes-sigs/descheduler/pull/1092
https://github.com/kubernetes-sigs/descheduler/pull/1087
