### ISSUE TITLE
Version Compatbility Matrix unclear

### ISSUE THREAD

**Issue by arousseau-coveo** [kubernetes-sigs/descheduler#1244]
**What version of descheduler are you using?**

descheduler version: 0.27.1

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
N/A

**Please provide a copy of your descheduler policy config file**
N/A

**What k8s version are you using (`kubectl version`)?**
N/A
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
N/A

**What did you expect to see?**

Clear information about version compatibility. 

**What did you see instead?**
The version [compatibility matrix](https://github.com/kubernetes-sigs/descheduler#compatibility-matrix) informations doesn't seems to reflect the current state of the descheduler. 

> However a particular descheduler release is only tested against the three latest k8s minor versions. For example descheduler v0.18 should work with k8s v1.18, v1.17, and v1.16.

The above sentence lets presume that 0.27 will works with k8s 1.27, 1.26,1.25 but while running 0.27 on k8s 1.25 we face the following warning: 
`Warning: Descheduler minor version 27 is not supported on your version of Kubernetes 1.25+. See compatibility docs for more info: https://github.com/kubernetes-sigs/descheduler#compatibility-matrix`

Also 
>  version 27 is not supported on your version of Kubernetes 1.25+

Let presume descheduler version 0.27 will not work for kubernetes version 1.25, 1.26, 1.27, 1.28 .... which is probably not the case.

So what information is correct here ?

**Comment by a7i** [comment]
Hi @arousseau-coveo we run integration tests against the current release and 2 previous versions so you are correct that v0.27 should work with Kubernetes 1.25, 1.26, and 1.27

I noticed that you left the `kubectl version` empty. Would you be able to provide your server version so I can make sure we're parsing it correctly? Thanks!

**Comment by arousseau-coveo** [comment]
> Hi @arousseau-coveo we run integration tests against the current release and 2 previous versions so you are correct that v0.27 should work with Kubernetes 1.25, 1.26, and 1.27
> 
> I noticed that you left the `kubectl version` empty. Would you be able to provide your server version so I can make sure we're parsing it correctly? Thanks!

@a7i  I just added the output now I feel it's because of how EKS format the versions that we have that message.

**Comment by a7i** [comment]
Thank you for raising this and providing the data.

I should be able to get a fix soon and get it out in the next patch or minor release.
