### ISSUE TITLE
Kustomize template ref=v0.28.0 references to 0.27.1

### ISSUE THREAD

**Issue by fvasco** [kubernetes-sigs/descheduler#1261]
The command:

```sh
kubectl create --dry-run=client -o yaml -k 'github.com/kubernetes-sigs/descheduler/kubernetes/job?ref=v0.28.0' | grep image
```

returns the output: `image: registry.k8s.io/descheduler/descheduler:v0.27.1`
The correct result should be: `image: registry.k8s.io/descheduler/descheduler:v0.28.0`

**Comment by a7i** [comment]
Addressed in v0.28.1
Please feel free to reopen if you still see this issue
