### ISSUE TITLE
I run ./hack/update-generated-defaulters.sh but no code generated

### ISSUE THREAD

**Issue by shentupenghui** [kubernetes-sigs/descheduler#1297]
hi:
   I face a problem while add a plugin to descheduler.
   what I have done:
   
<img width="1152" alt="image" src="https://github.com/kubernetes-sigs/descheduler/assets/25290236/8cdabf06-6bab-4679-8b55-db894ef499b4">
  what happend:
  no zz_generated.deepcopy.go created 
<img width="909" alt="image" src="https://github.com/kubernetes-sigs/descheduler/assets/25290236/cbb2e348-eb0c-4d5b-8a29-3be27932e149">

**Comment by a7i** [comment]
Hi @shentupenghui for this to work for me, I have the repo cloned in `$GOPATH/src/sigs.k8s.io/descheduler/`
Although some have mentioned that they don't need to do that.
