### ISSUE TITLE
Docs for CRDs missing

### ISSUE THREAD

**Issue by kaiivoschneider** [kubernetes-sigs/descheduler#1306]
Nowhere in docs it is stated how to install the custom resource definitions for rescheduler. Installation of descheduler works, but obviously I cannot create a DeschedulerPolicy because my cluster does not know this resource kind.

**Comment by grzesuav** [comment]
@kaiivoschneider it is not crd, it should be placed as config file in configmap

**Comment by grzesuav** [comment]
take a look at https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/templates/configmap.yaml and in general on this helm chart

**Comment by a7i** [comment]
@grzesuav is correct.

This also matches`KubeSchedulerConfiguration` which is not a CRD. Please feel free to reopen.

/kind support
/close
