### ISSUE TITLE
Kustomize template ref=v0.29.0 references to 0.28.1

### ISSUE THREAD

**Issue by fvasco** [kubernetes-sigs/descheduler#1339]
The command:

```sh
kubectl apply --dry-run=client -k 'github.com/kubernetes-sigs/descheduler/kubernetes/cronjob?ref=v0.29.0' -o yaml|grep 'image:'
```

returns the output: `image: registry.k8s.io/descheduler/descheduler:v0.28.1`
The correct result should be: `image: registry.k8s.io/descheduler/descheduler:v0.29.0`

Similar to: #1261

**Comment by a7i** [comment]
Fixed:
```
kubectl apply --dry-run=client -k 'github.com/kubernetes-sigs/descheduler/kubernetes/cronjob?ref=v0.29.0' -o yaml|grep 'image:'

              image: registry.k8s.io/descheduler/descheduler:v0.29.0
```

I will update our release process to reflect this. The initial challenge is that we need to create the tag to build the image, but can't update the manifests until the image is built.
