### ISSUE TITLE
Not installing CRDs

### ISSUE THREAD

**Issue by dhereish** [kubernetes-sigs/descheduler#1351]
descheduler version: 0.29.0

When installing with Helm chart CRDs not getting installed. 

Using apiVersion: "descheduler/v1alpha2" , kind: "DeschedulerPolicy"

When I try to create the policy manually it doen't find the CRD amd in you chart repo and your repo I can not seem to find the CRDs

**Comment by a7i** [comment]
The Policy config isn't a k8s resource (so you don't create it as a CRD). It is just a literal text file that you pass to the descheduler binary when it runs. In kubernetes, this can be done by creating a configmap with the config file as its data and using volume mounts to mount that configmap as a file in your Pod's container filesystem.

There are examples of doing this manually in the k8s manifests mentioned in the [quickstart guide](https://github.com/kubernetes-sigs/descheduler/tree/release-1.26#quick-start). The Helm chart makes this a little easier by parsing the options from a single values.yaml file.

Hope that helps!
/remove-kind bug
/kind support

Duplicate: https://github.com/kubernetes-sigs/descheduler/issues/1131

**Comment by damemi** [comment]
@a7i maybe we should put a small note in the readme to clarify that this is *not* a CRD
