### ISSUE TITLE
Bump Kubernetes dependencies to v0.30.0 alpha

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#1357]
Similar PR: https://github.com/kubernetes-sigs/descheduler/pull/1201

Bump to latest alpha or beta (if available)

**Comment by a7i** [comment]
@pravarag any interest in picking this up?

**Comment by pravarag** [comment]
> @pravarag any interest in picking this up?

Thanks for mentioning, I'll pick this up.
