### ISSUE TITLE
Is descheduler executed in a loop?

### ISSUE THREAD

**Issue by ipsum-0320** [kubernetes-sigs/descheduler#1377]
In the [line](https://github.com/ipsum-0320/descheduler/blob/4bd348d9b720d81328eb3110d1d8d6f3f291970d/pkg/descheduler/descheduler.go#L413) of this file, After wait.NonSlidingUntil() is submitted, the function ends, and defer cancel() will be executed, thus interrupting the cycle execution of wait.NonSlidingUntil().

This may mean that descheduler.runDeschedulerLoop() can only be executed once, regardless of whether rs.DeschedulingInterval is set or not.

I think this is a BUG.

**Comment by damemi** [comment]
Hi @ipsum-0320, have you run into any issues trying to run the descheduler in a loop? `wait.NonSlidingUntil()` should execute synchronously until the context channel is closed. So, that should block the deferred `cancel()` from `RunDeschedulerStrategies()` until the channel is closed from somewhere else.

**Comment by ipsum-0320** [comment]
> Hi @ipsum-0320, have you run into any issues trying to run the descheduler in a loop? `wait.NonSlidingUntil()` should execute synchronously until the context channel is closed. So, that should block the deferred `cancel()` from `RunDeschedulerStrategies()` until the channel is closed from somewhere else.

@damemi okok, i know what you mean, thank you very much! 😊
