### ISSUE TITLE
status.phase=Unknown not available in 1.29 release 

### ISSUE THREAD

**Issue by BiancaTofan** [kubernetes-sigs/descheduler#1394]
Hello,

I want to define in my descheduler policy state = unknown but I cannot since in ProfileName is the following defined list :  [Running Pending PodInitializing ContainerCreating ImagePullBackOff]. 
As the podlifetime plugin already exist, can you please add also the unknown string? It can be useful for clusters which have many pods in unknown state to be evicted. 

Thank you in advance!

**Comment by yuzhiquantubi** [comment]
I think it's already supported in pod life time plugin 
https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/podlifetime/validation.go#L50

**Comment by BiancaTofan** [comment]
in 1.29 release there is no unknown phase defined : https://github.com/kubernetes-sigs/descheduler/blob/release-1.29/pkg/framework/plugins/podlifetime/validation.go 

> I think it's already supported in pod life time plugin https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/podlifetime/validation.go#L50

**Comment by a7i** [comment]
That's correct, it's going to land in 1.30

https://github.com/kubernetes-sigs/descheduler/pull/1330

**Comment by BiancaTofan** [comment]
do you have any estimated date for when the version 1.30 will be released?

**Comment by a7i** [comment]
We're currently blocked on kind image version 1.30 being published, which is being discussed here: https://github.com/kubernetes-sigs/descheduler/issues/1391

We are working to expedite this and hopefully cut a release in the next few days

**Comment by a7i** [comment]
@BiancaTofan v0.30.0 has been released.

/close
