### ISSUE TITLE
Chart not available anymore

### ISSUE THREAD

**Issue by aggarwala3** [kubernetes-sigs/descheduler#1401]
Chart doesnt look to be available anymore at https://kubernetes-sigs.github.io/descheduler/

**What version of descheduler are you using?**
descheduler version: 0.29.9

**Does this issue reproduce with the latest release?**

**Which descheduler CLI options are you using?**
Trying to install using terraform provider

**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.25
</pre></details>

**What did you do?**
Simply trying to install descheduler on target cluster; which was working till yesterday but today onwards Chart isnt available anymore.

**What did you expect to see?**
Descheduler chart to be installed, like it was working till yesterday

**What did you see instead?**
Error
```
│ Error: could not download chart: Chart.yaml file is missing
```

**Comment by damemi** [comment]
Works for me:
```
$ helm repo add descheduler https://kubernetes-sigs.github.io/descheduler/
"descheduler" has been added to your repositories
$ helm install my-descheduler descheduler/descheduler --version 0.29.0
NAME: my-descheduler
LAST DEPLOYED: Tue May 14 16:49:06 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Descheduler installed as a CronJob.
```

From https://artifacthub.io/packages/helm/descheduler/descheduler. Maybe there is a cache issue with your local helm? (or maybe mine)

**Comment by sarg3nt** [comment]
@aggarwala3 This is a known bug in the upstream helm provider if you have a folder in your project named the same as the chart.  Make sure you do not have a `descheduler` folder and it should work fine.
Yes, the error is stupid.
