### ISSUE TITLE
`unknown field nodeAffinityType` error with v0.30.0

### ISSUE THREAD

**Issue by headyj** [kubernetes-sigs/descheduler#1420]
**What version of descheduler are you using?**

descheduler version: v0.30.0

**Does this issue reproduce with the latest release?**

Actually It only occurs with latest release

**Which descheduler CLI options are you using?**

default command sent by the cronjob: https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/templates/cronjob.yaml#L79-L89

**Please provide a copy of your descheduler policy config file**

default policy

**What k8s version are you using (`kubectl version`)?**

v1.29 (EKS)

**What did you do?**

Running the cronjob is not working since v0.30.0 with almost default chart values:

```
fullnameOverride: descheduler
cronJobApiVersion: batch/v1
schedule: "10 3 * * *"
suspend: false
``` 

**What did you expect to see?**

The job should be executed without error

**What did you see instead?**

It returns the following error:
```
descheduler-28615870-wl9vc E0529 03:20:38.162660       1 run.go:74] "command failed" err="failed decoding descheduler's policy config \"/policy-dir/policy.yaml\": strict decoding error: unknown field \"nodeAffinityType\""
```

**Comment by vytautaskelmelissislt** [comment]
Revert to v0.29.0 and everything will work like in charms.

**Comment by a7i** [comment]
I believe this was addressed in this PR: https://github.com/kubernetes-sigs/descheduler/pull/1412

I will work on cutting a patch release v0.30.1

**Comment by a7i** [comment]
Meanwhile you can try specifying your own policy as highlighted [here](https://github.com/duplabe/descheduler/blob/17af29afe418d56aff1954ee4ee0392e29b3fd5e/charts/descheduler/values.yaml#L103-L143)

**Comment by a7i** [comment]
https://github.com/kubernetes-sigs/descheduler/pull/1425

**Comment by a7i** [comment]
v0.30.1 is out, let me know how it goes.

I tested and verified default profile works ✔️

**Comment by headyj** [comment]
Thank you @a7i , I tested v0.30.1 and the cronjob is working now!

**Comment by a7i** [comment]
thank you for reporting this!

/close
