### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by anton-johansson** [kubernetes-sigs/descheduler#144]
Where is the official Docker image located? The [job example](../blob/master/kubernetes/job.yaml) says `descheduler:latest`, however, when I try to pull that image I just get:
```
➜ docker pull descheduler:latest
Error response from daemon: pull access denied for descheduler, repository does not exist or may require 'docker login'
```

**Comment by warmchang** [comment]
DIY?

![image](https://user-images.githubusercontent.com/13084624/57191730-49a88a00-6f5b-11e9-9577-70b0a8b083de.png)

**Comment by anton-johansson** [comment]
Yeah, I was hoping that we could avoid building and hosting the image ourselves. :(

**Comment by aveshagarwal** [comment]
@anton-johansson yes we have not pushed official descheduler images. In case you would want to help, you could look into the location/process kubernetes is using to push official images and we could use the same.

**Comment by aveshagarwal** [comment]
@rhockenbury

**Comment by rhockenbury** [comment]
It would be great to explore pushing an image to gcr.io, but in the meantime, would it be reasonable  to throw the latest image up on dockerhub? - https://hub.docker.com/r/aveshagarwal/descheduler

**Comment by aveshagarwal** [comment]
@rhockenbury  i have pushed 0.9.0 to docker hub: docker.io/aveshagarwal/descheduler:0.9.0

**Comment by seanmalloy** [comment]
I'm interested in working on this issue. Looks like the official container image would be something like `k8s.gcr.io/descheduler:0.9.0`. I'll try to research how to get this setup.

**Comment by aveshagarwal** [comment]
@seanmalloy thanks for working on this issue.

**Comment by seanmalloy** [comment]
I submitted #160 to get the `Makefile` updated with an option to push the container images.

**Comment by seanmalloy** [comment]
The `Makefile` changes have been merged to master.

I attended the SIG Scheduling meeting today, and it was recommend to reach out to @ravisantoshgudimetla to facilitate getting the official image pushed to k8s.gcr.io.

@ravisantoshgudimetla can you provide any insight on how to push the container image to k8s.gcr.io Or how would we setup an automated process to push the container images k8s.gcr.io?

**Comment by seanmalloy** [comment]
I submitted PR https://github.com/kubernetes/k8s.io/pull/296 to get the GCE staging repo created.

**Comment by rhockenbury** [comment]
Is this now waiting on just a new release, and maybe a readme update?

**Comment by seanmalloy** [comment]
@rhockenbury I believe next steps are ...

Test and merge #173. This will verify that @ravisantoshgudimetla and @aveshagarwal can push to the staging registry.

After that I need to clean up #164, so that the docs are correct. Then a new release would need to be created and the official container image pushed to the production registry.

**Comment by seanmalloy** [comment]
@aveshagarwal @ravisantoshgudimetla @damemi can one of you remove the `lifecycle/stale` label from this issue?

**Comment by seanmalloy** [comment]
Now that #173 is merged the descheduler now has an official staging registry in gcr.io that is confirmed to be working.

@ravisantoshgudimetla @aveshagarwal @damemi I'm going to investigate how to get the official production registry setup in gcr.io for the descheduler. I'll let you know what I find out.

**Comment by seanmalloy** [comment]
I believe I found the relevant documentation for how to make this all happen ...

* https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io
* https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md

It will take me some time to read through the docs and figure out next next, but I think it is getting pretty close now.

**Comment by seanmalloy** [comment]
@damemi @ravisantoshgudimetla @aveshagarwal I submitted pull request https://github.com/kubernetes/test-infra/pull/16022 to get a prow job created for automating descheduler container image builds. I believe the only other thing I need to do is get a GCB(Google Cloud Build) config file added to the descheduler repo.

**Comment by seanmalloy** [comment]
Work in progress PR to add the GCB config https://github.com/kubernetes-sigs/descheduler/pull/217.

**Comment by seanmalloy** [comment]
Last pull request before I close out this issue ... https://github.com/kubernetes/k8s.io/pull/570.

**Comment by seanmalloy** [comment]
/close

Starting with the v0.10.0 release the official contain image can be downloaded with a command similar to this ...

`docker pull us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0`

**Comment by stevehipwell** [comment]
Could the documentation be updated to show this? Also is there a plan to have an official Helm chart?

**Comment by seanmalloy** [comment]
@stevehipwell thanks for the feedback. I'm going to be submitting a PR in a week or two with some more comprehensive documentation for this project. I'll include the container image location in that PR.

Please submit a separate GitHub issue if you think having a helm chart would be a useful feature.

Thanks!
