### ISSUE TITLE
The descheduler supports limiting the total number of pods evicted per rescheduling cycle

### ISSUE THREAD

**Issue by zhifei92** [kubernetes-sigs/descheduler#1449]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The `descheduler` supports limiting the total number of pods evicted per rescheduling cycle. Although there have been a `MaxPodsToEvictPerNode` and `MaxPodsToEvictPerNamespace`, but it is not enough

The `MaxNoOfPodsToEvictTotal` serves to prevent scenarios where an unintended issue, such as a software bug or incorrect usage of Pod Disruption Budgets (PDBs), could result in a substantial number of pods being evicted simultaneously, potentially compromising the availability of services.

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version:

**Additional context**

**Comment by zhifei92** [comment]
If this feature is accepted, I would like to work on it.

/assign

**Comment by a7i** [comment]
seems reasonable to me.

cc: @damemi and @ingvagabund thoughts?

**Comment by zhifei92** [comment]
This feature has already been adopted internally within our company, and many business units consider it a necessity. 

I  opened a pull request, and if it is not accepted, I will close it.
