### ISSUE TITLE
Possibility of selecting nodes that descheduler analysis with Helm

### ISSUE THREAD

**Issue by livenson** [kubernetes-sigs/descheduler#1481]
I am trying to use descheduler to balance out pods in a cluster, mostly using LowNodeUtilization. I am installing using helm -- and I cannot seem to find a way to pass the nodeSelector for the algorithm with values.yaml. Is such a possibility missing or I just do not know where to look?

thanks for help!

**Comment by damemi** [comment]
Hi @livenson, nodeSelector is part of the `deschedulerPolicy`, so you should be able to pass it in values.yml like so: https://github.com/kubernetes-sigs/descheduler/blob/daaa3a277e1a119bb014e93fe64b3573548ae3a8/charts/descheduler/values.yaml#L92

**Comment by livenson** [comment]
@damemi , many thanks, that was indeed what I have overlooked.
