### ISSUE TITLE
Publish v0.31.0 GitHub Release

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#1494]

**Comment by walkamongus** [comment]
I'd like to see this release as well. Specifically I would be like the `minPodAge` evictor setting to be released.

**Comment by a7i** [comment]
appreciate the feedback to get this going.

the "bottleneck" is lack of contribution/review/automated-release. I will do my best to get all the PRs out today, but feel free to pick up one of the Issues to expedite the release.

**Comment by a7i** [comment]
all done! please report any issues and happy to investigate

/assign
/close
