### ISSUE TITLE
clarification on example nodeResourceUtilizationThresholds 

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/descheduler#150]
With the example
```
         thresholds:
           "cpu" : 20
           "memory": 20
           "pods": 20
         targetThresholds:
           "cpu" : 50
           "memory": 50
           "pods": 50
```

thresholds nodes that could be underutilized are "below thresholds", `--v=4` output:

```
I0514 20:14:06.750116       1 lownodeutilization.go:66] Criteria for a node under utilization: CPU: 50, Mem: 50, Pods: 10
I0514 20:14:06.750178       1 lownodeutilization.go:73] Total number of underutilized nodes: 1
I0514 20:14:06.750227       1 lownodeutilization.go:86] all nodes are under target utilization, nothing to do here
```

to me it seems that the example will never do anything?

**Comment by aveshagarwal** [comment]
> to me it seems that the example will never do anything?

Not clear what you mean by it? Could you explain a bit more? You could modify the thresholds according to scenario in your clusters?

**Comment by matti** [comment]
dunno, I spent two hours trying to figure out `threshold` and `targetThresholds` - I just think the example does not work.

Naturally I also tried multiple different configurations "to match my cluster scenario"

**Comment by matti** [comment]
And what I mean by "does not work" - the example will never delete *any* pods in *any* cluster.
