### ISSUE TITLE
Emit k8s Event When a Pod Is Evicted

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#166]
It would be useful if the descheduler emitted a k8s event when it successfully evicts a pod. The event should be created in same namespace as the evicted pod.

**Comment by seanmalloy** [comment]
It looks like the best place to do this would here ...

https://github.com/kubernetes-incubator/descheduler/blob/master/pkg/descheduler/evictions/evictions.go#L50-L51

**Comment by seanmalloy** [comment]
I would be happy to submit a pull request to add this feature.

**Comment by kivagant-ba** [comment]
@seanmalloy , so when will you be happy? ;)

**Comment by seanmalloy** [comment]
I created #83 to implement this.

**Comment by seanmalloy** [comment]
Pull request #183 was merged.
