### ISSUE TITLE
Descheduler evicts pods when they're not ready

### ISSUE THREAD

**Issue by disparo13** [kubernetes-sigs/descheduler#180]
My team is deploying apps, and pods need time to start to apply database changes with LiquiBase. LiquiBase is setting the lock, then performing changes, and releasing lock in the end. Only after that, the pod can pass the readiness probe. So the pod starts, setting the lock and its state kubectl showing like this:
`scheduler-6dddf5b468-rvlmn                    0/1     Running     0          13s`
but if descheduler runs at this moment being scheduled, it's killing the pod ungracefully, leaving the lock unreleased - I can see it in my cluster logs. So the next pod that is running after that just stucks and waiting for the lock being released, which will never happen. So descheduler mustn't kill the pods, that was not fully run, having the READY state like 0/1, 0/2, etc.

**Comment by disparo13** [comment]
> You have few options to mitigate this, based on https://github.com/kubernetes-sigs/descheduler#pod-evictions
> 
Not applicable. Basically, I want those pods to be evicted, but only after their full and proper start.

**Comment by hanumanthan** [comment]
@disparo13 is this still an issue?

I understand the lock part in your question, but if a pod has to be evicted what benefit it gets from passing the readiness probe before eviction ? 

@seanmalloy If there's more to this than that meets the eye, I can take a look into this.
While listing pods under each strategy, we can filter only ready pods. Few questions on what the behaviour should be under these strategies
1. MaxPodLifeTimeSeconds - when this value is less than readiness probe
2. NodeTaints - should we honour readiness when its on a tainted node
3. NodeUtilization - should we honour readiness when its a node is highly utilized

For other strategies, i believe there is on conflict on readiness probe and eviction.

**Comment by disparo13** [comment]
@hanumanthan yes, guess so. Probably, I wasn't as clear because English is not my mother's language. I meant that POD not exactly MUST but CAN be evicted, at some time, in the future. So, descheduler in a moment of it's run can remove pods with Ready state and ignore ones that Not ready.

**Comment by supersaeyan** [comment]
A parameter can be supported to explicitly state whether or not the pod should be ready before it is a candidate for eviction.

@hanumanthan In the questions mentioned, the user configuring the strategy, becomes responsible in choosing what is more important, if the parameter is used, logically it should take precedence.
