### ISSUE TITLE
"No such container" logs on each descheduler run

### ISSUE THREAD

**Issue by simonszu** [kubernetes-sigs/descheduler#191]
Hi,
i'm currently testing the descheduler on OpenShift 3.11 with Docker runtime. I have noticed that each run of the descheduler (it runs on minute */30) causes a few log lines like

```
Handler for GET /v1.21/containers/89692e18f2ecd948e4f2aa6b38c7ff02e91b255468947b34303594be92e2f410/json returned error. No such container. 89692e18f2ecd948e4f2aa6b38c7ff02e91b255468947b34303594be92e2f410
Handler for GET /v1.21/containers/8795635e8606de41a442bbd3172466309cfab1c75ee308608bab74122442cc1a/json returned error. No such container. 8795635e8606de41a442bbd3172466309cfab1c75ee308608bab74122442cc1a
```
Since the descheduling works fine, our log-management setup is going crazy, since these lines contain the word "error". I am searching for a technical explanation why the descheduler tries to access non-existent containers, and maybe getting a better idea than to modify the filters of our log management.

**Comment by seanmalloy** [comment]
@simonszu are you still facing this issue?
