### ISSUE TITLE
Master nodes trigger node utilisation policy

### ISSUE THREAD

**Issue by alperbas** [kubernetes-sigs/descheduler#206]
Hello,

Tested on descheduler v0.8 and v0.9. As the master nodes in the cluster are not heavily utilised, descheduler always thinks it needs to rebalance things because there are nodes under utilised. Is there an option or a config parameter that makes it ignore master nodes or certain labeled nodes?

Thanks!

**Comment by aveshagarwal** [comment]
you can try using node selectors: https://github.com/kubernetes-sigs/descheduler/blob/master/cmd/descheduler/app/options/options.go#L55-L56

**Comment by alperbas** [comment]
It did the trick. Thanks!
