### ISSUE TITLE
Switch to go modules.

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes-sigs/descheduler#207]
We need to look into if we could start using go modules for dependency management.

**Comment by damemi** [comment]
I had this as a sub-task under the last k8s bump (https://github.com/kubernetes-sigs/descheduler/issues/187). I've been looking into it and trying to get this started but I run into issues when it depends on `k8s.io/kubernetes`. I ended up opening https://github.com/kubernetes-sigs/descheduler/issues/200 to investigate if we can break some of these dependencies

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes-sigs/descheduler/issues/200#issuecomment-578241612

**Comment by damemi** [comment]
@aveshagarwal we should also tag a latest release, or start following upstream's release cycle, since the latest semver tag we have is https://github.com/kubernetes-sigs/descheduler/tree/v0.8.0 (last commit 2018)
