### ISSUE TITLE
manual overide annotation not working

### ISSUE THREAD

**Issue by tysen514** [kubernetes-sigs/descheduler#219]
I've been trying to use the annotation descheduler.alpha.kubernetes.io/evict so that the descheduler has something to work with because all of our pods have a local storage attachment.  Unfortunately, in our deployment files this isn't working.  Could I possibly have an example of how this would work within a deployment file?

**Comment by seanmalloy** [comment]
@tysen514 it looks like `"descheduler.alpha.kubernetes.io/evict": "true"` annotation feature was added in commit dc7f9efc19fd1acb67e14464c2f1d0830dfc3bcb. This commit is not part of the v0.9.0 release. I think you would need to compile the descheduler from the master branch if you want to use this feature.

I see you mentioned that your pods are using local storage. PR https://github.com/kubernetes-sigs/descheduler/pull/142, which is included in v0.9.0, added the CLI option `--evict-local-storage-pods` that allows the descheduler to evict pods with local storage.

**Comment by seanmalloy** [comment]
/close

@tysen514 the v0.10.0 container image is available at `us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0`. This image should have the feature you are looking for. Please re-open this issue if it is still not working with the v0.10.0 container image. Thanks!

**Comment by tysen514** [comment]
Not trying to reopen an old issue.  Just wanted to let you know that I was finally able to get back to this project and it is now working for us!  Thank you for your help.  We ultimately opted to go for the cli "--evict-local-storage-pods" route.  Thank you for all your hard work on a much needed k8s feature/option!
