### ISSUE TITLE
--descheduling-interval flag not functional

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#220]
The [`--descheduling-interval` flag](https://github.com/kubernetes-sigs/descheduler/blob/dd54f1a6560f2945502af3b5347beaeceb1449a2/cmd/descheduler/app/options/options.go#L51) doesn't seem to be wired up to anything.

As a user, I would expect this flag to set the descheduler to run continuously, with the interval between runs determined by the flag's value.

Doing so would allow the descheduler to be run as a standalone pod instead of a CronJob, which are not currently GA. Is there any previous discussion on this flag and its implementation?

**Comment by aveshagarwal** [comment]
cronjob are widely used so not sure it helps much.

**Comment by aveshagarwal** [comment]
and thats the reason to not implement it in the first place though initially we had thought about it.
