### ISSUE TITLE
Release v0.10.0

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#224]
It has been quite a while since the last scheduler release. I am proposing that descheduler release v0.10.0 is created in the near future. See below list of suggested pull requests that I think should be merged before the v0.10.0 release is created.

- [x] Implement --descheduling-interval CLI option https://github.com/kubernetes-sigs/descheduler/pull/221
- [x] Automated Container Image Builds https://github.com/kubernetes-sigs/descheduler/pull/217
- [x] Automated Container Image Builds Part 2 https://github.com/kubernetes/test-infra/pull/16022
- [x] Switch to Go modules https://github.com/kubernetes-sigs/descheduler/pull/216
- [x] Documentation updates https://github.com/kubernetes-sigs/descheduler/pull/208
- [x] Build automation clean up https://github.com/kubernetes-sigs/descheduler/pull/236  

Additionally this would be the first release where an official container image for descheduler can be pushed to gcr.io.

Normally I would create a milestone for tracking this stuff, but I don't have access to create/update milestones in the repo. So this is the best alternative I could come up with.

**Comment by seanmalloy** [comment]
@ravisantoshgudimetla @aveshagarwal @damemi let me know if you think this is a reasonable proposal.

Also ...

I think I can help out by reviewing #216 in the near future and I will also sign up for writing the release notes for v0.10.0. Let me know if there is anything else I could do to help with this.

**Comment by damemi** [comment]
Thanks @seanmalloy, definitely +1 to this.

It would also be nice if we could start tagging regular releases to coincide with our bumps for kubernetes versions. Maybe even use a matching version scheme like `v0.10.18`->k8s 1.18, etc.

**Comment by seanmalloy** [comment]
Rough draft of release notes. I'll probably review and revise these at least one by time myself, but if anyone else has any suggestions that would be cool too.

## New Features
* Users can specify pods that are safe to evict using annotation descheduler.alpha.kubernetes.io/evict - GH-186
* Create k8s events when pods are evicted - GH-183
* New strategy RemovePodsViolatingNodeTaints - GH-175

## Bug Fixes
* Fix duplicate strategy to also take namespace into account - GH-156
* Spelling fix - GH-178
* Fix typos in k8s yaml files - GH-193, GH-201

## Others
* Enable golangci-lint - GH-149
* Setup official Google Container Registry descheduler container image - GH-160, GH-173
* Improve duplicate strategy unit tests - GH-162
* Enable e2e tests in TravisCI - GH-169
* Migrated to kubernets-sig GitHub organization - GH-182
* Clean up golint - GH-190
* Switch from glog to klog - GH-192
* Bump k8s dependencies to v1.17 - GH-204
* Update to Go 1.13 - GH-209
* Update k8s yaml files to use priorityClassName instead of critical-pod annotation - GH-213

**Comment by damemi** [comment]
These release notes look good. #221 just merged so you can add that to the notes and cross it off in your original post. I'd like to get everything else in your first post finished too, hopefully before the 1.18 release of k/k

**Comment by aveshagarwal** [comment]
@seanmalloy release notes looks really good. thanks.

**Comment by ravisantoshgudimetla** [comment]
I agree with @damemi and @aveshagarwal on the release notes. This is really good. Thanks for working on this @seanmalloy

**Comment by seanmalloy** [comment]
Just one more PR to review and merge for the v0.10.0 release, https://github.com/kubernetes-sigs/descheduler/pull/208.

Here is a gist with the updated release notes. This should provide an easy copy and paste for the person that creates the release.

https://gist.github.com/seanmalloy/3ae02ebdad8519db0d2dddb3f36bb471

**Comment by aveshagarwal** [comment]
thanks a lot @seanmalloy and @damemi for your work on this release.

Would like to know your thoughts what you think if instead of making 0.10.0, we release 1.0.0?

**Comment by damemi** [comment]
I would like to get this to 1.0.0 as soon as we can, but I think we should first promote our APIs out of alpha before bumping to a major version release. Wdyt?

**Comment by seanmalloy** [comment]
I agree with @damemi. We have a some work to do before we are ready for v1.0.0. I think for now it would be best to stick with v0.10.0.

**Comment by aveshagarwal** [comment]
ok sounds good. Please let me know if we are ready and i will cut a release v0.10.0.

**Comment by aveshagarwal** [comment]
would like to get this PR: https://github.com/kubernetes-sigs/descheduler/pull/236 in before we cut a release.

**Comment by seanmalloy** [comment]
@aveshagarwal I'm not aware of anything else that needs to be merged prior to cutting the release. Let me know if you need any help with the [release process](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/releasing.md).

**Comment by aveshagarwal** [comment]
@seanmalloy as per the release process doc and semi auto version, i have completed first 3 steps. Feel free to go for other steps. Let me know if my help is needed.

**Comment by seanmalloy** [comment]
@aveshagarwal here is the PR for step 4 ... https://github.com/kubernetes/k8s.io/pull/570.

**Comment by aveshagarwal** [comment]
> @aveshagarwal here is the PR for step 4 ... [kubernetes/k8s.io#570](https://github.com/kubernetes/k8s.io/pull/570).

i have lgtm'ed, i am not sure if i can `/approve` too in that repo.

**Comment by seanmalloy** [comment]
> i have lgtm'ed, i am not sure if i can `/approve` too in that repo.

@aveshagarwal  you have been added to the OWNERS file [here](https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/images/k8s-staging-descheduler/OWNERS), so for future releases both you and @ravisantoshgudimetla will be able to approve descheduler image promotions.

Step 4 is done the image is available at `us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0`.

@aveshagarwal you can go ahead and complete the last two release steps, 5 and 6.

**Comment by aveshagarwal** [comment]
@seanmalloy thanks a lot for your help. I have published v0.10.0 now so step 5 done now. Feel free to to go for step 6.

**Comment by seanmalloy** [comment]
@aveshagarwal I'll do the 6th and final step. Thanks for your help?

**Comment by mattlqx** [comment]
FYI the release notes at https://github.com/kubernetes-sigs/descheduler/releases are incorrect as they state the image as `us.gcr.io/k8s-artifacts-prod/descheduler:v0.10.0` and not `us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0`.

**Comment by seanmalloy** [comment]
@aveshagarwal I had the incorrect image location in the release notes. Sorry about this. Can you edit the release notes to change the location of the container image to be `us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0`?

https://github.com/kubernetes-sigs/descheduler/releases/tag/v0.10.0

I completed step 6(send email). I'll close out this issue once the typo is fixed in the release notes.

**Comment by aveshagarwal** [comment]
@seanmalloy fixed the path.

**Comment by seanmalloy** [comment]
/close

Thanks for your help @aveshagarwal!
