### ISSUE TITLE
DuplicatePods strategy might be too broad

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#230]
Looking at the code for the `RemoveDuplicatePods` strategy, it seems to consider pods as duplicates of each other if they have the same owner and are in the same namespace.

However, wouldn't it be possible that 2 entirely different pods could have the same owner? Say for example I have a controller that creates pods that serve different functions, but are both owned by the same controller. Would RemoveDuplicates consider these to be duplicate, and if so how could I know which one is going to be deleted?

**Comment by ingvagabund** [comment]
> However, wouldn't it be possible that 2 entirely different pods could have the same owner? Say for example I have a controller that creates pods that serve different functions, but are both owned by the same controller. Would RemoveDuplicates consider these to be duplicate, and if so how could I know which one is going to be deleted?

Pods owned by the same controller (running on the same node) originating from the same RC/RS/... are seen as cattle. Is your question about "which one is going to be deleted" still valid under that assumption?

**Comment by aveshagarwal** [comment]
when pods belong to same controller and are more than one on same node, then except one, rest are deleted and selection is random.

**Comment by vincent-pli** [comment]
I think the `Duplicate` should defined by customer, could we introduce list which contains all `owner`s  which could generate `Duplicate`  pod?
For example, a build in list should contain: `Deployment`, `ReplicaSet`, it should editable by end user.

**Comment by seanmalloy** [comment]
> I think the `Duplicate` should defined by customer, could we introduce list which contains all `owner`s which could generate `Duplicate` pod?
> For example, a build in list should contain: `Deployment`, `ReplicaSet`, it should editable by end user.

@vincent-pli this sounds like an interesting feature request. Can you open a new separate issue for this feature request? This will allow us to track it more easily. Thanks!

**Comment by vincent-pli** [comment]
@seanmalloy 
Sure, done, thanks

**Comment by damemi** [comment]
As another example use case for this: in OpenShift, [DeploymentConfigs](https://docs.openshift.com/container-platform/4.1/applications/deployments/what-deployments-are.html#deployments-and-deploymentconfigs_what-deployments-are) create a separate `deploy` pod to handle the rollout of new deployments. This deployer pod has the same owner as the workload pods, but will be considered a duplicate under the current strategy. If it's deleted however, it is not recreated and breaks deployments.

So to add to the suggestion in https://github.com/kubernetes-sigs/descheduler/issues/243, it would be helpful if a user could set other criteria/fields to compare against when considering duplicates.

**Comment by damemi** [comment]
Perhaps in addition to checking `ownerRefs`, we should also check the pod's `image`s. In theory, 2 pods that have the same ownerRef but different images should clearly not be considered duplicates, right? This would be a quick fix that reasonably tightens this strategy up while we work on expanding it

Any thoughts?

**Comment by vincent-pli** [comment]
@damemi 
I like the idea, easy way to resolve most of the cases

**Comment by damemi** [comment]
closed via #275
