### ISSUE TITLE
descheduler should work with the same policy for scheduler

### ISSUE THREAD

**Issue by u2takey** [kubernetes-sigs/descheduler#238]
Scheduler calculate scores for each pod during binding with sheduler policy. 
Maybe descheduler could use the same policy and calculate scores for each pod currently running, get the score for `best node` and `current node`, helping making the decision of `deschedule` by calculating diffrence of `best score` and `current score`.

**Comment by damemi** [comment]
This is an interesting idea, especially with the scheduler framework we should be able to get scores from the default scheduler plugins and consider those.

I think it would be nice if, perhaps part of a larger refactor, we used some kind of similar framework approach in the descheduler (as opposed to how it currently runs by just [running the strategy functions](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/descheduler.go#L82-L86) in an abritrary order)

**Comment by seanmalloy** [comment]
+1

A similar idea was mentioned in this comment ... https://github.com/kubernetes-sigs/descheduler/issues/184#issuecomment-557627594.

@damemi is SIG Scheduling going to move forward with moving [kube-scheduler code to staging](https://docs.google.com/document/d/1WO-ixERpqkCSEXEq30YtEH_z_G-BoLKeCbkRJcKq3xA/edit)? It seems like this would make it easier to implement this feature.

**Comment by damemi** [comment]
> @damemi is SIG Scheduling going to move forward with moving kube-scheduler code to staging?

I'll be pushing on this to make at least some progress for 1.19, yeah. There's also work being done to move the default plugins into their own repo https://github.com/kubernetes-sigs/scheduler-plugins

I think the descheduler might need its own design doc for how to implement a refactor like this. Wouldn't hurt at least

**Comment by damemi** [comment]
Currently blocking the upstream effort to move the scheduler plugin code to staging is this PR to initialize and external repo for helper functions: https://github.com/kubernetes/kubernetes/pull/92507
