### ISSUE TITLE
Introduce list for "Duplicate" decision

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/descheduler#243]
As mentioned in #230 , the `DuplicatePods` strategy is too broad, 2 pods in same `namespace` with same `owner` will be treated as `Douplicate`, that's rough. 
I know project [tekton-pipeline](https://github.com/tektoncd/pipeline), a `Taskrun` resource will generate unlimited `pod` and they all have deep relationship with each other.

So I suggest introduce a list for `DuplicatePods` strategy, let user decide which resource as `Owner` then it's children should be treated as `Douplicate`, we could has several default candidates (Deployment, ReplicaSet), and user could reset it.

**Comment by damemi** [comment]
This parameter may be added in https://github.com/kubernetes-sigs/descheduler/pull/275 (specifically https://github.com/kubernetes-sigs/descheduler/pull/275/commits/c11cb4f52bea5c71e3fa519b6a58aabdcdce13a4), please feel free to add any review or feedback you may have to that PR

**Comment by damemi** [comment]
closed via #275
