### ISSUE TITLE
Descheduling for a specific namespace

### ISSUE THREAD

**Issue by semin-park** [kubernetes-sigs/descheduler#251]
I'm trying to create a descheduler for a specific namespace.

I changed the `clusterrolebinding` to a `rolebinding` and gave it a namespace.

But now the descheduling pod's log indicates an error saying

> E0311 09:30:04.764541       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:descheduler-serviceaccount" cannot list resource "nodes" in API group "" at the cluster scope
E0311 09:30:04.839594       1 server.go:46] nodes is forbidden: User "system:serviceaccount:kube-system:descheduler-serviceaccount" cannot list resource "nodes" in API group "" at the cluster scope

What I would like to do, is to be able to create a descheduler for a specific namespace. Is this possible?

**Comment by seanmalloy** [comment]
/kind feature

@semin-park it is currently not possible to do this with descheduler. There is no way to restrict it to a namespace. PR #202 is open for adding a pod label selector option. Would the pod label selector feature meet your requirements? Or do you still want to be able to target a specific namespace?

**Comment by younseunghyun** [comment]
Hi
Operation strategy of Kubernetes can be divided into cluster per environment(prod, dev), namespace per environment.

As I know, many people use as namespace per environment.

At that point of strategy, developer want to use separate descheduler policies for each namespace.

So if we can restrict the namespace, it would be helpful to use.

Thx

**Comment by semin-park** [comment]
I agree with @younseunghyun 

It would be nice if we could target a specific namespace. Currently the only way to go seems to be to create multiple clusters, but that will likely increase the external fragmentation at the node level and also increase maintaining costs.

In our case we have a `dev` and `prod` namespace, and it'd be great if we could have deschedulers with potentially different policies for each namespace :)

**Comment by seanmalloy** [comment]
@younseunghyun and @semin-park thanks for your feedback. I think I just have some more questions.

1. is it acceptable to simply added a CLI option to limit descheduler to one or more namespaces?
2. Do you want to be able to specify more than one namespace?

**Comment by younseunghyun** [comment]
Usage case of the descheduler used to be as cron job.

So, I think we can specify which namespaces to apply descheduler.

**Comment by seanmalloy** [comment]
I think that adding a CLI option to restrict descheduler operation to one or more namespaces is a reasonable feature.

@damemi @ravisantoshgudimetla @aveshagarwal what are your thoughts? Any concerns?

**Comment by damemi** [comment]
Instead of just a namespace option, would we be able to add a [field selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/) parameter? In that case you could still accomplish this by limiting `spec.Namespace`.

I think that would pair nicely with the label selector in https://github.com/kubernetes-sigs/descheduler/pull/202, and add richer functionality

**Comment by seanmalloy** [comment]
@damemi I like the field selector idea.

@younseunghyun and @semin-park would this meet your requirements?

**Comment by damemi** [comment]
If we want to limit any potential unintended effects of a field selector, we could also just implement namespace selection as a field selector and restrict it in our code to only the namespace field (for now). That would allow us to open up the feature more when we get more confident in it

**Comment by younseunghyun** [comment]
@seanmalloy 

field selector option is great idea.

**Comment by seanmalloy** [comment]
I created a Google Doc proposal and shared it with the sig-scheduling mailing list. I've also added this to the sig-scheduling meeting agenda for July 2nd.

**Comment by seanmalloy** [comment]
@younseunghyun and @semin-park are there specific descheduler strategies you would like to restrict to running in a single name space?

Any details you provide on real world use cases would be helpful as I build out the proposal doc for review by SIG scheduling.

**Comment by seanmalloy** [comment]
/assign @ingvagabund 

The proposal has been reviewed by SIG scheduling and this feature can now be implemented. Descheduling for a specific namespace will be implemented using a strategy parameter, not a CLI option.

Here is an example of what the YAML might look like:
```
---
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "PodLifeTime":
     enabled: true
     params:
        maxPodLifeTimeSeconds: 86400
	 namespaces:
           includeNamespaces:
             - ns1
             - ns2
           excludeNamespaces:
             - ns3
             - ns4
```

The proposal document can be found here: https://bit.ly/k8s-descheduler-labels-namespaces

**Comment by younseunghyun** [comment]
@seanmalloy  Sorry for late check.

Thanks for applying the opinion :)
