### ISSUE TITLE
Descheduler goes into a loop with Remove duplicates strategy

### ISSUE THREAD

**Issue by kasturinarra** [kubernetes-sigs/descheduler#252]
I try to create a pod using an rc with replicas as 12 and i run descheduler.  I don't think there's anything in the duplicate pods strategy that considers the replica request vs number of available nodes and this causes a deschedling loop. descheduler tries to evict the pods every time the descheduler is run.

**Comment by seanmalloy** [comment]
This is a duplicate of #263.

/triage duplicate
/close
