### ISSUE TITLE
About the image registry of descheduler

### ISSUE THREAD

**Issue by gitbeyond** [kubernetes-sigs/descheduler#253]
Put the image on gcr.io, some areas are inaccessible, such as China. Try to build your own image, and you won't be able to access the relevant network, so please also consider putting the image into a warehouse that can be accessed all over the world. Thank you.

```bash
go: github.com/spf13/cobra@v0.0.5: Get https://proxy.golang.org/github.com/spf13/cobra/@v/v0.0.5.mod: dial tcp 216.58.200.49:443: i/o timeout
make: *** [Makefile:47: build] Error 1

```

**Comment by seanmalloy** [comment]
@gitbeyond the [CronJob](https://github.com/kubernetes-sigs/descheduler/blob/8a62cf16999b19d42c94f9a94da9b1db07427377/kubernetes/cronjob.yaml#L19) and [Job](https://github.com/kubernetes-sigs/descheduler/blob/8a62cf16999b19d42c94f9a94da9b1db07427377/kubernetes/job.yaml#L17) use `us.gcr.io`.

The container images are accessible from the below locations. These are documented in the [User Guide](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md).
```
docker pull asia.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0
docker pull eu.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0
docker pull us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0
```

**Comment by gitbeyond** [comment]
@seanmalloy Yes, I see, but in China, gcr.io is not accessible.

**Comment by seanmalloy** [comment]
@gitbeyond are you able to pull container images from k8s.gcr.io?

**Comment by seanmalloy** [comment]
@gitbeyond I'm not aware of a solution for your problem. Where do you pull other k8s project container images from?

**Comment by seanmalloy** [comment]
/close

As documented in #363 the container images for the descheduler are now available in from k8s.gcr.io. At this time I don't believe an alternative registry is available. Please feel free to re-open this issue if you would like to discuss further.

**Comment by devops-inthe-east** [comment]
Hey @seanmalloy , we've tried the above links to pull images, 

Since I am using the C9 in AWS, is there an alternative way to pull images from GCR. 

If not, How can I pull image from GCR on my C9.  A word of advice will be helpful. 

We have run in the below issue, 

'docker pull asia.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.27.0
Error response from daemon: manifest for asia.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.27.0 not found: manifest unknown: Failed to fetch "v0.27.0" from request "/v2/k8s-artifacts-prod/descheduler/descheduler/manifests/v0.27.0".'

**Comment by damemi** [comment]
@devops-inthe-east `k8s.gcr.io` has been deprecated and images from 1.27 on are no longer published there. Please use `registry.k8s.io` (see https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/).

I tried to find a way to pull from a specific region with the new registry, but I couldn't find one. It seems like the new registry is meant to distribute across regions automatically from what I can tell.
