### ISSUE TITLE
kubectl and descheduler CPU utilisation values are vastly different

### ISSUE THREAD

**Issue by duronrulez** [kubernetes-sigs/descheduler#270]
We've notice that the values for CPU utilisation between kubectl top nodes and the descheduler are vastly different. 

```
I0423 10:01:19.375155    7053 lownodeutilization.go:156] Node "XXX" is appropriately utilized with usage: api.ResourceThresholds{"cpu":44.05815423514539, "memory":38.10868466231932, "pods":18.96551724137931}
```

while kubectl top nodes reports
```
NAME                                        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
XXX    7946m        100%   10365Mi         81%
```

The values are vastly different and the ones reported by kubectl seem to be the ones that match the node usage. Is there any reason why the 2 values will missmatch so much?

**Comment by seanmalloy** [comment]
/close

@duronrulez currently the [LowNodeUtilization descheduler strategy](https://github.com/kubernetes-sigs/descheduler#lownodeutilization) uses [container requests](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) not the actual CPU and memory utilization. Yes, the word utilization is in the name of the strategy, and this is confusing. There is a one liner in the README that describes this, `Currently, pods request resource requirements are considered for computing node resource utilization.`.

See #7 for a discussion around utilization vs allocation terminology confusion. See #225 for a discussion on adding a new strategy that is based on actual container utilization metrics.
