### ISSUE TITLE
Desheduler needs to check the number of replicas before evicting the pod.

### ISSUE THREAD

**Issue by pbannykh** [kubernetes-sigs/descheduler#271]
Vendor applications often run in a single replica. Descheduler should not evict pods that work in a single replica.

**Comment by seanmalloy** [comment]
/kind feature

@pbannykh thanks for opening this issue!

Based on my understanding of the descheduler I believe you are correct the descheduler does not take the number of replicas into consideration. For your reference the [IsEvictable](https://github.com/kubernetes-sigs/descheduler/blob/78eef6c343cc77a5c11c9ada3bf73be89861624a/pkg/descheduler/pod/pods.go#L31-L38) function shows the various conditions that determines if a pod can be evicted or not.

Here are three possible solutions ...
1. Create a [PDB](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) to prevent the pod from being evicted
2. Mark the pod as [critical pod](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/)
3. Add a new feature to descheduler to take replicas into consideration

Would options 1 or 2 work for you? Or do you feel that you really need a configuration option for descheduler to take replicas into consideration?

**Comment by pbannykh** [comment]
@seanmalloy thanks for the proposed solutions!

We cannot allow users to mark their pods as critical, because users will mark almost all of their pods as critical.

Creating a PDB for a single replica makes node drain difficult.

Add a new feature to descheduler to take replicas into consideration is not a bad decision for me and I am ready to discuss this. Enabling this option may leave some nodes unbalanced. This will create unnecessary work for descheduler the next time it starts.

**Comment by seanmalloy** [comment]
@pbannykh would you want the number of replicas to be configurable? Or is a simple hard coded exception for ignoring single replica pods good enough?

One more idea ...

Would adding a label selector configuration option to descheduler meet your requirement? See pull request #202. I believe if the label section feature was implemented it would allow you to tell descheduler to ignore pods with certain labels.

Right now I'm undecided if this feature should be added or not. I'd like some feedback from @damemi @aveshagarwal @ravisantoshgudimetla or @ingvagabund to get some additional perspectives.

**Comment by damemi** [comment]
There are valid cases for descheduling a single replica, for example if affinity conditions change or even rebalancing resource usage, so I don't think this would work as a default behavior. It could be configurable though if you want to enable it.

**Comment by seanmalloy** [comment]
@pbannykh there are some additional features for filtering pods that are being working on for a future release of the descheduler.

Filtering by namespace has been merged into the master branch and will be officially available as part of the upcoming v0.19.0 release. See PR #337 

Filtering pods by pod label was discussed in a recent SIG scheduling meeting, and the proposal was accepted. See issue #195.

Filtering pods by priority class was also discussed in a recent SIG scheduling meeting, and this will also be implemented in the  descheduler at some point in the future. See issue #329 and work in progress PR #364.

Does one of these features satisfy your requirements?
