### ISSUE TITLE
Evict pods violating security practices

### ISSUE THREAD

**Issue by AdheipSingh** [kubernetes-sigs/descheduler#272]
descheduler should be able remove pods having securitycontext params such as runasroot, priviledge escaltion set to true, remove pods with default service account It would good feature as addon.

**Comment by seanmalloy** [comment]
/kind feature

@AdheipSingh thanks for opening this issue!

The descheduler only evicts pods. It does not permanently remove them. After a pod is evicted by the descheduler it is immediately re-scheduled by the [kube-scheduler](https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/).

Is this what you would be expecting if this feature request was implemented? Can you provide more details around the requirement to evict pods that are violating certain security best practices?

**Comment by AdheipSingh** [comment]
@seanmalloy thanks for the reply !!

Here 's a code snippet which i was trying to play around with. Any practices around security context enabled, using service accounts, high quota allocation...........can be added. Can take input from the user as described below, and evict in case condition matches.

Do tell your thoughts. :) 
```
type StrategyParameters struct {
	NodeResourceUtilizationThresholds *NodeResourceUtilizationThresholds `json:"nodeResourceUtilizationThresholds,omitempty"`
	NodeAffinityType                  []string                           `json:"nodeAffinityType,omitempty"`
	PodsHavingTooManyRestarts         PodsHavingTooManyRestarts          `json:"podsHavingTooManyRestarts,omitempty"`
	SecurityPractices                 SecurityPractices                  `json:"securityPractices,omitempty"`
}

type SecurityPractices struct {
	ServiceAccount string `json:"string"`
	RunAsUser      int64  `json:"runAsUser"`
}
```
```

func RemovePodsViolatingSecurity(client clientset.Interface, strategy api.DeschedulerStrategy, nodes []*v1.Node, evictLocalStoragePods bool, podEvictor *evictions.PodEvictor) {

	for _, node := range nodes {
		klog.V(1).Infof("Processing node: %#v\n", node.Name)

		pods, err := podutil.ListEvictablePodsOnNode(client, node, evictLocalStoragePods)
		if err != nil {
			klog.Errorf("failed to get pods from %v: %v", node.Name, err)
		}
		//	klog.V(1).Infof("sa pod: %v", pods)
		for _, pod := range pods {
			if pod.Spec.ServiceAccountName == "default" {
				klog.V(1).Infof("sa pod: %v", pod.Spec.ServiceAccountName)
				if !nodeutil.PodFitsCurrentNode(pod, node) && nodeutil.PodFitsAnyNode(pod, nodes) {
					klog.V(1).Infof("Evicting pod: %v", pod.Name)
					if _, err := podEvictor.EvictPod(pod, node); err != nil {
						break
					}
				}
			}
		}

	}
	klog.V(1).Infof("Evicted %v pods", podEvictor.TotalEvicted())
}
```

**Comment by seanmalloy** [comment]
@AdheipSingh thanks for the clear description on how this new feature might work.

I'm still not clear why someone would want to evict theses types of pods if they will just get scheduled again? What is the real world use case?

**Comment by pmundt** [comment]
I think this would also be a good candidate for leveraging #301, as this would then inhibit the automatic rescheduling behaviour.

**Comment by AdheipSingh** [comment]
@ingvagabund is this something to be taken into consideration ?

**Comment by ingvagabund** [comment]
> @ingvagabund is this something to be taken into consideration ?

I totally missed this comment. Apologies. In this case the suggested approach is to implement a custom strategy. Once the descheduling framework is completed, we will be revisiting all the open issues and PRs to suggest how they can be incorporated into the new framework or whether a new descheduling plugin will be more preferable.
