### ISSUE TITLE
Migrate travis tests to prow

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#323]
Recently we've been seeing more issues with getting travis to actually run our e2e tests. In order to ensure they are run before PRs merge, we should add these to prow. I've started a PR to do that here: https://github.com/kubernetes/test-infra/pull/17943

One thing I don't know is how to keep something similar to our current [version test matrix](https://github.com/kubernetes-sigs/descheduler/blob/08c22e8921ffa6fe55b2f4fcc2be56b4a47187ac/.travis.yml#L7-L11) in prow to run the tests against multiple versions. This ensures we don't break anything in versions that should still be supported

**Comment by seanmalloy** [comment]
/close

The descheduler e2e tests are now running through prow for the master, release-1.18, and release-1.17 branches. The Travis CI configuration was removed from the master branch in PR https://github.com/kubernetes-sigs/descheduler/pull/342.
