### ISSUE TITLE
Throttling Error While running Descheduler

### ISSUE THREAD

**Issue by ishan-rep** [kubernetes-sigs/descheduler#324]
Sorry if this is not the right place to post this, please do let me know any other way of communicating with Descheduler community. Anyways, here I go:

We are running Descheduler with PodLifeTime policy. I think Descheduler is not able to run this policy on various pods  (Figured from the log below):

```
I0616 11:50:59.223768       1 request.go:557] Throttling request took 267.045984ms, request: GET:https://<IP>/api/v1/pods?fieldSelector=spec.nodeName%3D<NodeIP>%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded
I0616 11:50:58.223772       1 request.go:557] Throttling request took 93.628651ms, request: POST:https://<IP>/api/v1/namespaces/default/events
```

Any suggestions as to how to resolve this?

**Comment by damemi** [comment]
@ishan-rep thanks for reporting this, is this actually preventing the descheduler from evicting pods that you expect it to? (reminder that there are [default restrictions](https://github.com/kubernetes-sigs/descheduler#pod-evictions) on what pods are eligible to evict. this is the most common reason that a strategy doesn't run on various pods)

Normally I think these throttling notifications are recoverable, though they are annoying noise. I don't believe they indicate that any requests were actually cancelled.

**Comment by ishan-rep** [comment]
Hey @damemi , from [this](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L580) part of k8s code , whenever the latency crosses a certain threshold, it is throwing an error.

I've gone through the type of Pods that are not evicted and our pods doesn't fall into that category.

Are we sure that this throttling issue isn't preventing the pods from getting evicted?

**Comment by damemi** [comment]
> Are we sure that this throttling issue isn't preventing the pods from getting evicted?

@ishan-rep it's tough to tell, could you please provide more of the descheduler logs, and if possible the yaml for the pods you expect to be evicted?

**Comment by ingvagabund** [comment]
Those are standard info logs reported by any code using client-go library. No need to worry about it.
As @damemi noted, the descheduler logs will shed more light here.

**Comment by seanmalloy** [comment]
@ishan-rep are you able to provide any additional details? If not I'd like to close out this issue. Thanks!
