### ISSUE TITLE
how to avoid conflict with scheduler

### ISSUE THREAD

**Issue by szy441687879** [kubernetes-sigs/descheduler#326]
descheduler is a crontab which get all info and run strategies.
i get a node which is over targetThreshold in LowNodeUtilization,so i try to evict one pod names A.
but meanwhile pod B on the same node is evicted by other Reason,it means i dont need to evict pod A if i known pod B will be evicted.
in this case,is scheduler will evict A and B both?how can i avoid this or is allowed in design

**Comment by lixiang233** [comment]
Descheduler will run all enabled strategies in a random order, if some pods on an overutilized node had already been evicted by some other strategies before running `LowNodeUtilization` and it makes the node's utilization drops below `targetThreshold`, no pod will be evicted by `LowNodeUtilization` strategy(node's utilization will be calculated everytime `LowNodeUtilization` starts).

**Comment by szy441687879** [comment]
i means if some pods on an overutilized node is evicted by user or other contollers ，and happend when the node is calculating utilization

**Comment by lixiang233** [comment]
Node's utilization is calculate based on a node/pods cache called `NodePodsMap`, and if a pod is evicted by user right after this cache generated, it won't be updated, so I think in the case you mentioned above, descheduler may evict pod A even if pod B has been evicted.

**Comment by szy441687879** [comment]
is there any way to avoid this problem？or i need to consider this kind of confliction in descheduler strategies designing

**Comment by seanmalloy** [comment]
@szy441687879 so you would like the descheduler to run in real time instead of periodically as a CronJob?

Unfortunately this is not currently a feature of descheduler. The descheduler is currently designed to run as a batch job(CronJob) periodically. There is some discussion in #261 about making the descheduler a kube-scheduler plugin using the scheduler framework, but so far there has not been any progress moving this forward.

/kind feature

**Comment by lixiang233** [comment]
@szy441687879  It took me a few days to think about this, and finally I came to a conclusion: this is not a problem. As mentioned above, node's utilization is calculated based on a node/pods cache, so once the cache is generated, pods which should be evicted are determined and no matter what happens next, they'll be evicted. Actually, pods are evicted when cache generates, even if the real eviction happens in the future, so you can think of these things(generate cache, calculate utilization, evict pods) as happening at the same time. And the case you mentioned which happens in this order `generate cache`->`evict pod by user`->`evict pod by descheduler` has no difference from `generate cache`->`evict pod by descheduler`->`evict pod by user`. As descheduler doesn't share a lock with scheduler or other components, we can't prevent your case from happening. We don't know what will happen in the future, so we can't let pods which will be evicted in the future to effect our decision in the past. And as descheduler uses cache, it always runs in the past OvO.
By the way, if you want to evict pods by yourself or other components for node's utilization, you shouldn't run descheduler at the same time.

**Comment by szy441687879** [comment]
thank 

> @szy441687879 It took me a few days to think about this, and finally I came to a conclusion: this is not a problem. As mentioned above, node's utilization is calculated based on a node/pods cache, so once the cache is generated, pods which should be evicted are determined and no matter what happens next, they'll be evicted. Actually, pods are evicted when cache generates, even if the real eviction happens in the future, so you can think of these things(generate cache, calculate utilization, evict pods) as happening at the same time. And the case you mentioned which happens in this order `generate cache`->`evict pod by user`->`evict pod by descheduler` has no difference from `generate cache`->`evict pod by descheduler`->`evict pod by user`. As descheduler doesn't share a lock with scheduler or other components, we can't prevent your case from happening. We don't know what will happen in the future, so we can't let pods which will be evicted in the future to effect our decision in the past. And as descheduler uses cache, it always runs in the past OvO.
> By the way, if you want to evict pods by yourself or other components for node's utilization, you shouldn't run descheduler at the same time.


--
 

 。

> @szy441687879 It took me a few days to think about this, and finally I came to a conclusion: this is not a problem. As mentioned above, node's utilization is calculated based on a node/pods cache, so once the cache is generated, pods which should be evicted are determined and no matter what happens next, they'll be evicted. Actually, pods are evicted when cache generates, even if the real eviction happens in the future, so you can think of these things(generate cache, calculate utilization, evict pods) as happening at the same time. And the case you mentioned which happens in this order `generate cache`->`evict pod by user`->`evict pod by descheduler` has no difference from `generate cache`->`evict pod by descheduler`->`evict pod by user`. As descheduler doesn't share a lock with scheduler or other components, we can't prevent your case from happening. We don't know what will happen in the future, so we can't let pods which will be evicted in the future to effect our decision in the past. And as descheduler uses cache, it always runs in the past OvO.
> By the way, if you want to evict pods by yourself or other components for node's utilization, you shouldn't run descheduler at the same time.

thank you for answering.the design of descheduler doesn't share a lock so it can't prevent my case.i consider use scheduler plugin together to slove my problem which descheduler only give a evict suggestion

**Comment by szy441687879** [comment]
> @szy441687879 It took me a few days to think about this, and finally I came to a conclusion: this is not a problem. As mentioned above, node's utilization is calculated based on a node/pods cache, so once the cache is generated, pods which should be evicted are determined and no matter what happens next, they'll be evicted. Actually, pods are evicted when cache generates, even if the real eviction happens in the future, so you can think of these things(generate cache, calculate utilization, evict pods) as happening at the same time. And the case you mentioned which happens in this order `generate cache`->`evict pod by user`->`evict pod by descheduler` has no difference from `generate cache`->`evict pod by descheduler`->`evict pod by user`. As descheduler doesn't share a lock with scheduler or other components, we can't prevent your case from happening. We don't know what will happen in the future, so we can't let pods which will be evicted in the future to effect our decision in the past. And as descheduler uses cache, it always runs in the past OvO.
> By the way, if you want to evict pods by yourself or other components for node's utilization, you shouldn't run descheduler at the same time.

thank you for answering.the design of descheduler doesn't share a lock so it can't prevent my case.i consider use scheduler plugin together to slove my problem which descheduler only give a evict suggestion
