### ISSUE TITLE
Allow Ignoring Pods For Eviction

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#329]
**Is your feature request related to a problem? Please describe.**

I would like to be able to tell the descheduler to ignore certain pods for eviction. Currently the descheduler provides several options for ignoring pods, but none of the current options fit my use case.

**Describe the solution you'd like**

**Option 1:**
I would like to be able to set the annotation `descheduler.alpha.kubernetes.io/evict: "false"` on a pod and have descheduler always ignore this pod. Descheduler should never evict this pod. Users would need to add the annotation `descheduler.alpha.kubernetes.io/evict: "true"` to inform the descheduler to always evict a pod. This would be a breaking change.

**Option 2:**
I would like descheduler to have an option to specify a PriorityClass threshold that allows excluding pods for eviction. This is similar to ignoring system and node critical pods, but the end user can specify a PriorityClass threshold instead of only allowing the hard coded system and node critical  PriorityClasses.

**Describe alternatives you've considered**

* Marking the pods as a critical pod
* Assigning local storage to the pod
* Setting a very restrictive PDB

Marking the pod as a [critical pod ](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/)is the closest option that fits my use case, but the pods I want descheduler to ignore are not considered system or node critical. It is just a pod running a business application therefore I do not want to mark it as system or node critical.

**What version of descheduler are you using?**

descheduler version: v0.18.0

**Additional context**

The k8s cluster autoscaler currently supports a similar annotation for pods `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"`. See the [CA FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) for details.

**Comment by seanmalloy** [comment]
@damemi @ingvagabund @aveshagarwal @ravisantoshgudimetla what do you think about this feature? Does it seem reasonable to you?

**Comment by seanmalloy** [comment]
Looks like this topic has been proposed and discussed before. See #140 and #117.

**Comment by ingvagabund** [comment]
The closest solution for this was to assign a local storage to a pod. I don't know if there's an admission plugin which can be configured to forbid pods with a local storage set. Though, recommending descheduler consumers to assign a local storage in order to protect a pod from eviction is not semantically right since the underlying implementation can change. Also, when the descheduler is allowed to evict even pods with a local storage, the suggested solution will no longer work (e.g. in clusters where only administrator can configure the descheduler).

On the other hand providing user specified annotation to tell descheduler to ignore a pod can have consequences as well. E.g. too many application pods can have the annotation set and make the descheduler unusable.

Yet still, the annotation (or other mechanisms) will have no effect if the scheduler decides to preempt the application pod due to insufficient resources for example. Instead of providing a new annotation I'd prefer to make the descheduling decision based on existing priority classes.

**Comment by lixiang233** [comment]
Only in `LowNodeUtilization` and `RemovePodsViolatingInterPodAntiAffinity`, priority will effect whether a pod will be evicted(except SystemCritical pods), if we don't want descheduler to evict a specific pod, I prefer to make this pod `SystemCritical`. But as mentioned above, we may want descheduler to ignore a non-critical pod. I'm wondering if we can intrdouce a new configuration which defines a priority value threshold. Pods whoes priority is above that threshold will be ignored and by default the threshold is set to [SystemCriticalPriority](https://github.com/kubernetes-sigs/descheduler/blob/c713537d56eb6b12c2f66c1f3ecb9be10db02980/pkg/utils/priority.go#L9). If users want to ignore one pod, just change its priority class and run descheduler with a suitable priority threadhold.

**Comment by seanmalloy** [comment]
> I'm wondering if we can intrdouce a new configuration which defines a priority value threshold. Pods whos priority is above that threshold will be ignored and by default the threshold is set to [SystemCriticalPriority](https://github.com/kubernetes-sigs/descheduler/blob/c713537d56eb6b12c2f66c1f3ecb9be10db02980/pkg/utils/priority.go#L9). If users want to ignore one pod, just change its priority class and run descheduler with a suitable priority threshold.

@lixiang233 and @ingvagabund I like this idea. Do you think we would just add a new CLI option to descheduler? Maybe something like `--pod-priority-threshold`?

**Comment by ingvagabund** [comment]
> Do you think we would just add a new CLI option to descheduler?

That's the place where we put the strategy independent configuration now. Though, I would like to avoid extending the list of flags since they are not versioned. We might also iterate on the policy type [1] and move some flags into it.

[1] https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/api/types.go#L26

**Comment by damemi** [comment]
Like you mentioned, marking the pod as Critical is the most obvious closest solution here but

> the pods I want descheduler to ignore are not considered system or node critical. It is just a pod running a business application therefore I do not want to mark it as system or node critical.

So I understand why you don't want to use the system critical priorities here. The descheduler currently considers a pod to be critical if its priority is >= [`SystemCriticalPriority`](https://github.com/kubernetes-sigs/descheduler/blob/267b0837dc3085c387d1ee6bf76050bf0db91c9a/pkg/utils/pod.go#L123). However, this level of priority is [reserved for the Kubernetes system](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/apis/scheduling/types.go#L29-L30), so I guess you can't just create your own priority class that high for "business critical".

So as mentioned in https://github.com/kubernetes-sigs/descheduler/issues/329#issuecomment-648103504, we could do something where we have a user-configurable threshold, or we just lower the current hardcoded threshold to `HighestUserDefinablePriority`. A configurable threshold could run the risk of a user accidentally evicting system critical pods too.

If we go the configurable route, I agree with @ingvagabund that it should be more policy-oriented than CLI.

**Comment by seanmalloy** [comment]
@ingvagabund and @damemi I updated the issue description https://github.com/kubernetes-sigs/descheduler/issues/329#issue-643540317 to lay out the annotation and PriorityClass options. Do we want to just move forward with implementing this using PriorityClasses? Or do you want me to submit a proposal document to SIG scheduling for review?

@lixiang233 would you be interested in implementing this feature once we have consensus on the high level implementation details?

**Comment by lixiang233** [comment]
> @ingvagabund and @damemi I updated the issue description [#329 (comment)](https://github.com/kubernetes-sigs/descheduler/issues/329#issue-643540317) to lay out the annotation and PriorityClass options. Do we want to just move forward with implementing this using PriorityClasses? Or do you want me to submit a proposal document to SIG scheduling for review?
> 
> @lixiang233 would you be interested in implementing this feature once we have consensus on the high level implementation details?

of cource. Please let me know if you have consensus on it.

**Comment by ingvagabund** [comment]
> Do we want to just move forward with implementing this using PriorityClasses? Or do you want me to submit a proposal document to SIG scheduling for review?

Might be worth mentioning on the SIG next week. Though, I don't see it as something waiting to be approved by the group. Option 2 still aligns with how the priorities and preemption works in the scheduler. Option 1 can turn quite impractical.

**Comment by damemi** [comment]
I also like the customizable priority threshold. Maybe we could even let users set a priorityclass by name (and then the descheduler would be smart enough to interpret the threshold from that). Might be a little more convenient, but we could offer both

**Comment by seanmalloy** [comment]
@damemi @ingvagabund and @lixiang233 I added this to the July 16th SIG Scheduling agenda. I did not create a formal proposal document.

**Comment by Huang-Wei** [comment]
Option 2 + policy-level field makes sense to me.

> Or do you want me to submit a proposal document to SIG scheduling for review?

Nope, it's unnecessary :)

**Comment by seanmalloy** [comment]
@lixiang233 this was discussed at the July 16th SIG Scheduling meeting. The consensus was that option 2(using priority classes) is the best approach. I believe we want to add this as strategy parameter, not a CLI option. Feel free to assign this issue to yourself and start working on it. Thanks!

@damemi and @ingvagabund feel free to add any details you think I may have missed.

**Comment by lixiang233** [comment]
/assign
One more question: should this parameter be different for each strategies?

**Comment by ingvagabund** [comment]
> One more question: should this parameter be different for each strategies?

Some strategies can be focused only on lower priority classes. So yes.

Also, if this will go into v1alpha1 policy, https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/api/types.go#L48 is the only place to put it to.

**Comment by ingvagabund** [comment]
@lixiang233 do you still plan to work on the issue?

**Comment by lixiang233** [comment]
> @lixiang233 do you still plan to work on the issue?

yes, as #338 got merged, I'll start working on this soon.
