### ISSUE TITLE
Error adding helm repo

### ISSUE THREAD

**Issue by swestcott** [kubernetes-sigs/descheduler#355]
Hello,

I'm following the [instructions](https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/README.md) to use the Helm Chart, but have encountered an error on the first step.

```
$ helm repo add descheduler https://kubernetes-sigs.github.io/descheduler/
Error: looks like "https://kubernetes-sigs.github.io/descheduler/" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-sigs.github.io/descheduler/index.yaml : 404 Not Found
```

**Comment by seanmalloy** [comment]
/close

Thanks for opening this issue. The helm chart has been created, but we have run into problems with the deployment automation. We are tracking this is #248.
