### ISSUE TITLE
[Helm] Wrong version form chart

### ISSUE THREAD

**Issue by vmdude** [kubernetes-sigs/descheduler#365]
There is a wrong version (0.18.0) in the `chart.yml`:

https://github.com/kubernetes-sigs/descheduler/blob/d0fbebb77c79831137b1a14b5ceadb489c678859/charts/descheduler/Chart.yaml#L3

When we add the repo through helm, it shows only version 0.18.1:

```
$ helm repo add descheduler https://kubernetes-sigs.github.io/descheduler/
$ helm template descheduler/descheduler-helm-chart --version 0.18.0
Error: failed to download "descheduler/descheduler-helm-chart" (hint: running `helm repo update` may help)
$ helm search repo descheduler
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
descheduler/descheduler-helm-chart	0.18.1       	0.18.0     	Descheduler for Kubernetes is used to rebalance...
```

**Comment by seanmalloy** [comment]
@vmdude thanks for opening this issue.

We attempted to release descheduler helm chart version 0.18.0, but our release automation failed. We fixed the glitch and were able to to release descheduler helm chart version 0.18.1 which was the first helm chart release. Version 0.18.1 can be found on the `release-1.18` branch:
https://github.com/kubernetes-sigs/descheduler/blob/76ab9e765a7db36011b6be4e4e1c93018c0fb65e/charts/descheduler/Chart.yaml#L3

The master branch will be updated roughly sometime in August for the 0.19.0 release.

Based on this explanation are you good with closing this issue? Do you think there is some end user documentation that could be updated to make this more clear?

CC: @stevehipwell

**Comment by stevehipwell** [comment]
I'm struggling to see where there is a bug? If you add the repo to helm, update it and run `helm search repo descheduler` you get the following result.

```
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
descheduler/descheduler-helm-chart      0.18.1          0.18.0          Descheduler for Kubernetes is used to rebalance...
```

The chart and app version's don't match but that's documented as expected behaviour, not having a _0.18.0_ chart isn't ideal but it isn't an actual bug (and could happen again).

**Comment by vmdude** [comment]
It's not a bug per-se, but your `chart.yml` file refered to a version that didn't exist in the helm repo (cause explained by @seanmalloy )
It's OK to close this issue.
