### ISSUE TITLE
Update To Go 1.15

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#367]
The k8s 1.19 release will be built using Go 1.15. Go 1.15 is not GA yet. The descheduler should also be updated to use Go 1.15 prior to releasing v0.19.0.

See issues tracking k8s 1.19 release cycle update to Go 1.15:
* https://github.com/kubernetes/release/issues/1421
* https://github.com/kubernetes/kubernetes/issues/93484

I believe we can hold off on this until after Go 1.15 goes GA and the k/k repo is bumped to use the Go 1.15.0 GA release.

**Comment by warmchang** [comment]
:smile: It's time to go: https://github.com/golang/go/releases/tag/go1.15

**Comment by seanmalloy** [comment]
Created PR #371

**Comment by seanmalloy** [comment]
> Created PR #371 

/close
