### ISSUE TITLE
Add ability to optimise for Zonal Distribution

### ISSUE THREAD

**Issue by Stono** [kubernetes-sigs/descheduler#368]
**Describe the solution you'd like**
We like to ensure that there is a loosely even distribution of pods across all zones within our cluster.  Whilst our scheduler is configured to do best endeavours spread, we need something to continually monitor the situation and nudge pods accordingly when the imbalance is less than suitable.

**Describe alternatives you've considered**
At the moment we alert on the situation, and then use some automated handling of that alert to "deschedule" a pod, see: https://twitter.com/karlstoney/status/1292158531005829128.

It feels like the perfect fit for this project however.

Also we are aware in 1.18 brings beta PodTopologicalConstraints, but that's a way away for us using it in Production.

**Comment by seanmalloy** [comment]
@Stono thanks for opening this issue. This looks like a duplicate of #146. I suggest we close out this issue and move any further discussions to #146.

The proposed API for implementing this in the descheduler is in [this comment](https://github.com/kubernetes-sigs/descheduler/issues/146#issuecomment-639277192). Unfortunately, the proposed descheduler implementation will rely on the `TopologySpreadConstraint` k8s feature. So this would require running a version of k8s with the `TopologySpreadConstraint` feature enabled.

Also, note that the `TopologySpreadConstraint` kube-scheduler feature will be promoted to GA in k8s 1.19.

/label triage/duplicate

@damemi @ingvagabund @lixiang233 please feel free to add any additional thoughts you might have.

**Comment by Stono** [comment]
That sounds reasonable to me :) I was hunting something pre-topological constraints but admit that's a tall ask.
Thanks for the response!
