### ISSUE TITLE
Node not indentified as underutilized

### ISSUE THREAD

**Issue by auduny** [kubernetes-sigs/descheduler#381]
**What version of descheduler are you using?**

descheduler version: 0.18.0

**Does this issue reproduce with the latest release?**

Yes

**Which descheduler CLI options are you using?**

            - "--policy-config-file"
            - "/policy-dir/policy.yaml"
            - "--v"
            - "3"
            - "--node-selector"
            - "node-role.kubernetes.io/production=true"

**Please provide a copy of your descheduler policy config file**
```json
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 30
           "memory": 30
           "pods": 30
         targetThresholds:
           "cpu" : 50
           "memory": 50
           "pods": 70
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

Run the job once

**What did you expect to see?**

Atleast one node (k8s-node-vm-01.int.vgnett.no) is registred as underutilized.

**What did you see instead?**
```
I0820 10:43:23.889948       1 lownodeutilization.go:157] Node "k8s-node-vm-01.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":6.962025316455696, "memory":7.106983524831375, "pods":6.363636363636363}
I0820 10:43:23.890119       1 lownodeutilization.go:157] Node "oa68-k8s-node-01.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":35.678391959798994, "memory":15.592868177245256, "pods":48.18181818181818}
I0820 10:43:23.890284       1 lownodeutilization.go:157] Node "oa68-k8s-node-02.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":22.609603340292274, "memory":20.008464895317026, "pods":66.36363636363636}
I0820 10:43:23.890397       1 lownodeutilization.go:157] Node "oa68-k8s-node-03.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":17.432150313152402, "memory":18.385332871544318, "pods":53.63636363636363}
I0820 10:43:23.890526       1 lownodeutilization.go:157] Node "u89-k8s-node-02.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":19.62421711899791, "memory":20.405043432173535, "pods":67.27272727272727}
I0820 10:43:23.890638       1 lownodeutilization.go:157] Node "u89-k8s-node-03.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":13.883089770354905, "memory":16.56802734599502, "pods":60}
I0820 10:43:23.890658       1 lownodeutilization.go:66] Criteria for a node under utilization: CPU: 30, Mem: 30, Pods: 30
I0820 10:43:23.890680       1 lownodeutilization.go:70] No node is underutilized, nothing to do here, you might tune your thresholds further
```

**Comment by seanmalloy** [comment]
@auduny i'm not super familiar with using the `LowNodeUtilization` strategy, but why do you believe the node `k8s-node-vm-01.int.vgnett.no` is underutilized? Can you provide the output of `kubectl describe node k8s-node-vm-01.int.vgnett.no`?

**Comment by auduny** [comment]
Because the logs says ```Node "k8s-node-vm-01.int.vgnett.no" is appropriately utilized with usage: api.ResourceThresholds{"cpu":6.962025316455696, "memory":7.106983524831375, "pods":6.363636363636363}
```
And i set the limits to be 30 for cpu, memory and pods. All of them are under 30 and should then be marked as underutilized? Or am I missing something here? The other nodes has over 30 pods so they are correct. 

The docs says. "If a node's usage is below threshold for all (cpu, memory, and number of pods), the node is considered underutilized. " 

and

"Any node between the thresholds, thresholds and targetThresholds is considered appropriately utilized and is not considered for eviction."

**Comment by lixiang233** [comment]
@auduny  Is your node `Unschedulable`? I think that's the only reason descheduler regard an `underutilized` node `appropriately utilized`.

**Comment by seanmalloy** [comment]
/kind cleaup
/remove-kind bug

I agree we should log this, so it is less confusing. @auduny and @lixiang233 thanks for helping to track this down!

**Comment by damemi** [comment]
This is fixed in master with the recent refactor to this strategy in https://github.com/kubernetes-sigs/descheduler/pull/384 https://github.com/kubernetes-sigs/descheduler/blob/c9cfeb35c2724b3a49e0f95adea76ce125f15576/pkg/descheduler/strategies/lownodeutilization.go#L105-L107

(specifically, commit https://github.com/kubernetes-sigs/descheduler/pull/384/commits/9b4f781c5c902017b1b521129b3b356623d43146)

If there's any desire to backport this to 1.19 or 1.18, feel free. Otherwise we can probably consider this fixed
