### ISSUE TITLE
Add namespace filtering to RemoveDuplicates strategy

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#405]
Currently namespace filtering isn't available in RemoveDuplicates. I think this was intentionally chosen for reasons similar to LowNodeUtilization (where the strategy needs to consider the entire node to be effective), but looking more into RemoveDuplicates I think it does not depend on considering the entire node.

This is mainly because `namespace` is one of the fields we use to consider a pod's uniqueness:
https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/duplicates.go#L106

So we have never considered pods in different namespaces to be duplicates, so there is no risk of making the strategy less effective. It seems reasonable then to want to run this strategy in only select namespaces (or exclude others).

Does it make sense then that we could add namespace filters to this strategy?

**Comment by ingvagabund** [comment]
> This is mainly because namespace is one of the fields we use to consider a pod's uniqueness

Good point!!! Yeah, it's reasonable to allows namespace filtering in the strategy.
