### ISSUE TITLE
Forbid descheduling when descheduler.alpha.kubernetes.io/evict=false

### ISSUE THREAD

**Issue by codablock** [kubernetes-sigs/descheduler#422]
I'd like to propose a change to the way `descheduler.alpha.kubernetes.io/evict` is handled. Currently it is only checked for presence of this annotation, in which case eviction is always allowed, no matter if anything else prohibited it.

I propose to change the behavior so that the value of the annotation is checked as well. In case it is `false`, it should prohibit descheduling in any case. In case it is `true`, it should allow descheduling in any case.

In my case, this would be useful to circumvent cases like https://github.com/kubernetes-sigs/descheduler/issues/335, which I'm running into right now. There are likely many other cases where descheduling is also not a good idea, so allowing to disable descheduling on a pod/deployment/sts basis without touching pod priorities would be very helpful.

**Comment by damemi** [comment]
Adding an annotation to forbid eviction was discussed in https://github.com/kubernetes-sigs/descheduler/issues/329, and the conclusion was that [filtering pods by custom priority thresholds](https://github.com/kubernetes-sigs/descheduler#priority-filtering) was a better approach. Does this apply to your use case?

**Comment by seanmalloy** [comment]
The recommendation is to use a PriorityClass to achieve this. Also, starting with k8s 1.19 a non-prempting PriorityClass can be created.

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

Please feel free to re-open if you'd like to discuss further.

/close
