### ISSUE TITLE
Allow to control at what time/day-of-week eviction is allowed for a pod

### ISSUE THREAD

**Issue by codablock** [kubernetes-sigs/descheduler#423]
**Is your feature request related to a problem? Please describe.**
When suggesting the use of the descheduler for my client, people immediately got scared about the potential of always evictable pods, even at business hours when load is high and interruptions are critical. They would prefer if eviction would only happen outside of business hours.

I understand that properly scaled Deployments or StatefulSets should protect the client from interruptions due to pod eviction, but this is not always possible, especially when legacy software is moved into k8s which only allows 1 instance of it at a time.

**Describe the solution you'd like**
I'd like to be able to control at which time of the day eviction is allowed. This should be configurable per pod, so an annotation is probably the best solution. I'm not sure if there is any established way of formulating such rules in text format.

**Comment by damemi** [comment]
Have you considered [running the descheduler as a cronjob](https://github.com/kubernetes-sigs/descheduler#run-as-a-cronjob) only during the hours you want eviction? I could see wanting the granularity to run it during business hours for some workloads and outside for others, but that seems very specific for most use cases I'd imagine.

**Comment by seanmalloy** [comment]
@codablock have you considered setting up pod disruption budgets for the very sensitive applications? This would allow running descheduler during business hours, but prevent it from evicting too many pods for the very sensitive applications.

**Comment by ingvagabund** [comment]
You might also target only certain namespaces which are not too sensitive during working hours. Which strategies are mission critical for you?
