### ISSUE TITLE
Throttle pod eviction when past evictions led to the same node being chosen by the scheduler

### ISSUE THREAD

**Issue by codablock** [kubernetes-sigs/descheduler#424]
**Is your feature request related to a problem? Please describe.**
Currently, multiple missing features in descheduler cause re-scheduling of pods onto the same nodes again and again. Two such examples are https://github.com/kubernetes-sigs/descheduler/issues/335 and https://github.com/kubernetes-sigs/descheduler/issues/335#issuecomment-704899359. The descheduler currently never gives up.

**Describe the solution you'd like**
pod eviction should be throttled when a configurable number of past evictions led to the re-scheduling on the same node. This should be configurable via options (default values) and via annotations per pod.

I assume that there are more cases where pods are re-scheduled to the same node. I already encountered 2 such cases on the first run of descheduler. I also assume that it will take some time until all these cases are fixed, so I'd suggest to implement this feature first so that there is some sensible default/fallback behavior for such cases.

**Comment by damemi** [comment]
I think this would be related to our long-term goal of incorporating the actual scheduler framework into the descheduler to better inform eviction decisions (see related issues like https://github.com/kubernetes-sigs/descheduler/issues/261, https://github.com/kubernetes-sigs/descheduler/issues/238).

That work is making some progress, but currently at the step of breaking the scheduler framework out of core kubernetes (see upstream issue https://github.com/kubernetes/kubernetes/issues/89930). 

Like you mention, there are a lot of cases where an evicted pod will end up on the same node. The descheduler is pretty naïve and optimistic, so trying to cover all of these now would be a lot like re-writing existing scheduler logic.

We could potentially add some sort of "throttling" (maybe an annotation like `last-evicted-time/count`?) that could de-prioritize pods for eviction, but ultimately I think the ask here is a known issue of incorporating more scheduler logic.

**Comment by seanmalloy** [comment]
remove-lifecycle stale
