### ISSUE TITLE
Add Helm Test To Descheduler Automated CI Checks

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#440]
The descheduler CI checks currently only run `helm lint`. It would be great to also run `helm test` as part of CI. The Makefile will need to be updated to add support for `helm test`. It would probably also be good to add this as a separate CI check, see below URL.

https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/descheduler

**Comment by seanmalloy** [comment]
This documentation looks useful ... https://helm.sh/docs/topics/chart_tests/

**Comment by pravarag** [comment]
Hi @damemi @seanmalloy I would like to work on this issue if it's not already taken by somebody else.

**Comment by seanmalloy** [comment]
> Hi @damemi @seanmalloy I would like to work on this issue if it's not already taken by someone else.

@pravarag no one is working on this. Please feel free to submit a pull request. Let me know if you have any questions.

Thanks!

**Comment by pravarag** [comment]
@damemi @seanmalloy I was going through the current usage of `helm lint` as mentioned [here](https://github.com/kubernetes-sigs/descheduler/blob/0a11b5a138d89dc17fc4274a96be5350029f534a/Makefile#L133) and as I can understand linting doesn't require chart to be installed in a namespace. But, for `helm test <release_name>` we'll have to first install the chart in a namespace as suggested [here](https://helm.sh/docs/topics/chart_tests/#steps-to-run-a-test-suite-on-a-release) . So, do we have a K8s cluster where we can first install the release and then utilize it to perform the `helm test` or there might be other ways to achieve the same(maybe a dry-run)?

**Comment by seanmalloy** [comment]
@pravarag it will be very similar to the e2e tests. The helm tests will need to run in a kind cluster.

https://github.com/kubernetes-sigs/descheduler/blob/22fe589ae6adea5d1aded0314a80c808b3de1889/Makefile#L114-L115
https://github.com/kubernetes-sigs/descheduler/blob/master/test/run-e2e-tests.sh

**Comment by seanmalloy** [comment]
I'm think there would be a new Makefile target created named test-helm and it would run a script `./test/run-helm-tests.sh`

**Comment by pravarag** [comment]
> @pravarag it will be very similar to the e2e tests. The helm tests will need to run in a kind cluster.

Thanks @seanmalloy for sharing the above details and I can see the `kind cluster` creation step [here](https://github.com/kubernetes-sigs/descheduler/blob/master/test/run-e2e-tests.sh#L25) . So, I wanted to check whether I can use the same kind cluster to run `helm tests` or I'll be needing to create a new one? Also, I don't see a `kind delete cluster` mentioned anywhere in the scripts so are we not deleting that kind cluster?

**Comment by seanmalloy** [comment]
> > @pravarag it will be very similar to the e2e tests. The helm tests will need to run in a kind cluster.
> 
> Thanks @seanmalloy for sharing the above details and I can see the `kind cluster` creation step [here](https://github.com/kubernetes-sigs/descheduler/blob/master/test/run-e2e-tests.sh#L25) . So, I wanted to check whether I can use the same kind cluster to run `helm tests` or I'll be needing to create a new one? Also, I don't see a `kind delete cluster` mentioned anywhere in the scripts so are we not deleting that kind cluster?

I think having the script `test/run-helm-tests.sh` create a separate kind cluster should be fine. I see you added the code in your PR to delete the kind cluster, which is also fine.

Let me know if you have any other questions.

Thanks!

**Comment by pravarag** [comment]
@seanmalloy I need your help regarding this comment for helm tests: https://github.com/kubernetes-sigs/descheduler/pull/527#issuecomment-808738401. I wanted to understand the functionality of the test which we'll be writing as part of this issue.

**Comment by pravarag** [comment]
@seanmalloy please provide your review comments on these changes I've made at the latest here: https://github.com/kubernetes-sigs/descheduler/pull/527#issuecomment-815884849 . Let me know if those are good to go with or not 🙂

**Comment by pravarag** [comment]
@seanmalloy @damemi I've few doubts w.r.t adding a CI check for `helm test` changes.

I've added a CI check with the other checks here: https://github.com/pravarag/test-infra/commit/6e8d626e244a06789bb410c9f0112c14f80a5f8a but I wanted to check how to approach with `unit or integration` tests as mentioned in other CI checks in the same directory. Do I need to write new unit tests or integration tests for same or there are already few which I can utilize here.

Also let me know if it's okay to create a draft PR with the current changes under `kubernetes/test-infra` repo or not with work-in-progress so that I can share further updates with easy references.

**Comment by damemi** [comment]
@pravarag it's always okay to open a WIP PR 🙂  feel free to go ahead, that will make it easier to discuss the changes

**Comment by pravarag** [comment]
@seanmalloy @damemi can we close this issue as the test-infra PR: https://github.com/kubernetes/test-infra/pull/22391 is also merged now 🙂

**Comment by damemi** [comment]
@pravarag yup, this should be all set now. Thanks!
/close
