### ISSUE TITLE
ARM Container Image

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#445]
**Is your feature request related to a problem? Please describe.**

I would like to run the descheduler on ARM(specifically ARM64) hardware. I'd like an official descheduler container image for this use case.

**Describe the solution you'd like**

I would like the descheduler project to provide an official ARM64 container image in addition to the already provided x86_64 container image.

**Describe alternatives you've considered**

Not running descheduler on ARM.

**What version of descheduler are you using?**

descheduler version: v0.19.0

**Additional context**

The [k8s external-dns](https://github.com/kubernetes-sigs/external-dns) and [k8s cluster-proportional-autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) projects already provide official ARM container images on k8s.gcr.io. These can be used as a reference when setting up the build automation for the descheduler.

**Comment by seanmalloy** [comment]
@damemi and @ingvagabund any concerns with getting this setup for descheduler?

I'm willing to do the work if no one has any concerns. I'll attempt to get this done prior to the v0.20.0(k8s 1.20) release. It's not strictly required for this release, but I'd like to squeeze it in if I have the time.

Let me know what you think.

**Comment by ingvagabund** [comment]
Are there any missing bits to provide support for ARM64? Will ARM64 require special support?

**Comment by seanmalloy** [comment]
> Are there any missing bits to provide support for ARM64? Will ARM64 require special support?

I think the basics would be to get the Makefile updated to allowing easily passing the options to `go build` to compile for ARM64 and also adjust the Makefile for the container image builds.

I'm not aware of any Go code that would need to be changed to support ARM64. I'm hoping all that needs to be done is to update the build automation.

**Comment by damemi** [comment]
I don't have any concerns, but also don't know how this is done by the other repos :) So having the examples to follow is definitely helpful.

**Comment by seanmalloy** [comment]
I believe external-dns and cluster-proportional-autoscaler are leveraging the below feature to the multi-arch images.

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by seanmalloy** [comment]
I'll start working on this in the near future. Not required for the v0.20.0 release, but I'll see if I can get it done before then.

/assign

**Comment by seanmalloy** [comment]
I verified that the build automation is working now that #449 is merged to master. The multi-arch images are now being pushed to the staging registry.

```
kind create cluster
docker pull gcr.io/k8s-staging-descheduler/descheduler:v20201204-descheduler-helm-chart-0.19.0-80-gde24f3854
kind load docker-image gcr.io/k8s-staging-descheduler/descheduler:v20201204-descheduler-helm-chart-0.19.0-80-gde24f3854
```
