### ISSUE TITLE
RemovePodsViolatingTopologySpreadConstraint Support Soft Constraints

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#461]
**Is your feature request related to a problem? Please describe.**

As of the soon to be released descheduler version v0.20.0 the `RemovePodsViolatingTopologySpreadConstraint` strategy only supports evicting pods that are using [Pod Topology Spread](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) hard constraints.

It would be nice if descheduler also support evicting pods that use Pod Topology Spread soft constraints.

**Describe the solution you'd like**

Descheduler supports evicting pods that are using Pod Topology Spread soft constraints.

**Describe alternatives you've considered**

Pods using Pod Topology Spread soft constraints are not always balanced at runtime.

**What version of descheduler are you using?**

descheduler version: v0.20.0

**Additional context**

Slack thread: https://kubernetes.slack.com/archives/C09TP78DV/p1607421341263300
PR review comment in initial implementation: https://github.com/kubernetes-sigs/descheduler/pull/413#discussion_r499824758

**Comment by AmoVanB** [comment]
Simply removing the following check works fine in our test clusters:

```diff
diff --git a/pkg/descheduler/strategies/topologyspreadconstraint.go b/pkg/descheduler/strategies/topologyspreadconstraint.go
index 8c5067311..f9c72bd4c 100644
--- a/pkg/descheduler/strategies/topologyspreadconstraint.go
+++ b/pkg/descheduler/strategies/topologyspreadconstraint.go
@@ -127,11 +127,6 @@ func RemovePodsViolatingTopologySpreadConstraint(
                namespaceTopologySpreadConstraints := make(map[v1.TopologySpreadConstraint]struct{})
                for _, pod := range namespacePods.Items {
                        for _, constraint := range pod.Spec.TopologySpreadConstraints {
-                               // Only deal with hard topology constraints
-                               // TODO(@damemi): add support for soft constraints
-                               if constraint.WhenUnsatisfiable != v1.DoNotSchedule {
-                                       continue
-                               }
                                namespaceTopologySpreadConstraints[constraint] = struct{}{}
                        }
                }
```

We however only have soft constraints, so nothing guaranteed regarding the cohabitation of both types of constraints

**Comment by lixiang233** [comment]
We can add a parameter to let users decide whether to handle soft rules, the strategy may look like:
```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemovePodsViolatingTopologySpreadConstraint":
     enabled: true
     params:
        handleSoftTopologySpreadConstraints: true
```

**Comment by damemi** [comment]
Yeah, a parameter is a good idea so that the original behavior is still there with the option to add this. The name could be easier too, maybe just `softConstraints` or `includeSoftConstraints`

**Comment by lixiang233** [comment]
> The name could be easier too, maybe just `softConstraints` or `includeSoftConstraints`

I can help to add this parameter and I'll choose `includeSoftConstraints` for the name.
/assign
