### ISSUE TITLE
RemovePodsViolatingNodeTaints strategy: evict based on PreferNoSchedule taint

### ISSUE THREAD

**Issue by klebediev** [kubernetes-sigs/descheduler#472]
Our use-case is the following:
We have a Kubernetes cluster in AWS with 2 instance groups:
 - `on-demand` running on on-demand ec2 instances
 - `spot` running on spot ec2 instances

The idea is to schedule workloads to `spot` instance group, but when spot instances aren't available schedule to `on-demand`.
We have `PreferNoSchedule` taint attached to `on-demand` and `on-demand` has lower priority than `spot` in cluster-autoscaler config.

The problem is: in case of unavailability of spot instances some workloads were scheduled to `on-demand`, but after some time when spot instances are back, it's required to reschedule workloads from `on-demand` to `spot`.

So, in our case it would be useful to handle `PreferNoSchedule` taint in the same way as how `NoSchedule` taint is handled in `RemovePodsViolatingNodeTaints` strategy now.

**Comment by damemi** [comment]
Hi @klebediev, thanks for opening this. However, this appears to be a duplicate of another issue that's already tracking this feature (https://github.com/kubernetes-sigs/descheduler/issues/461), so I'm closing this one to keep the discussion in that issue. Please feel free to share your use case there!
/close

**Comment by klebediev** [comment]
Hi @damemi, 
Not sure I understand you correctly. My issue/feature request is about node `RemovePodsViolatingNodeTaints` strategy whereas you referred to #461 which is about `PodTopologySpreadConstraint` which seems to be a different thing.
Might you clarify, please.

**Comment by seanmalloy** [comment]
> Hi @damemi,
> Not sure I understand you correctly. My issue/feature request is about node `RemovePodsViolatingNodeTaints` strategy whereas you referred to #461 which is about `PodTopologySpreadConstraint` which seems to be a different thing.
> Might you clarify, please.

Re-opening based on above comment.

/reopen

**Comment by seanmalloy** [comment]
Here is a slack thread from `#sig-scheduling` discussing the same use case, but with a final solution that does not use the descheduler.  This is just for reference.

https://kubernetes.slack.com/archives/C09TP78DV/p1607641663293000

**Comment by damemi** [comment]
@klebediev sorry, I misread and you are correct that this is not a duplicate. My apologies!

**Comment by ingvagabund** [comment]
This looks like a one line change of updating [taint filter](https://github.com/kubernetes-sigs/descheduler/blob/7afa54519ff5ffbde75838339a0376cdfcb14127/pkg/descheduler/strategies/node_taint.go#L89) and extending the filter function with `v1.TaintEffectPreferNoSchedule` as well.

**Do we want to evict pods violating `v1.TaintEffectPreferNoSchedule` by default when `RemovePodsViolatingNodeTaints` is enabled?:**

Scheduler's `TaintToleration` plugin uses the taint to score nodes and find a node violating the taint the least. Given the pods get scheduled to nodes not violating the taint first, evicting pods will no have the intended goal when all the remaining nodes are violating at least one `TaintToleration` taint of a pod. At which point all the pod will "just" get re-distributed while still violating the taint. Depending on the number of such pods and resulting disruption effect, it may be acceptable to enable the new taint by default, it may be not. Opinions?

**Comment by seanmalloy** [comment]
> Depending on the number of such pods and resulting disruption effect, it may be acceptable to enable the new taint by default, it may be not. Opinions?

I feel like this is another use case where the descheduler could benefit from being able to import the scheduler code to more intelligently select pods for eviction.

/remove-lifecycle stale

**Comment by damemi** [comment]
Moving from https://github.com/kubernetes-sigs/descheduler/issues/612

I think as a best-effort attempt this could be enabled similar to how we added the soft topology constraints (https://github.com/kubernetes-sigs/descheduler/issues/461). It's not guaranteed in all situations, but in a case where pods are only on the violated nodes due to other nodes being down (and then those valid nodes come back up) it could help to redistribute them.

So, this is open to anyone who wants to work on it
