### ISSUE TITLE
How to to print text log in creen, and record json log into file  at the same time

### ISSUE THREAD

**Issue by garysdevil** [kubernetes-sigs/descheduler#476]
How to to print text log in creen, and record json log into file  at the same time?
I try to use  "--log-dir=/tmp/tmp --log-file test.log", but failed.
Hope there is a example.

**Comment by seanmalloy** [comment]
@garysdevil I don't believe there is a way to enable both text and json logs at the same time.

/kind suport

**Comment by damemi** [comment]
We could look into this, but note that this issue isn't specific to descheduler (we use the `klog` logging library and those flags are imported). So if you can find any other k8s project that has solved this problem, the solution should work for descheduler too.

**Comment by garysdevil** [comment]
> @garysdevil I don't believe there is a way to enable both text and json logs at the same time.
> 
> /kind suport

ok, but I failed to record log into file  by  parameters "--log-dir=/tmp/tmp --log-file test.log", can you give me a right example?
