### ISSUE TITLE
helm chart nodeSelector in cronjob

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/descheduler#479]
https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/templates/cronjob.yaml

**Comment by damemi** [comment]
Hi @matti, could you please add some more detail as to what it is you are requesting? I am not sure from your title whether you are referring to the `--node-selector` option in descheduler, or adding nodeSelectors to the cronjob, or something else. Thanks!

**Comment by matti** [comment]
in the cronjob.yaml

**Comment by damemi** [comment]
Hi @matti 
It sounds like you're referring to adding nodeSelectors to the cronjob itself. I opened a PR that I think will add that here: https://github.com/kubernetes-sigs/descheduler/pull/480
