### ISSUE TITLE
Add verify scripts for `make gen`

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#483]
Issues such as the one described in https://github.com/kubernetes-sigs/descheduler/pull/482 could be avoided if we add automatic verify scripts on PRs to ensure that `make gen` (and its subscripts) have been run. It should be simple enough as running `make gen` in a tmp dir and checking if any changes have been generated.

/kind cleanup
/help

**Comment by pravarag** [comment]
@damemi I would like to work on this issue if it's not already been taken  :)

**Comment by pravarag** [comment]
@damemi I've come across few doubts while trying to understand the issue. As you mentioned that we need this change to ensure `make gen` has run it's all subscripts proprerly and when I try to run `make gen` locally, it basically generates three binaries,
```
conversion-gen
deepcopy-gen
defaulter-gen
```
So, do we need to ensure that `make gen` has generated those three binaries in `/tmp` location properly or not?

**Comment by damemi** [comment]
Those binaries are what actually run to generate the updated code. `make gen` conveniently downloads them (if they do not already exist) and stores them in the tmp directory which is [ignored by git](https://github.com/kubernetes-sigs/descheduler/blob/master/.gitignore#L1).

The goal here is to make sure that code which is about to be committed has already run these generators. What we want to check is that the diff in a PR doesn't change when you run `make gen` against it. 

So, since the binaries themselves are not committed we can't check that they are stored in `/tmp` (but if they aren't being downloaded, then the generators won't be running anyway, so you will still see a diff).

**Comment by seanmalloy** [comment]
Not quite done yet.

/reopen

**Comment by pravarag** [comment]
@seanmalloy @damemi is it okay to close this issue now? The last PR for `defaulters gen` has been merged today. Let me know if there is anything else I need to check w.r.t this issue.

**Comment by seanmalloy** [comment]
I believe everything is done now. @pravarag thanks for your help with this!

/close
