### ISSUE TITLE
[Question] RemovePodsViolatingInterPodAntiAffinity behavior when number of nodes is unsufficient to satisfy anti affinity

### ISSUE THREAD

**Issue by kamilzzz** [kubernetes-sigs/descheduler#494]
What will be the behavior of descheduler when it detects that some pods on a node violate inter-pod anti-affinity (preferred, not required), but number of nodes is unsufficient to satisfy this anti-affinity? Will it evict pod anyway (and then it will be scheduled so it will violate anti-affinity again) or just ignore violation?

E.g.: inter-pod anti-affinity to limit number of pods of specific type to 1 per node. Deployment with 5 replicas but only 4 nodes are currently available in the cluster. Scheduler will schedule 2 pods on the same node as it's configured as soft requirement. How descheduler will behave?

**Comment by damemi** [comment]
Yes, right now the descheduler will evict whether or not there are other nodes the pod can fit on. The [PodAntiAffinity strategy](https://github.com/kubernetes-sigs/descheduler/blob/7afa545/pkg/descheduler/strategies/pod_antiaffinity.go#L87) is pretty basic.

We could probably improve it to handle cases more like [NodeAffinity](https://github.com/kubernetes-sigs/descheduler/blob/241f1325c968889e6abaf250b66bf0522c517506/pkg/descheduler/strategies/node_affinity.go#L81-L84), which checks that the pod can actually fit on another node. We may also want to consider adding cases for soft and hard requirements.

I think these are valid improvements worth considering
/kind feature

**Comment by kamilzzz** [comment]
From the source code (https://github.com/kubernetes-sigs/descheduler/blob/241f1325c968889e6abaf250b66bf0522c517506/pkg/descheduler/strategies/pod_antiaffinity.go#L111) I can see right now this strategy works only when anti-affinity is set as RequiredDuringSchedulingIgnoredDuringExecution, right?

**Comment by damemi** [comment]
@kamilzzz ah, yes, you're correct. I thought this only applied to hard checks, but I missed that section of code earlier. Thank you for refreshing my memory :)

However I still believe this will evict even if there are no other nodes where the hard antiaffinity can be satisfied, which could leave pods in pending state... so it may still be a good update to add an optional check here to see if the pod can fit on any other node before evicting it

**Comment by kamilzzz** [comment]
Yeah, checking if pod can fit on any other node is good idea anyway.

Right now I'm wondering if that makes any difference if anti-affinity is soft or hard. In any case we could just check if pod can fit on another node before evicting.

In my case I've soft requirement but anyway I would like for pods to be evicted if anti-affinity is not satisfied and it would be on another node. Problem with current implementation is that initially I might have 3 nodes and 3 pod replicas with anti affinity on them. Initially scheduler will probably spread them out, but when any node goes down descheduler would constantly kill that pod (for example every 2 minutes) until that node comes up again.
