### ISSUE TITLE
Clarify "number of pods in terms of percentage"

### ISSUE THREAD

**Issue by tux-o-matic** [kubernetes-sigs/descheduler#514]
One can clearly understand CPU or RAM requested in relation to the capacity of a Node.
But when reporting a value for Pod utilisation, the documentation mentions [number of pods in terms of percentage](https://github.com/kubernetes-sigs/descheduler/blob/master/README.md#lownodeutilization).

How is a number of running Pod per Node expressed in %, based on maxPods?

**Comment by damemi** [comment]
It is just a percentage of the pods currently on the node vs the capacity of pods for that node. The percentage is calculated based on the [capacity and allocatable](https://kubernetes.io/docs/concepts/architecture/nodes/#capacity) values for pods configured on the node in [this section of code](https://github.com/kubernetes-sigs/descheduler/blob/e014fda/pkg/descheduler/strategies/lownodeutilization.go#L218).

**Comment by tux-o-matic** [comment]
Thanks @damemi . Thank we could make that a little clearer in the description?

**Comment by damemi** [comment]
@tux-o-matic sure, I opened a change for that here: https://github.com/kubernetes-sigs/descheduler/pull/515
