### ISSUE TITLE
Clarify descheduler handling of StatefulSets

### ISSUE THREAD

**Issue by lindhe** [kubernetes-sigs/descheduler#519]
It's clear to me from the documentation that _"Pods with local storage are never evicted (unless `evictLocalStoragePods: true` is set)"_, which makes sense since that indicates that the application is stateful and thus cannot be restarted as surely as a stateful app would. I would assume the same logic holds for pods in `StatefulSets`, but I find no documentation about that.

~If my assumption is correct:~
- [ ] ~we should add that to the documentation.~

If my assumption is incorrect:
- [x] let's clarify that in the documentation.
- [ ] ~I suggest we reconsider that design choice.~

If I'm missing something here, please fill me in.

**Comment by seanmalloy** [comment]
Based on the below code block I believe that the descheduler will consider StatefulSets for eviction.

https://github.com/kubernetes-sigs/descheduler/blob/6abfa232e79d12496fbb6e12c8b7fce55189fa17/pkg/descheduler/evictions/evictions.go#L218-L249

If I'm correct then the docs [here](https://github.com/kubernetes-sigs/descheduler#pod-evictions) just need to be updated to indicate that StatefulSet pods are considered for eviction in addition to RC, RS, Deployment and Job.

If the ask is to add a feature to have an option to include/exclude StatefulSet pods then this would be a feature enhancement request. Keep in mind there are already many other ways to have the descheduler include/exclude pods.

https://github.com/kubernetes-sigs/descheduler#filter-pods

Also, starting with the upcoming descheduler v0.21.0 release there will be an `ignorePvcPods` option in addition to the current`evictLocalStoragePods` option.

**Comment by seanmalloy** [comment]
I created PR #520 to document the current behavior.

@lindhe is updating the documentation good enough to close this issue or do you want to discuss a feature for excluding StatefulSets further?

From my perspective I think the descheduler has enough options to choose which pods are considered or not considered for eviction, but we welcome feedback if the current functionality does not fit your needs.

**Comment by lindhe** [comment]
Cool, thanks a lot for the PR! Having it documented properly was the most important part in my view. I may continue the discussion to understand better why sts by their nature are not excluded, but if I continue that thread it can surely be done without this Issue open.

Let's mark this as closed when the PR is merged.

**Comment by seanmalloy** [comment]
Task to complete before closing this issue:
- [ ] documentation
- [ ] unit tests
- [ ] e2e tests

**Comment by ingvagabund** [comment]
@seanmalloy do you still want to implement e2e for this?

**Comment by seanmalloy** [comment]
> @seanmalloy do you still want to implement e2e for this?

@ingvagabund yes I was going to wait until #535 is merged.

**Comment by ingvagabund** [comment]
@seanmalloy The PR is merged
/remove-lifecycle stale

**Comment by seanmalloy** [comment]
FYI ... I'm still going to submit a PR to implement the e2e tests. I had to take a break for a bit.
