### ISSUE TITLE
Improve LowNodeUtilization's consideration of evictable pods

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#529]
Similar to how we check that a pod fits on other nodes before evicting in strategies like Affinity/TopologySpread, it would be an improvement if LowNodeUtilization checked that a pod from an overutilized node can fit on the intended underutilized node before evicting it (ie, check for taints/affinity). This could improve the performance of the strategy and prevent unnecessary infinite evictions each run.

**Comment by RyanDevlin** [comment]
I can try this one.

**Comment by RyanDevlin** [comment]
@damemi I've noticed that the Affinity and TopologySpread strategies check for affinity on other nodes, but don't necessarily check for taints. Is checking for taints on other nodes still something that should be included in this feature?

**Comment by rustrial** [comment]
@RyanDevlin I guess eviction only makes sense if the Pod can be scheduled on another node, therefore it seems reasonable that all scheduling constraints (Affinity, TopologySpread and Taints) should be checked. Otherwise we would just evict a Pod to see it being scheduled to the same node again, which just increases the risk of service outages caused by Pod eviction (restart).

**Comment by RyanDevlin** [comment]
@rustrial At the bottom of #551 @ingvagabund commented about how, for the purposes of this feature, it would be overkill to take into account every filtering plugin. I'm currently implementing this feature with checks for NodeAffinity, Taints, and NodeSelector. The optimization isn't perfect, but statistically it should improve performance.

**Comment by ingvagabund** [comment]
Overkill on the code level view (duplicating the code since we can't import kubernetes/kubernetes code).

**Comment by ingvagabund** [comment]
> Otherwise we would just evict a Pod to see it being scheduled to the same node again, which just increases the risk of service outages caused by Pod eviction (restart).

That's responsibility of PDB to take care of disruptions.

**Comment by damemi** [comment]
> @RyanDevlin I guess eviction only makes sense if the Pod can be scheduled on another node

I mentioned this in the other thread (https://github.com/kubernetes-sigs/descheduler/issues/551#issuecomment-820542336), sorry for not bringing it up here... but there are use cases where a pod could be evicted regardless of if it fits on another node. For strategies like `PodLifetime`, you might actually want to evict a pod that will only be recreated on the same node

**Comment by jecnua** [comment]
Still valid

**Comment by damemi** [comment]
Bumped the NodeFit PR to get that moving again
/remove-lifecycle stale

**Comment by ingvagabund** [comment]
Fixed in https://github.com/kubernetes-sigs/descheduler/pull/790
/close
