### ISSUE TITLE
[docs] What is the minimum cluster version it supports

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes-sigs/descheduler#536]
I did not find relevant information in the documentation

**Comment by damemi** [comment]
Hi,
The descheduler isn't strictly tied to a specific version, but each release is tested to be compatible with the past 3 Kubernetes cluster versions. Please see ["Compatibility" in the README](https://github.com/kubernetes-sigs/descheduler#compatibility-matrix)

/remove-kind bug
/kind suppport

**Comment by zhangguanzhang** [comment]
thanks
