### ISSUE TITLE
How to automatically  generated code

### ISSUE THREAD

**Issue by wxuedong** [kubernetes-sigs/descheduler#542]
Hi：
       I want to submit PR , When I am finished modifying the code, the automatically generated code has an error， Do I need to regenerate the code when an error occurs ？，If needed then what are the steps ？
       For example, I modify the struct parameter in types.go ,At this time, the unit test is run and the compilation fails，What to do when this happens ？

**Comment by lixiang233** [comment]
@wxuedong Just run `make gen`

**Comment by wxuedong** [comment]
> @wxuedong Just run `make gen`

Thank you for your answer，

 After executing `make run`  other problems occurred.
"Warning: could not find nor generate a final Conversion function for sigs.k8s.io/descheduler/pkg/api.StrategyParameters -> sigs.k8s.io/descheduler/pkg/api/v1alpha1.StrategyParameters"
"The following fields need manual conversion:"
   -NodeAffinityType
   -RemovePodsViolatingNodeTaints
   "NodeAffinityType" and "RemovePodsViolatingNodeTaints" are new fields,How to solve this problem ?

**Comment by lixiang233** [comment]
You should add these new fields to both `sigs.k8s.io/descheduler/pkg/api/types.go` and `sigs.k8s.io/descheduler/pkg/api/v1alpha1/types.go`

**Comment by wxuedong** [comment]
> You should add these new fields to both `sigs.k8s.io/descheduler/pkg/api/types.go` and `sigs.k8s.io/descheduler/pkg/api/v1alpha1/types.go`, and run `make gen` again

Two files have been synchronized .
Console output :
ls: _output/bin/golangci-lint: No such file or directory
./hack/update-generated-conversions.sh
./hack/update-generated-deep-copies.sh
./hack/update-generated-defaulters.sh
./hack/update-toc.sh

zz_generated_xxxx.go  files is not updated , the file is still old

**Comment by wxuedong** [comment]
> > You should add these new fields to both `sigs.k8s.io/descheduler/pkg/api/types.go` and `sigs.k8s.io/descheduler/pkg/api/v1alpha1/types.go`, and run `make gen` again
> 
> Two files have been synchronized .
> Console output :
> ls: _output/bin/golangci-lint: No such file or directory
> ./hack/update-generated-conversions.sh
> ./hack/update-generated-deep-copies.sh
> ./hack/update-generated-defaulters.sh
> ./hack/update-toc.sh
> 
> zz_generated_xxxx.go files is not updated , the file is still old

The old file is deleted, and no new file is created by re-make

**Comment by seanmalloy** [comment]
@wxuedong what version of Go are you using?

/kind support

**Comment by wxuedong** [comment]
> @wxuedong what version of Go are you using?
> 
> /kind support

go version go1.14.4

**Comment by seanmalloy** [comment]
@wxuedong the descheduler master branch is currently using Go 1.16.1. Try using a newer Go version. I'm not sure this will fix the problem, but this is the only thing I can think of.

**Comment by wxuedong** [comment]
> @wxuedong the descheduler master branch is currently using Go 1.16.1. Try using a newer Go version. I'm not sure this will fix the problem, but this is the only thing I can think of.

I have upgraded to version 1.16.3 and still have no solution ,  I am thinking if it has something to do with my local environment configuration

**Comment by JacobHenner** [comment]
> I have upgraded to version 1.16.3 and still have no solution , I am thinking if it has something to do with my local environment configuration

Were you able to figure out the cause? I'm experiencing this with go 1.17.

**Comment by JacobHenner** [comment]
> > I have upgraded to version 1.16.3 and still have no solution , I am thinking if it has something to do with my local environment configuration
> 
> Were you able to figure out the cause? I'm experiencing this with go 1.17.

The issue was https://github.com/kubernetes-sigs/descheduler/pull/316
