### ISSUE TITLE
Exception stops execution of descheduler

### ISSUE THREAD

**Issue by damoon** [kubernetes-sigs/descheduler#579]
**What version of descheduler are you using?**

descheduler version: v0.20.0

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
default helm chart from https://kubernetes-sigs.github.io/descheduler/

**Please provide a copy of your descheduler policy config file**
default helm chart from https://kubernetes-sigs.github.io/descheduler/

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

1. Deployed Descheduler and a few other services.  
Descheduler does its job like its should.

2. Deployed Kata containers https://github.com/kata-containers/kata-containers/tree/main/tools/packaging/kata-deploy

**What did you expect to see?**

Descheduler keeps working as before.

**What did you see instead?**

Descheduler fails to execute with this exception
```
E0528 08:41:48.775507       1 runtime.go:78] Observed a panic: &errors.errorString{s:"feature \"PodOverhead\" is not registered in FeatureGate \"k8s.io/apiserver/pkg/util/feature/feature_gate.go:28\""} (feature "PodOverhead" is not registered in FeatureGate "k8s.io/apiserver/pkg/util/feature/feature_gate.go:28")
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x153ddc0, 0xc00027a380)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x153ddc0, 0xc00027a380)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/component-base/featuregate.(*featureGate).Enabled(0xc0003a5140, 0x171d05b, 0xb, 0x0)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/component-base/featuregate/feature_gate.go:302 +0x237
sigs.k8s.io/descheduler/pkg/utils.PodRequestsAndLimits(0xc000210fa0, 0x157c, 0x6)
	/go/src/sigs.k8s.io/descheduler/pkg/utils/pod.go:142 +0x5dd
sigs.k8s.io/descheduler/pkg/descheduler/strategies.nodeUtilization(0xc000546900, 0xc0000cee00, 0x27, 0x40, 0xc000546900)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/lownodeutilization.go:441 +0x347
sigs.k8s.io/descheduler/pkg/descheduler/strategies.getNodeUsage(0x190a9a0, 0xc000138020, 0x192a6c0, 0xc000420f20, 0xc0004664c0, 0x4, 0x4, 0xc000716a20, 0xc0007169f0, 0x0, ...)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/lownodeutilization.go:220 +0x174
sigs.k8s.io/descheduler/pkg/descheduler/strategies.LowNodeUtilization(0x190a9a0, 0xc000138020, 0x192a6c0, 0xc000420f20, 0xc000496c01, 0x0, 0xc000408de0, 0xc0004664c0, 0x4, 0x4, ...)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/lownodeutilization.go:102 +0x229
sigs.k8s.io/descheduler/pkg/descheduler.RunDeschedulerStrategies.func1()
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:123 +0x30a
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0002a5b10)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000dbb10, 0x18cf8e0, 0xc00052d140, 0x1, 0xc000516060)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002a5b10, 0x0, 0x0, 0x1, 0xc000516060)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
sigs.k8s.io/descheduler/pkg/descheduler.RunDeschedulerStrategies(0x190a9a0, 0xc000138020, 0xc00038de00, 0xc00047f600, 0xc0000468a0, 0xe, 0xc000516060, 0x0, 0x0)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:98 +0x536
sigs.k8s.io/descheduler/pkg/descheduler.Run(0xc00038de00, 0x18d11c0, 0xc0004662e0)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:60 +0x196
sigs.k8s.io/descheduler/cmd/descheduler/app.Run(...)
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/app/server.go:67
sigs.k8s.io/descheduler/cmd/descheduler/app.NewDeschedulerCommand.func1(0xc0003a7b80, 0xc0003a51c0, 0x0, 0x4)
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/app/server.go:52 +0x87
github.com/spf13/cobra.(*Command).execute(0xc0003a7b80, 0xc000140010, 0x4, 0x4, 0xc0003a7b80, 0xc000140010)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a7b80, 0xc0002a5f58, 0x1, 0x1)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/descheduler.go:34 +0xbd
panic: feature "PodOverhead" is not registered in FeatureGate "k8s.io/apiserver/pkg/util/feature/feature_gate.go:28" [recovered]
	panic: feature "PodOverhead" is not registered in FeatureGate "k8s.io/apiserver/pkg/util/feature/feature_gate.go:28"
```

The cluster is running with default feature gates.  
PodOverhead is enabeld by default.

**Comment by damemi** [comment]
That's definitely an odd error. When you say you expect `Descheduler keeps working as before`, does this mean you didn't have this problem before deploying the Kata containers, or before deploying this version of Descheduler?

**Comment by damoon** [comment]
Descheduler was deployed in previous versions before. Older and the current version work great for me. Thanks by the way.

This exception happened once when kata containers was deployed. It directly started, maybe after deploying the examples of kata containers.
I never tried kata containers before, therefore I can't say much about the error in old versions.

**Comment by damemi** [comment]
@damoon thanks for clarifying, that is interesting. I wonder if maybe Kata containers are doing something with feature gates in the cluster? I'll have to try running it myself to see if I can reproduce with that

**Comment by damoon** [comment]
hi :D
anything i can support here?

**Comment by Jc2k** [comment]
I just hit this as well, and also have Kata containers.

**Comment by Jc2k** [comment]
It will only check the feature gate when it hits a pod with `spec.overhead` != nil, could that explain why kata users hit this and "normal" users don't?

**Comment by damemi** [comment]
I'm not familiar with Kata containers, but if `spec.overhead != nil` that should imply that the `PodOverhead` feature gate is enabled, right? This may be a question for the Kata developers, but does it do anything to disable that feature gate?

**Comment by Jc2k** [comment]
The feature gate isn't disabled AFAICT.

I believe the extent of kata's involvement here is that it provides a RuntimeClass with a pod overhead, for example:

```
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-fc
handler: kata-fc
overhead:
    podFixed:
        memory: "120Mi"
        cpu: "250m"
```

Pods then reference that runtime class in the normal way:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  runtimeClassName: kata-fc
```

And this means they get a `spec.overhead`. AIUI, kata doesn't set the overhead, kubernetes does, because of the RuntimeClass.

If something had turned the feature gate off then `spec.overhead` this wouldn't get set. It's presence means the feature is turned on.

AIUI the default runtime class does not have a overhead, so most installations won't even try to test the feature gate because of short circuit evaluation. (I.e. it does `if spec.overhead && featuregate_enabled` rather than `if featuregate_enabled && spec.overhead). What i'm saying is, I wonder if the feature gate check is broken, but only clusters where at least one pod actually has an overhead notice it, because of the short cirtcuit evaluation.

**Comment by ingvagabund** [comment]
Fixed in https://github.com/kubernetes-sigs/descheduler/pull/790
/close
