### ISSUE TITLE
podStatusPhases support containercreating status 

### ISSUE THREAD

**Issue by lovejoy** [kubernetes-sigs/descheduler#580]
**Is your feature request related to a problem? Please describe.**

some network issue or cni issue may cause pods always containercreating 
sth like https://github.com/kubernetes-sigs/descheduler/issues/62
**Describe the solution you'd like**

podStatusPhases now only support  `Running` and `Pending` should add some other status

**Comment by damemi** [comment]
`ContainerCreating` isn't a valid pod status phase, which is what we check for: https://github.com/kubernetes/api/blob/v0.21.1/core/v1/types.go#L2506-L2526. I'm not sure how kubectl determines the ContainerCreating status but we could look into what that technically is so that we can check for it

**Comment by lovejoy** [comment]
@damemi  https://github.com/kubernetes/api/blob/v0.21.1/core/v1/types.go#L2415-L2421 

![image](https://user-images.githubusercontent.com/469764/120632484-98f37880-c49b-11eb-803b-67609397d6a2.png)

**Comment by damemi** [comment]
Thanks @lovejoy 
So it looks like to add this, we would need to add logic to do the following:
```
for each pod
  for each container
    if containerStatus.State.Waiting != nil && containerStatus.State.Waiting.Reason == "ContainerCreating"
      evict this pod
```
We could add this logic into where we currently check [status phases](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/pod_lifetime.go#L80-L88).

**Comment by hanumanthan** [comment]
If a pod has multiple containers and only one of them is stuck in `ContainerCreating` state, how should we deal with the eviction ? The pod may be unusable with the stuck container, so does it make sense to evict ?

**Comment by damemi** [comment]
That is a good question. I don't think we will be able to accurately answer it without gathering more user feedback, though it sounds like from this request if *any* container is ContainerCreating, that will trigger the kubectl output status that @lovejoy is requesting to act on

**Comment by a7i** [comment]
> Thanks @lovejoy So it looks like to add this, we would need to add logic to do the following:
> 
> ```
> for each pod
>   for each container
>     if containerStatus.State.Waiting != nil && containerStatus.State.Waiting.Reason == "ContainerCreating"
>       evict this pod
> ```
> 
> We could add this logic into where we currently check [status phases](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/pod_lifetime.go#L80-L88).

This would also help with CrashLoopBackoff containers. i.e. `containerStatus.State.Waiting.Reason == "CrashLoopBackoff"`. We are moving off of an in-house tool so I would be open to proposing a PR in the next few days. Any ideas on what the schema should look like?

```
  "PodLifeTime":
     enabled: true
     params:
       podLifeTime:
         maxPodLifeTimeSeconds: 86400
         reasons:
         - "CrashLoopBackoff"
         - "ContainerWaiting"
         podStatusPhases:
         - "Pending"
         - "Running"
```

**Comment by damemi** [comment]
/remove-lifecycle rotten

@a7i sorry, this slipped for me... I think it might be confusing for some users to have `phases` and `reasons` as separate fields. We've seen a couple reports of people asking why `podStatusPhases` doesn't support a specific phase, when it's not actually a phase (similar to this one)

It might be easier for people if we just lump everything into a single field, so they don't need to know the technical details of what the `status` they see from kubectl is. Do you think there's any potential problems with that?

**Comment by a7i** [comment]
>It might be easier for people if we just lump everything into a single field, so they don't need to know the technical details of what the status they see from kubectl is

@damemi I do not see any issues with that. Will work on a PR soon-ish.
