### ISSUE TITLE
How to build docker image???

### ISSUE THREAD

**Issue by ToughLama** [kubernetes-sigs/descheduler#590]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version:

**Additional context**

**Comment by damemi** [comment]
Hi @ToughLama,
You can build the docker image using the `make image` commands, which are provided for [various arch's](https://github.com/kubernetes-sigs/descheduler/blob/master/Makefile#L65-L75), or by calling the [Dockerfile](https://github.com/kubernetes-sigs/descheduler/blob/1606698/Dockerfile) directly with `docker build`.
