### ISSUE TITLE
no matches for kind "DeschedulerPolicy"

### ISSUE THREAD

**Issue by tintranvan** [kubernetes-sigs/descheduler#595]
I have already install descheduler for my cluster ( k8s v1.20.0) as deployment. 
Deployment status is running.
But when i trying to run example manifest
`apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
     params:
       removeDuplicates:
         excludeOwnerKinds:
         - "ReplicaSet"
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
  "RemovePodsHavingTooManyRestarts":
     enabled: true
     params:
       podsHavingTooManyRestarts:
         podRestartThreshold: 20
         includingInitContainers: true`

I got the issue : 

` no matches for kind "DeschedulerPolicy" in version "descheduler/v1alpha1"`

There is no idea for this. Pls help me to resolve them

**Comment by a7i** [comment]
@tintranvan What do you mean by

> But when i trying to run example manifest

`DeschedulerPolicy` needs to be inside of a ConfigMap as shown here: https://github.com/kubernetes-sigs/descheduler/blob/master/kubernetes/base/configmap.yaml#L8
You do not directly create that resource.

**Comment by damemi** [comment]
I think this was answered by @a7i's comment above https://github.com/kubernetes-sigs/descheduler/issues/595#issuecomment-874210986
/close

**Comment by tanwarsatya** [comment]
@damemi I think if possible it would be better to update the usage document, I stumbled upon this thread while looking for the same issue.
