### ISSUE TITLE
TopologySpreadConstraint should take target node's requests allocation into consideration before evicting

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#604]
**Is your feature request related to a problem? Please describe.**

TopologySpreadConstraint strategy should take target node's requests allocation into consideration before evicting them.

For example, if I have 3 nodes in the cluster with 3 domains size `[7 5 3]`, `maxSkew=1`, `whenUnsatisfiable=ScheduleAnyways`, it will attempt to evict 2 pods from the node1 and place them on node3 without any consideration of whether node3 is over-allocated or not. If the cluster is not set to scale, we will get in a constant evict/schedule loop as the 2 pods get evicted (and since node3 is over-allocated), Scheduler will put it back on node1 again.

**Describe the solution you'd like**

It would be ideal for Descheduler to take target node's requests allocation into consideration to see if the pods that are about to be evicted would fit on the target node.

**Describe alternatives you've considered**

No workarounds.

**What version of descheduler are you using?**

descheduler version: v0.21.0

**Additional context**

This is related to other non-utilization strategies as well.

**Comment by damemi** [comment]
This could apply to all strategies in theory, couldn't it? It's not a bad idea, but perhaps this could be added as just another check for the `PodFitsAnyNode` function

**Comment by a7i** [comment]
@damemi correct. happy to contribute to this. any discussion/plans to-date?

**Comment by damemi** [comment]
@a7i this is the first it's been discussed that I can remember

Though perhaps we could merge this issue with the NodeFit feature discussion in https://github.com/kubernetes-sigs/descheduler/issues/529. I think it would fit well as an additional check cc @ingvagabund @seanmalloy @RyanDevlin wdyt?

**Comment by RyanDevlin** [comment]
I agree, this check should occur in the `PodFitsAnyNode` function in `pkg/descheduler/node/node.go`.

@damemi as we add checks to `PodFitsAnyNode` it slowly starts to resemble the filtering plugins the Scheduler uses. Should we be integrating or reusing code from there to implement these checks? How does this evolve as we scale the descheduler?

**Comment by damemi** [comment]
@RyanDevlin we started some work to try to break out the upstream scheduler plugin code to be re-used in the Descheduler, but right now it's too entangled into core k8s to do so. We have an issue for that here: https://github.com/kubernetes-sigs/descheduler/issues/238

For the time being our only option has been to manually re-code, or now we can use helper functions from https://github.com/kubernetes/component-helpers which have already been broken out

**Comment by RyanDevlin** [comment]
@damemi Understood. In that case I can grab this one if it's not taken? I've been looking for something to contribute to.

**Comment by damemi** [comment]
Please feel free!
/assign @RyanDevlin

**Comment by raul-te** [comment]
@RyanDevlin Thank you for working on this issue! Is there anything I can do to help? The eviction loops caused by this bug are preventing me from deploying descheduler to prod, so I'd be very happy to contribute as well.

**Comment by RyanDevlin** [comment]
@raul-te I'm finalizing work on this feature, and I hope to have a WIP pull request opened sometime next week. In the meantime, could you provide some more context regarding your specific use-case? Which resource type is causing your eviction loop? For instance do your nodes fail to fit the evicted pod because their memory requests are maxed out? Or CPU, etc.?

**Comment by raul-te** [comment]
@RyanDevlin that's great news. Thanks again for working on this bug.

In my case, the resource causing the eviction loop is memory. For example, on a replica set with 3 pods, these are the requested resources:
```
redacted-pod-name-7f69c655d8
          requests:
            cpu: "2"
            memory: 7Gi
```

These are the resources of the nodes able to run this workload:
```
redacted-node-name-105-117.compute.internal: Pods: 1 — Used memory: 61463680Ki (95%) — Used cpu: 11081m (32%)
redacted-node-name-113-131.compute.internal: Pods: 0 — Used memory: 62422216Ki (97%) — Used cpu: 9356m (27%)
redacted-node-name-123-159.compute.internal: Pods: 0 — Used memory: 63059360Ki (98%) — Used cpu: 19356m (56%)
redacted-node-name-33-56.compute.internal: Pods: 2 — Used memory: 26426764Ki (41%) — Used cpu: 10631m (31%)
redacted-node-name-41-195.compute.internal: Pods: 0 — Used memory: 63275512Ki (98%) — Used cpu: 9381m (27%)
redacted-node-name-55-230.compute.internal: Pods: 0 — Used memory: 55621096Ki (86%) — Used cpu: 10281m (30%)
redacted-node-name-60-34.compute.internal: Pods: 0 — Used memory: 51670596Ki (80%) — Used cpu: 11531m (33%)
```

and these are the  relevant descheduler 0.21 logs:
```
I0907 23:16:30.696368       1 node.go:123] "Pod can possibly be scheduled on a different node" pod="redacted-ns/redacted-pod-name-7f69c655d8-pbdh7" node="redacted-node-name-113-131.compute.internal"
I0907 23:16:36.935390       1 node.go:123] "Pod can possibly be scheduled on a different node" pod="redacted-ns/redacted-pod-name-7f69c655d8-226ff" node="redacted-node-name-105-117.compute.internal"
I0907 23:16:36.935412       1 node.go:123] "Pod can possibly be scheduled on a different node" pod="redacted-ns/redacted-pod-name-7f69c655d8-kdrh7" node="redacted-node-name-105-117.compute.internal"
I0907 23:16:36.936348       1 duplicates.go:163] "Duplicate found" pod="redacted-ns/redacted-pod-name-7f69c655d8-kdrh7"
I0907 23:16:46.936999       1 duplicates.go:194] "Adjusting feasible nodes" owner={namespace:redacted-ns kind:ReplicaSet name:redacted-pod-name-7f69c655d8 imagesHash:redacted-pod-name:tag} from=<redacted> to=7
I0907 23:16:46.937021       1 duplicates.go:202] "Average occurrence per node" node="redacted-node-name-33-56.compute.internal" ownerKey={namespace:redacted-ns kind:ReplicaSet name:redacted-pod-name-7f69c655d8 imagesHash:redacted-pod-name:tag} avg=1
I0907 23:16:46.955613       1 evictions.go:130] "Evicted pod" pod="redacted-ns/redacted-pod-name-7f69c655d8-kdrh7" reason="RemoveDuplicatePods"
I0907 23:16:46.956039       1 event.go:291] "Event occurred" object="redacted-ns/redacted-pod-name-7f69c655d8-kdrh7" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerRemoveDuplicatePods"

```

**Comment by RyanDevlin** [comment]
@raul-te Thank you for the detailed logs. I'll use these to help inform my design.

**Comment by ingvagabund** [comment]
Fixed in https://github.com/kubernetes-sigs/descheduler/pull/790
/close
