### ISSUE TITLE
Docs around autohealing are misleading

### ISSUE THREAD

**Issue by Niksko** [kubernetes-sigs/descheduler#606]
The [docs around autohealing](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md#autoheal-node-problems) are a bit misleading in my opinion.

They link off to Node Problem Detector, claiming that `Node Problem Detector can detect specific Node problems and taint any Nodes which have those problems.`. In fact, NPD doesn't do any tainting. It's the `TaintNodeByCondition` feature of the node controller that takes _some_ conditions and turns them in to taints. However this only works for the default node conditions: `PIDPressure`, `MemoryPressure`, `DiskPressure`, `Ready`, and some cloud provider specific conditions.

There is an [open PR](https://github.com/kubernetes/node-problem-detector/pull/565) on NPD that wants to add this tainting behaviour, but the maintainers seem to think it shouldn't be NPD that does the tainting.

The effect is that the autoheal cycle describe doesn't actually work, at least not for custom conditions. It would be wonderful if it did, because it's quite a compelling outcome, and it would be amazing if it were offered exclusively in terms of Kubernetes first party tooling.

At the very least, we should change the wording in the docs to make it clear that NPD doesn't really participate in the autohealing. At most, I'm hoping that by raising this issue, the fact that this cycle doesn't currently work as intended can get a little more visibility. My guess at possible solutions:
* Merge the PR linked above, so that NPD creates taints
* Extend the node controller to add condition based taints for _all_ conditions, including custom ones
* Create a new project to convert conditions in to taints
* Add a new strategy in this repo that allows for descheduling based on Conditions

**Comment by seanmalloy** [comment]
@Niksko thanks for bringing this up. I think the first step is to fix the documentation for descheduler and NPD to indicate that the auto healing feature only works with the k8s builtin node conditions. Would you be willing to submit the PRs to fix the docs?

/kind documentation

**Comment by JaneLiuL** [comment]
i would like to open a pr for fix it today
