### ISSUE TITLE
Can Descheduler able to reshdule the pods which has PreferNoSchedule value

### ISSUE THREAD

**Issue by amitdrana** [kubernetes-sigs/descheduler#612]
Hi Team,
  I have a situation,  we have pods in which we have set `Tolerations:   on-demand=true: PreferNoSchedule`, and in nodes, we have set on-spot and on-demand taints.
  So When the spot instances are not ready or terminated due to some reason and all the pods are scheduled to on-demand nodes as per the toleration setting.
  
  Can Deschduler has the ability to reschedule the pods to on-spot instances when the spot instance is available again.

**Comment by damemi** [comment]
Hi @amitdrana, there is an issue open discussing this already: https://github.com/kubernetes-sigs/descheduler/issues/472

It seems like that has stalled out, but we can move the discussion there to get it going again. However I'm going to close this issue as duplicate
/close
