### ISSUE TITLE
Advise for descheduler Implementation

### ISSUE THREAD

**Issue by darkgordon** [kubernetes-sigs/descheduler#620]
Hello everyone, nice to meet you :)

Could you please give me adivse of my implementation using  HPA, cluster autoscaler and descheduler inside of a k8s cluster provisioned by Kops

The goal of my  implementation is when there is a lot of load in the cluster, the hpa triggers new pods, scales up if necessary and then use descheduler to evict some pods and hope to kubernetes scheduler to balance the cluster. In my case I used the following strategies: LowNodeUtilization and RemoveDuplicates 

The problem I had is that when the load of my cluster started to go down  I noticed that some pods were in state “terminating” and then scheduled again not allowing my hpa to scale down.

I checked the logs from the pods of the descheduler and noticed that there were a lot of evicted pods triggers, then I uninstalled my descheduler and I could see that the downscaling of pods was successful.

I have the following questions of this behavior

Is there anyway that Descheduler don't work well with HPA enabled ?
Is there any good practices for the implementation of descheduler with HPA or cluster autoscaler?

I share my helm descheduler strategies used.

    **RemoveDuplicates**:
      enabled: true
      params:
        thresholdPriority: 50000
        nodeFit: true
        namespaces:
          include:
          - "apps"
          - "default"
    **LowNodeUtilization**:
      enabled: true
      params:
        thresholdPriority: 10000
        nodeFit: true
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 60
            memory: 60
          targetThresholds:
            cpu: 80
            memory: 80

Any advice, help or documentation is welcome.

Thanks a lot :)

**Comment by seanmalloy** [comment]
> The problem I had is that when the load of my cluster started to go down I noticed that some pods were in state “terminating” and then scheduled again not allowing my hpa to scale down.
> 
> I checked the logs from the pods of the descheduler and noticed that there were a lot of evicted pods triggers, then I uninstalled my descheduler and I could see that the downscaling of pods was successful.

Could your provide the k8s events for those terminating pods? Also please provide the descheduler logs with `--v=4` log level.

I haven't run descheduler with HPA or cluster auto scaler, so I'm not aware of any best practices for using them together.
