### ISSUE TITLE
Can we provide a feature that balances the load from the node MEM dimension?

### ISSUE THREAD

**Issue by Kuri-su** [kubernetes-sigs/descheduler#631]
**Is your feature request related to a problem? Please describe.**
I saw that `descheduler` calculates the Mem usage of Pod to get the actual usage MEM on each machine, but this will ignore the memory usage of some programs running directly on the host

**Describe the solution you'd like**
so , can we provide a feature that balances the load from the node MEM dimension?

**Comment by damemi** [comment]
Getting the actual memory usage requires access to metrics, and I'm not sure if even those metrics will report on programs running outside of k8s. Either way, we do already have an issue open to try implementing metrics-based real usage evictions: https://github.com/kubernetes-sigs/descheduler/issues/225. I think this is a duplicate of that, do you agree @Kuri-su ?

**Comment by Kuri-su** [comment]
yes, this issue  is the same as  #225 , thanks
