### ISSUE TITLE
Ignore Pods With Deletion Timestamp

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#638]
As a follow-up, some of the other strategies could benefit from this as well. Possibly a good place would be [ListPodsOnANode](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/pod/pods.go#L159)), for those that use that.

_Originally posted by @a7i in https://github.com/kubernetes-sigs/descheduler/pull/621#pullrequestreview-754599387_

**Comment by seanmalloy** [comment]
The `RemovePodsViolatingTopologySpreadConstraint` strategy now ignores pods with `.metadata.DeletionTimestamp` set. Need to figure out which other strategies would benefit from this.

/kind feature

**Comment by JaneLiuL** [comment]
/assign 
I would like to have a try :)

**Comment by a7i** [comment]
Fixed in #639 

/close
