### ISSUE TITLE
[RFE] Support rescheduling with Pod status CreateContainerConfigError 

### ISSUE THREAD

**Issue by williamcaban** [kubernetes-sigs/descheduler#643]
**Is your feature request related to a problem? Please describe.**

When Pod get into error `CreateContainerConfigError`, even when using a Deployment, the Pod remains in that status until it is manually deleted and then the Pod is recreated in the cluster.

**Describe the solution you'd like**

To work around the "manually deleting the pod" to "fix" that type of error, having the option to trigger a descheduling event, will have the same effect and the normal remediations to recreate the Pod will start.

**Comment by damemi** [comment]
I think this will be similar to https://github.com/kubernetes-sigs/descheduler/issues/580. How is the `CreateContainerConfigError` determined? Since it's not an "actual" pod status, we need to look into the code to find out what interpretations of container statuses trigger that error

**Comment by ingvagabund** [comment]
@williamcaban could you please provide a reproduce for making a pod end up with CreateContainerConfigError error? It will be useful for understanding of how to properly recognize this state. Also for writing a test in case the feature gets implemented.
