### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by kunshen1** [kubernetes-sigs/descheduler#647]
My go version is 1.16
Once I make the file, it reports the issue:

go: inconsistent vendoring in /root/descheduler:
        golang.org/dl@v0.0.0-20211007222857-6589945b0d11: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

Can any one give me the suggestion about how to solve it? Thanks :)

**Comment by damemi** [comment]
Could you provide some more information? What branch are you building from, have you pulled the latest from that branch, etc. Also please post the full output of the command you are running, for example when I run `make` I get no problems:
```
$ make
CGO_ENABLED=0 go build -ldflags "-X sigs.k8s.io/descheduler/pkg/version.version=v20211015-v0.22.0-16-g50f9513cb -X sigs.k8s.io/descheduler/pkg/version.buildDate=2021-10-15T09:45:37-0400 -X sigs.k8s.io/descheduler/pkg/version.gitbranch= -X sigs.k8s.io/descheduler/pkg/version.gitsha1=50f9513cbb3a0eee4e6134ba09aaa7e9a4a09add" -o _output/bin/descheduler sigs.k8s.io/descheduler/cmd/descheduler
```

You may want to try clearing your go mod cache as well
