### ISSUE TITLE
livenessProbe

### ISSUE THREAD

**Issue by gabegorelick** [kubernetes-sigs/descheduler#652]
**Is your feature request related to a problem? Please describe.**

Descheduler doesn't specify a livenessProbe on its containers. This means that it could theoretically hang in such a way that the container is still running but not actually working. I have no idea if this is actually possible, but I thought I would raise it for discussion. 

**Describe the solution you'd like**

Add a livenessProbe to container manifests.

**Describe alternatives you've considered**

Closing this issue with an explanation as to why a livenessProbe is overkill is totally fine.

**What version of descheduler are you using?**

descheduler version: v0.22.1

**Additional context**

A lot of Kubernetes linters will flag missing livenessProbes, which means extra work when deploying Descheduler in a cluster with (arguably overzealous) admission requirements.

**Comment by damemi** [comment]
@gabegorelick that's a good question. We don't have any health endpoints implemented in the descheduler, so unless there is a generic endpoint we could use then we'll have to add one of those too

**Comment by ingvagabund** [comment]
+1 for the liveness probe. From https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/:
```
The kubelet uses liveness probes to know when to restart a container. For example, liveness probes could catch a deadlock, where an application is running, but unable to make progress. Restarting a container in such a state can help to make the application more available despite bugs.
```

The descheduler has a descheduling [loop](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/descheduler.go#L117) running every DeschedulingInterval seconds. Would be great to take that into account verifying the last time from the last loop was at most DeschedulingInterval ago + time it takes to run all the strategies. Nevertheless, to at least make sure the binary is not hanging, we may provide a simple ping liveness probe. E.g. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go#L42-L55.

**Comment by a7i** [comment]
@JaneLiuL are you still working on this? I have an immediate need to get this into the next release and can submit a PR within a day.

**Comment by JaneLiuL** [comment]
So sorry I forget it, already submit a PR.

**Comment by seanmalloy** [comment]
This was completed in #685.

/close
