### ISSUE TITLE
Limit the maximum number of pods to be evicted per Namespace

### ISSUE THREAD

**Issue by tmrekk121** [kubernetes-sigs/descheduler#656]
**Is your feature request related to a problem? Please describe.**

Descheduler has a policy called `maxNoOfPodsToEvictPerNode` that allows you to limit the maximum number of pods to evict per node.
It would be nice to be able to set the maximum number of pods to evict per Namespace.
**Describe the solution you'd like**

Add `maxNoOfPodsToEvictPerNamespace` policy.

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version: v0.22.1 (built from master)

**Additional context**

**Comment by ingvagabund** [comment]
+1, simply to implement, we already have a limit for a maximum number of evictions per node.

**Comment by ingvagabund** [comment]
Resolved through https://github.com/kubernetes-sigs/descheduler/pull/658
/close
