### ISSUE TITLE
Adding "affinity" value

### ISSUE THREAD

**Issue by martin-magakian** [kubernetes-sigs/descheduler#659]
**Is your feature request related to a problem? Please describe.**
I would like to run `descheduler` preferably on "spot instance".
To do that I need to leverage Kubernetes `affinity`.

**Describe the solution you'd like**
Updating the `Deployment` to use a `affinity` variable.
This is pretty common: [exemple1](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L221), [exemple2](https://github.com/cilium/cilium/blob/dc40b2cbe0468aa7389cdafa6c0ae0387f165eb8/install/kubernetes/cilium/values.yaml#L92), [exemple3](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml#L70)

**Describe alternatives you've considered**
Running "ondemand" only.

**What version of descheduler are you using?**
`1.10.3`

**Additional context**
Fixing proposal: https://github.com/kubernetes-sigs/descheduler/pull/660
Fixes #659

**Comment by seanmalloy** [comment]
Implemented by #660

/close
