### ISSUE TITLE
can't delete failed pod (STATUS : TopologyAffinityError)

### ISSUE THREAD

**Issue by ryudwig** [kubernetes-sigs/descheduler#669]
**What version of descheduler are you using?**

descheduler version: v0.22.1

**Does this issue reproduce with the latest release?**

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5ab7b2b", GitTreeState:"clean", BuildDate:"2021-04-30T00:27:01Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-1085+01c9f3f43ffcf0-dirty", GitCommit:"01c9f3f43ffcf096c29d51f3b6f2b6914b2b56a6", GitTreeState:"dirty", BuildDate:"2021-07-02T12:28:26Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**
I installed descheduler on cronjob. I would like to delete failed pod (STATUS : TopologyAffinityError)
I could get list with kubectl command
---------------------------------------------
$ kubectl get pod -A --field-selector="status.phase==Failed"

NAMESPACE   NAME                           READY   STATUS                  RESTARTS   AGE
wp-ade      gd-bid-normal-5657cf9d-22nj5   0/2     TopologyAffinityError   0          4h47m
wp-ade      gd-bid-normal-5657cf9d-22pt9   0/2     TopologyAffinityError   0          4h47m

so, I wrote configmap.
--------------------------------
descheduler-policy-configmap

apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveFailedPods":
        enabled: true
        params:
          failedPods:
            reasons: 
              - "TopologyAffinityError"
            includingInitContainers: true
            excludeOwnerKinds:
            - "Job"
            minPodLifetimeSeconds: 180

If you check the log, you can see that it has not been deleted. 
It was the same even after changing the reason value to "Failed".
------------------------------------------------------------------------
I1208 14:00:06.916575       1 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1638972006\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1638972006\" (2021-12-08 13:00:06 +0000 UTC to 2022-12-08 13:00:06 +0000 UTC (now=2021-12-08 14:00:06.916542039 +0000 UTC))"
I1208 14:00:06.916652       1 secure_serving.go:195] Serving securely on [::]:10258
I1208 14:00:06.916766       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I1208 14:00:06.928708       1 node.go:46] "Node lister returned empty list, now fetch directly"
...
I1208 14:00:07.197602       1 failedpods.go:50] "Processing node" node="tex-stg-worker-01.tex-stg.c.widerlab.io"
...
I1208 14:00:07.966961       1 descheduler.go:152] "Number of evicted pods" totalEvicted=0

**What did you expect to see?**
I would like to delete failed pod (STATUS : TopologyAffinityError)

**What did you see instead?**

**Comment by ryudwig** [comment]
Do you need more information?

**Comment by damemi** [comment]
Hi @ryudwig, sorry this slipped off my radar. Could you post the full yaml of the failed pods, ie `kubectl get -o yaml pod/wp-ade gd-bid-normal-...`?

**Comment by ryudwig** [comment]
> Thank you for your interest @damemi 

[pod.txt](https://github.com/kubernetes-sigs/descheduler/files/7763032/pod.txt)

**Comment by JaneLiuL** [comment]
@ryudwig  i do run descheduler as your config, and can delete fail pods, could you show me more logs?
including it should have node numbers , could you try `kubectl get nodes -o wide` and show me?
