### ISSUE TITLE
Too slow to list pods when cluster is huge

### ISSUE THREAD

**Issue by Garrybest** [kubernetes-sigs/descheduler#671]
**Is your feature request related to a problem? Please describe.**

It always appears becase the way we list pods is not reasonable. See [here](https://github.com/kubernetes-sigs/descheduler/blob/49ad197dfcc96f5c06c86c192899dd339814a3b4/pkg/descheduler/pod/pods.go#L81-L166). We list pods on a node by field selector while it means the descheduler counts on `kube-apiserver` to get the pods on each node. 

**Describe the solution you'd like**

When the cluster is large scale, like 3k+ nodes and 90k+ pods. The descheduler is not able to work because every interval it will request `kube-apiserver` for almost 30k+ times(enable 10 plugins and every plugins request for 3k+ times) with a `FieldSelector`. Meanwhile, it leads to a lot of pressure for `kube-apiserver`.

Now I have a very simple idea to fix this problem. We could new a `PodInformer` to establish a cache for all pods. And then we use an informer [indexer](https://github.com/kubernetes-sigs/descheduler/blob/master/vendor/k8s.io/client-go/tools/cache/index.go#L35-L57) to establish a relationship between the pods and their assigned nodes. So we could easily get the pods that assigned to a node and the action is very cheap and quick.

**Describe alternatives you've considered**

Well, I think this solution is the best way to fix this problem. It makes descheduler work normally in a large scale cluster.

**What version of descheduler are you using?**

descheduler version: v0.22.1

**Additional context**

**Comment by Garrybest** [comment]
I'm glad to make a contribution if it is considered as a significant problem.

**Comment by damemi** [comment]
Hey @Garrybest, sure feel free to open a PR to improve this. I think there are a couple reasons for this function, including that we want to use a field selector to exclude certain pods and we want a fresh cache for each call anyway. But these are probably both doable with an informer.

As a side note, it would be great if we could get some perf-scale tests to measure the improvement. If we can definitively say "this provides X% speedup" that would be awesome

**Comment by Garrybest** [comment]
Hi @damemi, thanks for your suggestion. 

> I think there are a couple reasons for this function, including that we want to use a field selector to exclude certain pods and we want a fresh cache for each call anyway. But these are probably both doable with an informer.

Agree, and I decide to use a pod filter function with a pod informer to replace the field selector and we could also exclude any pods we don't want.

> As a side note, it would be great if we could get some perf-scale tests to measure the improvement. If we can definitively say "this provides X% speedup" that would be awesome.

Right! That would be convincing. But it may be a little hard to make a test because the perf data is based on how busy, what scale  the cluster is and how many request the `kube-apiserver` receive in that time. Let me think about it.

I will open a new PR to fix this problem ASAP. And it theoretically has a good improvement by using pod informer. After that I will try to measure the improvement as much as possible. 😉

**Comment by a7i** [comment]
Will this work for CronJob/Job or just the Deployment approach?

**Comment by Garrybest** [comment]
The test result is shown in https://github.com/kubernetes-sigs/descheduler/pull/673#issuecomment-993115438.
