### ISSUE TITLE
Allow logs to go to stdout

### ISSUE THREAD

**Issue by hlascelles** [kubernetes-sigs/descheduler#676]
At present, logs go to `stderr`. For Datadog, this means they show up as Errors.

See https://docs.datadoghq.com/agent/docker/log/?tab=containerinstallation (screenshot below).

It would be good to be able to log to `stdout` natively in descheduler.

descheduler version: 0.22.1
descheduler chart version: 0.22.1

![image](https://user-images.githubusercontent.com/299102/145976352-73fee7d6-eb47-47e4-874f-717714b4fb6f.png)

In action:

![image](https://user-images.githubusercontent.com/299102/145976671-72aecb5e-86a2-4c57-b15a-824383a02c5c.png)

**Comment by damemi** [comment]
cc @ingvagabund

**Comment by ingvagabund** [comment]
Checking https://github.com/kubernetes/klog/blob/main/klog.go there's no option for klog to write into stdout.

**Comment by ingvagabund** [comment]
@hlascelles how does the datadog consumes the data? Parsing container's stdout/stderr?

**Comment by damemi** [comment]
Just curious, what are we doing with this: https://github.com/kubernetes-sigs/descheduler/blob/e6314d2/cmd/descheduler/descheduler.go#L32

Which passes to this:
https://github.com/damemi/descheduler/blob/94888e653c6f8d0554f251256cd1dd9eafea4368/cmd/descheduler/app/server.go#L81

Seems like we are trying to specify the output as Stdout, but is that not respected anymore? It seems really odd that klog would not allow stdout

**Comment by ingvagabund** [comment]
Based on https://github.com/spf13/cobra/blob/master/command.go#L247-L251:
```
// SetOut sets the destination for usage messages.
// If newOut is nil, os.Stdout is used.
func (c *Command) SetOut(newOut io.Writer) {
```
So only for the usage text.

**Comment by hlascelles** [comment]
@ingvagabund Yes, as I understand it the ageent just streams the STDOUT and STDERR to the Datadog servers. 

I have searched their docs (and the agent config) on a way to override the level, but I cannot find a way.

**Comment by ingvagabund** [comment]
@hlascelles any way to verify the fix in https://github.com/kubernetes-sigs/descheduler/pull/680 by building a container and having the datadog collects the logs?

**Comment by hlascelles** [comment]
I will have a look. In the meantime I see that Wordpress docker has the same issue: https://github.com/docker-library/wordpress/issues/311#issuecomment-395514485

**Comment by hlascelles** [comment]
I am seeing:
```
docker build -t descheduler-fix . 
=>
Step 6/11 : RUN VERSION=${VERSION} make build.$ARCH
 ---> Running in 2c81f13f89a0
make: *** No rule to make target 'build.'.  Stop.
```

**Comment by hlascelles** [comment]
I was never able to test this because of the build error above, sorry.  I will try the new build.

Also, for the record, here is how (in Datadog) to change any stream with the first char as I,E,W to the correct status:

```
You will have to add a new Pipeline (go to Logs -> Configuration). Click on add a new pipeline, give it a name and click on create. Next, you will have to click on add processor for this pipeline and select grok parser. Set the following parsing rule:

level_rule %{regex("[IWEiwe]"):level}.*

Click on create button. This should now assign level attribute to your logs. Next, add another processor and select Status Remapper, and type level as the attribute, and click on create.
```

**Comment by damemi** [comment]
That is weird, I get the same error running `docker build` directly. However, running `make image` (which does a docker build) works for me. @hlascelles could you try `make image` instead?

**Comment by tamir-allc** [comment]
for some reason it still reproduces (Datadog user as well) on v0.23.1 and even v0.24.0.

**Comment by jmk47912204** [comment]
Hey Everyone, 

Is there a way to fix this [issue](https://github.com/kubernetes-sigs/descheduler/issues/676#issue-1079550906) from descheduler itself rather than having [workaround](https://github.com/kubernetes-sigs/descheduler/issues/676#issuecomment-1013178391) on the datadog level? 

Thank you

**Comment by hlascelles** [comment]
I've never found one. I've also found many other k8s utilities work in the same way. I've just added lots of Datadog parsing rules.
