### ISSUE TITLE
How to impletement custom strategy for descheduler?

### ISSUE THREAD

**Issue by Thor-wl** [kubernetes-sigs/descheduler#686]
Hi. I've impletemented my custom strategies for business use. But it is not so convient to submit it to the community. Is there some interfaces or guidence to reuse descheduler, just like the relationship between scheduler framework and custom plugins? I just want to maintain my own strategy repository without forking descheduler repository.

**Comment by damemi** [comment]
Hi @Thor-wl, there's been some discussion about designing a "descheduler framework" similar to the scheduler's (for example, in https://github.com/kubernetes-sigs/descheduler/issues/679)

It's not very well documented (intentionally) but some of the design decisions we have made in the descheduler were intended to make it easier to add new strategies similar to a hack-y framework. For example, standardizing the strategy function signatures so they can all be added to a registry like so https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/descheduler.go#L83-L94

The descheduler is not as complicated as the scheduler, so it should be relatively doable to implement your own strategies without a specifically defined framework. It just comes down to following the patterns of the existing strategies, as above. Hope this helps

**Comment by Thor-wl** [comment]
Thanks, damemi. @damemi
