### ISSUE TITLE
Evicting pods is too deterministic

### ISSUE THREAD

**Issue by HitkoDev** [kubernetes-sigs/descheduler#690]
**Is your feature request related to a problem? Please describe.**

Consider having the following pods (all pods have the same priority and QoS class):
```
bar-cchwg
bar-fkpbw
bar-ictdt
bar-oanma
bar-ypagq
foo-goiou
foo-pclma
foo-vzxpc
foo-wozdq
foo-yxgfx
```

Since they share the same priority and QoS class, descheduler will always evict them in the same (alphabetical) order (`bar` before `foo`). This behaviour implicitly gives pods a secondary "priority" based on name, and causes `bar` pods to be evicted over and over while `foo` pods never get evicted despite having the same priority. It also causes all pods belonging to the same group to be evicted together instead of evicting pods across all groups with the same priority.

**Describe the solution you'd like**

Pods with the same priority and QoS class should have the same probability of being evicted.

**Describe alternatives you've considered**

Changing priority or QoS class doesn't help, since pods within the same group still get evicted in deterministic order.

**What version of descheduler are you using?**

descheduler version: 0.22.1

**Comment by lianghao208** [comment]
Pods with the same priority and QoS class should be evicted in:
1. creation timestamp order (the older pods are more likely to be evicted)
2. random order
I wonder which order is better.

**Comment by maartengo** [comment]
Edit: I meant option 1 😄

**Comment by HitkoDev** [comment]
Option 1 doesn't really solve the problem imo, since most of the time all `foo` pods will have one timestamps, and all `bar` pods will have another timestamp. Descheduler will therefore still evict all pods from one group before starting to evict pods from the other group.

The only improvement option 1 has over the current implementation is that it will *eventually* get to all pods, whereas the current implementation keeps evicting the same pods over and over.

**Comment by lianghao208** [comment]
> Descheduler will therefore still evict all pods from one group before starting to evict pods from the other group.

Option 1 can prevent the same pods being evicted over and over. Because pods `bar` will be newer than pods `foo` after the eviction.

**Comment by damemi** [comment]
I think adding timestamp as another sorting criteria will help this. We did something similar for kube-controller-manager to add pseudo-random selection for scaling down replica sets as well, so there is some precedent for it

**Comment by HitkoDev** [comment]
> > Descheduler will therefore still evict all pods from one group before starting to evict pods from the other group.
> 
> Option 1 can prevent the same pods from being evicted over and over. Because pods `bar` will be newer than pods `foo` after the eviction.

Yes, but it can't prevent all pods of the same type from being evicted at the same time, so that's still a significant issue.

**Comment by HitkoDev** [comment]
> I think adding timestamp as another sorting criteria will help this. We did something similar for kube-controller-manager to add pseudo-random selection for scaling down replica sets as well, so there is some precedent for it

That's a valid solution for downscaling as downscaling will preserve at least the desired number of pods in a replica set. The problem with using it for descheduler is that it will in some cases lead to evicting all pods from a single replica set instead of evicting pods across different replica set to preserve service availability.

**Comment by damemi** [comment]
> The problem with using it for descheduler is that it will in some cases lead to evicting all pods from a single replica set instead of evicting pods across different replica set to preserve service availability.

That sounds like what is currently the issue too though, isn't it? If so, this isn't a regression (not sure if that's the point you were making, or just pointing out the ineffectiveness)

I don't think we should provide randomness as a method for descheduling. Evicting pods should usually have some level of predictability in order to maintain availability. Timestamp provides a pseudo-random ordering that is still predictable.

I also don't think it's inherent that sorting by timestamp will always prefer the pods from one replica set over another. ReplicaSets can be created at near the same time as each other and their pods may have overlapping timestamps because of that.

**Comment by HitkoDev** [comment]
> That sounds like what is currently the issue too though, isn't it? If so, this isn't a regression (not sure if that's the point you were making, or just pointing out the ineffectiveness)

It's not a regression, but it's not a solution to this issue either, because it still evicts pods based on some very much deterministic grouping and prioritises one group over another. The goal of this issue, as stated, is:

**Pods with the same priority and QoS class should have the same probability of being evicted.**

> I don't think we should provide randomness as a method for descheduling. Evicting pods should usually have some level of predictability in order to maintain availability. Timestamp provides a pseudo-random ordering that is still predictable.

I disagree. Randomness has been proven over and over to be the simplest, most effective way of balancing things out, and has been used for this exact purpose in several algorithms. One such example is quicksort, which often uses randomness for pivot selection to deal with "malformed" inputs like sorted arrays, and arrays of identical values, which is pretty close to the issue here (array of pods with identical priority).

And please don't say that timestamps in this context are pseudo-random. They're closely corelated with deploys and other cluster actions, and since those actions aren't even remotely random, neither are the timestamps.

> I also don't think it's inherent that sorting by timestamp will always prefer the pods from one replica set over another. ReplicaSets can be created at near the same time as each other and their pods may have overlapping timestamps because of that.

The only time you deploy and update everything on a cluster at the same time is when you create it. On each subsequent deploy, some replica sets will change and some won't. More often than not only one or two replica sets will change, unless you bump all image versions on each update. After a couple such updates, each replica set will have a distinct timestamp. Yeah it's not inherent, but it's almost guaranteed to happen over time.

**Comment by damemi** [comment]
I do understand the use case for a random selection, but my concern is the effect this change may have on existing workflows that assume a level of determinism. Being able to predict (and more importantly, reproduce) which pods will be evicted can be very important to some environments that prioritize their own service availability to varying degrees. It's especially important in debugging. This is why there aren't many implementations of truly random choice in Kubernetes that I'm aware of.

I'm not saying that alphabetical sorting is the best way to achieve this. Far from it, it's more likely this was just an oversight that has stuck around. But it is, unfortunately, the current behavior in the system, and [Hyrum's law](https://www.hyrumslaw.com/) says it's reasonable to assume that someone may be depending on it somewhere. So we need to respect that use case as well.

I think that there is an opportunity for improvement here though. Maybe a feature flag like `RandomChoiceEviction` that turns this on would be very useful. We could even expand on that with a richer `EvictionSort` field that provides different options for tiebreaker sorting: `name` (default), `age`, `random`, etc. At some point users may even be able to define their own. @HitkoDev do you think either of those options are feasible?

As a side note, a simple random sort might not be as effective as intended. It's still just as likely that the same pod could get chosen first, for example. If you ran the descheduler with random choice eviction and the same pod was evicted three times in a row, that sounds like it would not be satisfactory to resolve your problem. Additional weighting such as timestamps can help make the choices appear more random. (There's actually a cool blog from [Spotify](https://engineering.atspotify.com/2014/02/how-to-shuffle-songs/) about this problem which we could maybe draw some ideas from for this)

I do agree with the original issue here, that just relying on alphabetical sort of the pod names is not a great tiebreaker. Getting past that we just need to decide on an implementation approach.

**Comment by HitkoDev** [comment]
> I do understand the use case for a random selection, but my concern is the effect this change may have on existing workflows that assume a level of determinism. Being able to predict (and more importantly, reproduce) which pods will be evicted can be very important to some environments that prioritize their own service availability to varying degrees. It's especially important in debugging. This is why there aren't many implementations of truly random choice in Kubernetes that I'm aware of.

While almost no component in k8s is random by design, they generally behave a lot like differential equations under chaos theory. A small fluctuation in memory or CPU requests can be enough to schedule a pod on a different node, which changes score for subsequent scheduling, different pod distribution affects load balancing for services and resource allocation, and creates an unpredictable feedback loop. Pods from replica sets receive random name suffixes, which already affects descheduler order when two such pods are on the same node, and so on.

I'm all for supporting deterministic behaviour and backwards compatibility. Timestamps just aren't a good way of doing it, because then every deploy, update, or other cluster action has a side-effect of changing eviction order for descheduler. You could argue descheduler behaviour would still be deterministic (oldest first), but there's no way anyone would be able to keep track of which pod should be the oldest at some point and why.

That's why, given how many non-deterministc factors there already are, adding some "true" randomness to evictions would just fully embrace that idea and solve the problem of evicting the same pods over and over (I tested it on a few k8s clusters and it resulted in nodes being as close to ideally balanced as possible). Of course adding `EvictionSort` or `EvictionStrategy` would be a much more complete solution, as it would allow users to explicitly set the desired behaviour, and I'm all for that. As an option, `oldest-first` might actually be a good fit for some use cases where things are seldom updated.

If there are 25 candidate pods on a node, and descheduler randomly evicts 3 pods every 5 minutes, then one specific pod would be evicted 3 times in a row about once every 2 days. That's assuming the worst case scenario where all evicted pods are rescheduled on the same node, and descheduler keeps evicting them with no possibility of achieving a balanced cluster.

Under the same conditions, if a replica set has 3 pods, then the possibility of randomly evicting all 3 of those pods at the same time is about once per 8.75 days. If pods were evicted oldest first, then all 3 pods belonging to the same replica set would be evicted either every 2 hours, or never, with "expected value" being once every 7.90 days. So random eviction is 10% less likely to evict an entire replica set at the same time than the oldest-first approach.

> I do agree with the original issue here, that just relying on alphabetical sort of the pod names is not a great tiebreaker.

That's only half the issue. We need to be able to evict pods strictly based on the configured properties (priority and QoS), not based on some other implicit property, unless that property is explicitly configured to be a tiebreaker.

That being said, a good solution would be to add `EvictionStrategy` with the following options:

- `alphabetical` (current behaviour, default)
- `none` (no tiebreaker, random)
- `oldest-first`
- possibly other if it makes sense, e.g. `newest-first`, `resource-utilisation`, `round-robin` (one from each replica set), ...

**Comment by lianghao208** [comment]
> That being said, a good solution would be to add `EvictionStrategy` with the following options:
> 
> * `alphabetical` (current behaviour, default)
> * `none` (no tiebreaker, random)
> * `oldest-first`
> * possibly other if it makes sense, e.g. `newest-first`, `resource-utilisation`, `round-robin` (one from each replica set), ...

Adding a feature flag `--eviction-strategy` makes sense to me. @damemi WDYT? If we reach an agreement on this solution,
I would like to finish implementing the `alphabetical`, `none` and `oldest-first` options first.

**Comment by damemi** [comment]
@lianghao208 yeah I think that's a good idea. Though I misspoke calling it a flag, we have been moving away from `--feature-flag`s to policy fields in the config API. But the same idea applies, a field in the policy that accepts enumerated options

@ingvagabund @seanmalloy wdyt?

**Comment by lianghao208** [comment]
@damemi 
If we add a `EvictionStrategy` in policy fields, will it be an individual strategy(e.g. `DeschedulerPolicy.EvictionStrategy`) or one of the`DeschedulerPolicy.DeschedulerStrategy`?

IMO, an individual strategy like `DeschedulerPolicy.EvictionStrategy` seems better. Because strategies in `DeschedulerPolicy.DeschedulerStrategy` evicts pods in their implementations, and `EvictionStrategy` only determines pods order after listing.

**Comment by ingvagabund** [comment]
I will respond only to the part discussing how we can facilitate eviction "strategies". Given sooner or later we will probably get aligned with the scheduling framework and introduce "plugins" for descheduling strategies, I am inclined into implementing eviction strategies as an `eviction-sort` extension point the same way as the scheduling framework does for the [queue-sort](https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/#queue-sort). That way we can provide a default "plugin" for the `eviction-sort` and have any consumer to customize the descheduler with either public or private implementation taken into account various ways of sorting pods before eviction.

@HitkoDev I wonder what's your thought on implementing this feature later as part of here-called "descheduling framework" effort?

**Comment by lianghao208** [comment]
> I will respond only to the part discussing how we can facilitate eviction "strategies". Given sooner or later we will probably get aligned with the scheduling framework and introduce "plugins" for descheduling strategies, I am inclined into implementing eviction strategies as an `eviction-sort` extension point the same way as the scheduling framework does for the [queue-sort](https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/#queue-sort). That way we can provide a default "plugin" for the `eviction-sort` and have any consumer to customize the descheduler with either public or private implementation taken into account various ways of sorting pods before eviction.

@ingvagabund Will there be an individual repo such as "descheduler-plugin" introduced eventually when the "descheduling framework" has been finished? Like the [scheduler-plugin](https://github.com/kubernetes-sigs/scheduler-plugins).

**Comment by ingvagabund** [comment]
That is to be discussed

**Comment by HitkoDev** [comment]
@ingvagabund I think there are two ways this could work:
- plugin receives all pods and sorts them accordingly
- descheduler sorts all pods by priority & QoS, then plugins take care of pods within each group

I think the first case is "cleaner" and enables more flexibility, however, I imagine most plugins would still sort pods by priority & QoS first.

I wonder how descheduling framework would work with (cron) jobs though. Right now I have a special descheduler job which runs after node is added / removed, and I'm not sure how it would be possible to achieve the same behaviour with something similar to scheduling framework.
