### ISSUE TITLE
Proposal: Fail Fast Validation

### ISSUE THREAD

**Issue by jklaw90** [kubernetes-sigs/descheduler#701]
**Is your feature request related to a problem? Please describe.**
Currently a misconfiguration per strategy would allow descheduler to run with just an error log line every iteration. It may be preferable to fail early, rather than throwing throwing error logs. We won't notice there is a misconfiguration without looking at logs, it'll start and just throw error logs every iteration.

**Describe the solution you'd like**
I think we should change our strategy to an interface like
```go
// what we currently have
type strategyFunction func(ctx context.Context, client clientset.Interface, strategy api.DeschedulerStrategy, nodes []*v1.Node, podEvictor *evictions.PodEvictor, getPodsAssignedToNode podutil.GetPodsAssignedToNodeFunc)

// proposed interface
type Strategy interface {
    Name() string
    Enabled() bool
    Validate(ctx context.Context) error
    Run func(ctx context.Context, nodes []*v1.Node, podEvictor *evictions.PodEvictor, getPodsAssignedToNode podutil.GetPodsAssignedToNodeFunc)
}

// Example
type StrategyX struct {
    client clientset.Interface,
    strategy api.DeschedulerStrategy
}
func NewStrategyX(client clientset.Interface, strategy api.DeschedulerStrategy) Strategy {}
func (s *StrategyX) Name() string
func (s *StrategyX) Enabled() bool
func (s *StrategyX) Validate() error {}
func (s *StrategyX) Run(ctx context.Context, nodes []*v1.Node, podEvictor *evictions.PodEvictor, getPodsAssignedToNode podutil.GetPodsAssignedToNodeFunc) {}


// Example of how our loop can look
...
strategyList := []Strategy{
    strategies.NewStrategyX(rs.Client, strategyConfig),
}
...
// VALIDATE
var configErrors []errors
for _, strategy := range strategyList {
    if err := strategy.Validate(); err != nil {
        klog.Errors(err, "strategy config error")
        configErrors = append(configErrors, err)
    }
}
// FAIL early before we start the loop.
if len(configErrors > 0 {
   return errors.New("invalid descheduler configuration")
}
...
// our usual loop
wait.NonSlidingUntil(func() {
    for _, strategy := range strategyList {
        if strategy.Enabled() {
	    strategy.Run(ctx, nodes, podEvictor, getPodsAssignedToNode)
        } else {
	    klog.Debug("skipping strategy", "strategy", strategy.Name())
        }
    }
},  rs.DeschedulingInterval, stopChannel)
```
We will be able to validate all strategy configs and bail before starting our loop. It should be pretty clear to the operator that something is wrong when their deployment isn't running and jobs would fail. 

**Describe alternatives you've considered**

We could have metrics based on the failures per strategy for failed configs, but that seems like more of an operational burden for something as simple as a bad config.

**What version of descheduler are you using?**

descheduler version: v0.22.1

**Additional context**
I can implement this today or tomorrow if we agree on it.

**Comment by damemi** [comment]
Sounds good, I've been thinking we should move to an interface implementation for this kind of thing for a while. Will follow the PR, let us know when it's ready for review!

**Comment by andyli** [comment]
Is there a schema available somewhere right now?

I wanted descheduler to only touch namespace `default`, and it is now killing pods in `kube-system` and `database` etc. with the config as follows:

```yaml
deschedulerPolicy:
  strategies:
    LowNodeUtilization:
      params:
        namespaces:
          include:
          - default
        nodeFit: true
        nodeResourceUtilizationThresholds:
          targetThresholds:
            cpu: 85
            memory: 85
            pods: 85
          thresholds:
            cpu: 60
            memory: 60
            pods: 60
```

It's very confusing because in the README.md, the params of `RemoveDuplicates` are under `params.removeDuplicates`. But for `RemovePodsViolatingNodeAffinity`, the params are right under `params`. Not to mention many examples show no `params`.

**Comment by damemi** [comment]
@andyli the current config API schema is defined in https://github.com/kubernetes-sigs/descheduler/blob/1529180/pkg/api/v1alpha1/types.go

However, Namespace filtering is not supported for LowNodeUtilization (see https://github.com/kubernetes-sigs/descheduler#namespace-filtering). There is some lengthy discussion and explanation for this in https://github.com/kubernetes-sigs/descheduler/issues/391 (tl;dr is that LNU inherently works by considering resource usage for the entire node and it will not be as effective or predictable when limited to namespaces, as well as there being better options for namespace-specific balancing to achieve the same effect).

**Comment by damemi** [comment]
/remove-lifecycle stale
see https://github.com/kubernetes-sigs/descheduler/issues/753#issuecomment-1116043835
