### ISSUE TITLE
Kubernetes 1.24 Release Timeline

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#735]
From https://github.com/kubernetes/sig-release/blob/master/releases/release-1.24/README.md

The 1.24 release cycle is as follows:

- **Monday 10th January 2022**: Week 1 — Release cycle begins
- **Thursday 27th January 2022**: Week 3 — [Production Readiness Soft Freeze](https://groups.google.com/g/kubernetes-sig-architecture/c/a6_y81N49aQ)
- **02:00 UTC Friday 4th February 2022**: Week 4 — [Enhancements Freeze](../release_phases.md#enhancements-freeze)
- **Wednesday 23rd March 2022**: Week 11 — [Release Retrospective][Retrospective Document] part 1
- **01:00 UTC Wednesday 30th March 2022**: Week 12 — [Code Freeze](../release_phases.md#code-freeze)
- **Tuesday 19th April 2022**: Week 15 — Kubernetes v1.24.0 released

We will try to release the v0.24 Descheduler soon after Kubernetes 1.24 is released

---

Steps for Descheduler release:

- [x] **Bump `k8s.io` dependencies to `rc` post code freeze/prior to 1.24 release**
  - (ex https://github.com/kubernetes-sigs/descheduler/pull/539) (nice to have)
- [x] **Bump `k8s.io` dependencies to GA 1.24 post release** @JaneLiuL 
  - (ex https://github.com/kubernetes-sigs/descheduler/pull/615)
- [x] **Add release-1.24 branch tests and update old branch tests in k8s.io/test-infra** @pravarag (https://github.com/kubernetes/test-infra/pull/25833)
- [x] **Update version references in docs/readme/compatibility matrix** @pravarag 
  - (ex https://github.com/kubernetes-sigs/descheduler/pull/617)
- [x] * **Tag `v0.24` from `master`** @damemi
- [x] * **Update Helm chart** @JaneLiuL 
  - (ex https://github.com/kubernetes-sigs/descheduler/pull/709)
- [x] * **Cut `release-1.24` branch** @damemi
- [x] **Promote image from tagged branch commit** 
  - (ex https://github.com/kubernetes/k8s.io/pull/3344)
- [x] **Publish release** @damemi

* Note that to try addressing https://github.com/kubernetes-sigs/descheduler/issues/736, we will create the `v0.24` Git tag before cutting the release branch. But, in order for the automated Helm chart release action to work, it must detect some changes since the most recent tag. So, we will update the Helm chart after creating the tag but *before* creating the `release-*` branch, which is what triggers the automated Helm release action (see https://github.com/kubernetes-sigs/descheduler/blob/master/docs/release-guide.md#notes). Doing this will give us a `v0.24`-tagged SHA to promote from staging to the public image.

**Comment by JaneLiuL** [comment]
great! so may i ask that do i need to close the https://github.com/kubernetes-sigs/descheduler/pull/737?

**Comment by JaneLiuL** [comment]
can i have a try on update descheduler for k8s 1.24?

**Comment by pravarag** [comment]
@damemi I would also like to take part in 1.24 release upgrades for descheduler, be it via or documentation or bumping the file versions. Kindly let me know :)

**Comment by damemi** [comment]
@JaneLiuL I think you can close #737
I'll make a list of the tasks that need to be done, and folks can feel free to create and self-assign new issues for each one 🙂  it will be great to have some more hands working on the release, and there is a lot of steps involved!

**Comment by damemi** [comment]
Updated the original comment with a list of tasks, anyone please let me know if I missed anything. Otherwise, feel free to self-assign any particular tasks you're interested in.

**Comment by pravarag** [comment]
> Updated the original comment with a list of tasks, anyone please let me know if I missed anything. Otherwise, feel free to self-assign any particular tasks you're interested in.

Thanks for sharing the list of associated tasks. Wanted to check if the tasks are listed in the order of priority or all can be attempted once the code freeze happens for 1.24 release?

Also, I'd like to work on below two tasks if that's okay :) , 
```
[ ] Add release-1.24 branch tests and update old branch tests in k8s.io/test-infra
[ ] Update version references in docs/readme/compatibility matrix
```
@damemi

**Comment by damemi** [comment]
@pravarag updated with you on those tasks. I put the tasks in the general order that they should be done in. It's not too strict of an ordering (except for the tag/helm/branch part which is important to do in that order), so for most of them we can start whenever

**Comment by JaneLiuL** [comment]
@damemi  may i take below tasks ?
```
*  Bump k8s.io dependencies to rc post code freeze/prior to 1.24 release
* Update Helm chart
```

**Comment by damemi** [comment]
@JaneLiuL yup, added you to the main description

**Comment by pravarag** [comment]
@damemi for adding `1.24 release branch tests` we'll be removing [1.21](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml#L116) tests right and adding 1.24 tests? Like, does it support only upto 3 versions of K8s?

**Comment by damemi** [comment]
@pravarag yep, for the `master` and `release-1.24` branches we don't need the 1.21 tests, we only test the three latest minor versions https://github.com/kubernetes-sigs/descheduler#compatibility-matrix

**Comment by pravarag** [comment]
@damemi wnated to check, we'll be merging changes for Descheduler w.r.t K8s release 1.24, post 19th of April or I can start making changes now as well?

**Comment by pravarag** [comment]
@damemi I've opened the following PR here: https://github.com/kubernetes/test-infra/pull/25833

**Comment by JaneLiuL** [comment]
hi @damemi  sure~ i will doing an `rc` bump too :)

**Comment by damemi** [comment]
@JaneLiuL yeah the 1.24 release has hit some delays, see https://groups.google.com/a/kubernetes.io/g/dev/c/D0fGHU-9hKI

Also recommend subscribing to that group if anyone isn't already :)

**Comment by damemi** [comment]
Another update -- the 1.24 release is now delayed to May 3: https://groups.google.com/a/kubernetes.io/g/dev/c/9IZaUGVMnmo

**Comment by JaneLiuL** [comment]
Kubernetes v1.24.0-rc.0 has been release, but client-go or apiserver still don't release v1.24.0-rc.0 yet. i will waiting the client-go and apiserver release v1.24.0-rc.0  :)

**Comment by damemi** [comment]
@JaneLiuL thanks for the update! With the delays this release has been experiencing it's not totally surprising that there's hiccups with the client libraries too. No worries

**Comment by JaneLiuL** [comment]
:) open pr here for rc-0: https://github.com/kubernetes-sigs/descheduler/pull/787

**Comment by jklaw90** [comment]
will this pr make it in to 1.24 https://github.com/kubernetes-sigs/descheduler/pull/636

**Comment by damemi** [comment]
> will this pr make it in to 1.24 #636?

it will be tough, since that PR needs a rebase and there are still outstanding comments left on it. If @ingvagabund or @RyanDevlin are available to commit to addressing the last few nits then we can hold off the release for that PR

**Comment by jklaw90** [comment]
@damemi this issue is a very common in our clusters and we've been delaying increasing adoption of descheduler in our clusters because of it.  My concern is certain workloads like workers or slower booting services can really be impacted by this.

**Comment by ingvagabund** [comment]
Checking the #636 now

**Comment by JaneLiuL** [comment]
bump k8s to 1.24.0 pr here: https://github.com/kubernetes-sigs/descheduler/pull/791

**Comment by pravarag** [comment]
Added the following docs PR as well: #792

**Comment by JaneLiuL** [comment]
Update Helm chart pr: https://github.com/kubernetes-sigs/descheduler/pull/796

**Comment by damemi** [comment]
At this point I'd like to cut the `v0.24.0` git tag to start the final release process. Please let me know if there are any other changes that need to be merged into this release before that. Quickly reviewing the PRs that are open right now didn't show anything critical.

**Comment by damemi** [comment]
Tag created, and the images appear to be tagged with the right version now. Image promotion PR at https://github.com/kubernetes/k8s.io/pull/3739
