### ISSUE TITLE
Descheduler acting on nodes without label in nodeSelector

### ISSUE THREAD

**Issue by bwmetcalf** [kubernetes-sigs/descheduler#738]
We are using karpenter to provision capacity as needed and the descheduler to evict pods and tear down those nodes based on a `HighNodeUtilization` strategy.  We are also using `nodeSelector` so that the descheduler acts only on a subset of our nodes.  Our policy looks like
```
nodeSelector:
  karpenter.sh/provisioner-name: karpenter-provisioner
deschedulerPolicy:
  strategies:
    HighNodeUtilization:
      enabled: true
      params:
        nodeFit: true
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 30
            memory: 60
            pods: 75
```
However, the descheduler logs show it is trying to act on nodes that do not have this label
```I0223 19:40:57.676264       1 highnodeutilization.go:90] "Criteria for a node below target utilization" CPU=30 Mem=60 Pods=75
I0223 19:40:57.676274       1 highnodeutilization.go:91] "Number of underutilized nodes" totalNumber=2
I0223 19:40:57.676297       1 nodeutilization.go:223] "Total capacity to be moved" CPU=4500 Mem=34888605696 Pods=92
I0223 19:40:57.676310       1 nodeutilization.go:226] "Evicting pods from node" node="ip-10-3-141-88.us-west-2.compute.internal" usage=map[cpu:125m memory:0 pods:3]
I0223 19:40:57.676340       1 node.go:123] "Pod can possibly be scheduled on a different node" pod="gitlab-runner/runner-voaz8b2r-project-32000304-concurrent-1qrd6w" node="ip-10-3-132-203.us-west-2.compute.internal"
I0223 19:40:57.676399       1 nodeutilization.go:229] "Pods on node" node="ip-10-3-141-88.us-west-2.compute.internal" allPods=3 nonRemovablePods=3 removablePods=0
I0223 19:40:57.676406       1 nodeutilization.go:232] "No removable pods on node, try next node" node="ip-10-3-141-88.us-west-2.compute.internal"
```
Our gitlab runners run on nodes created by karpenter but by a different provisioner and therefore do not have the label indicated in our policy.  I have confirmed this.

Additionally, when the descheduler builds a list of nodes as indicated in the logs with
```
I0224 15:18:51.243243       1 node.go:46] "Node lister returned empty list, now fetch directly"
```
all of our nodes are listed regardless of whether or not the nodeSelector is satisfied.  This may be expected behavior, but seems suspect.

**Comment by bwmetcalf** [comment]
Here is more information showing the descheduler acting on nodes without the `nodeSelector` label:
```
I0224 15:38:51.269213       1 nodeutilization.go:226] "Evicting pods from node" node="ip-10-3-138-169.us-west-2.compute.internal" usage=map[cpu:125m memory:0 pods:2]
```
and output from `kubectl describe node`:
```
$ kubectl describe node ip-10-3-138-169.us-west-2.compute.internal|grep 'karpenter.sh/provisioner-name'
                    karpenter.sh/provisioner-name=gitlab-runner-provisioner-karpenter-provisioner
```

**Comment by damemi** [comment]
Thanks for the report @bwmetcalf, that does seem weird because the list of nodes passed to each strategy should be based on the labelSelector as set in ReadyNodes (https://github.com/kubernetes-sigs/descheduler/blob/54c50c53902c580f3752d5068fbfc18a252b43da/pkg/descheduler/node/node.go#L48)

Though I know the utilization strategies in particular have some limits on the ability to restrict nodes/pods, we'll have to check if that comes into play here.
/kind bug

**Comment by bwmetcalf** [comment]
I noticed the documentation here https://github.com/kubernetes-sigs/descheduler#policy-and-strategies for `nodeSelector` shows an example as
```
nodeSelector: prod=dev
```
but it's a map that should be passed in to the chart which is consistent with https://github.com/kubernetes-sigs/descheduler/blob/3ab0268c5aabdb487e0f6ec4d924511f0b8e38f9/charts/descheduler/values.yaml#L76.

Just pointing this out just in case there is something there.

**Comment by damemi** [comment]
@bwmetcalf that's interesting, are you deploying with the helm chart? Could you please share you descheduler policy config?

**Comment by bwmetcalf** [comment]
Yes, we are deploying with the helm chart and using `kind: Deployment`.

**Comment by damemi** [comment]
Maybe this is a mis-match between the type as defined in the chart and what's parsed by the node selector helpers.

Do you have any way to try deploying it manually to use the `label=value` format in your descheduler policy, and see if that shows the same behavior? You might be able to even just modify the policy configmap and kill the Pod if descheduler is already deployed

**Comment by bwmetcalf** [comment]
Editing the deployment "live" results in
```
error: deployments.apps "descheduler" is invalid
```
when trying to use `karpenter.sh/provisioner-name=karpenter-provisioner`.  It seems the docs are incorrect and this is a red herring.

**Comment by damemi** [comment]
Could you please paste the steps and full object for trying to make that change? It's odd that updating the policy configmap gave an error with the deployment

**Comment by bwmetcalf** [comment]
Ah.  That seems to be the problem.  After correcting this, the behavior seems to be correct.  Sorry for the confusion.  I will close this issue.

**Comment by damemi** [comment]
No worries! Glad we could resolve it. We should update the documentation to explain that better, it is confusing with 2 of those
