### ISSUE TITLE
Pods can't be evicted if one NodePool is tainted

### ISSUE THREAD

**Issue by prune998** [kubernetes-sigs/descheduler#752]
**What version of descheduler are you using?**

descheduler version: 0.22.0

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
all the defaults generated with 
```
kustomize build 'github.com/kubernetes-sigs/descheduler/kubernetes/job?ref=v0.22.0'
```

**Please provide a copy of your descheduler policy config file**
```
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 25
               "memory": 25
               "pods": 25
             targetThresholds:
               "cpu" : 50
               "memory": 50
               "pods": 50
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

I have an EKS cluster with two nodepool:
- a 3 node nodePool, not tainted, to run all my pods, managed by `cluster-autoscaler`, so that during my tests, the nodepool was using 3 nodes, with the latest only running daemonsets from base cluster needs.
- a 1 node nodePool specific to a project, tainted, and only running specific nodes with toleration. Node is almost empty.

out of the 3 nodes, one was a 99% CPU, the other around 60% and the last one around 20%, lower that the 25% threshold that I configured. 

I then run the `descheduler` job, to rebalance pods from nodes 1 and 2 to node 3 (as node 4 is tainted)

**What did you expect to see?**

I was expecting some pods rom nodes 1 and 2 to be deleted, and rescheduled on the node 3, to rebalance the cluster

**What did you see instead?**

Instead, no pod were evicted because of `Skipping eviction for pod, doesn't tolerate node taint`:

Here, 
node 1: `ip-10-254-25-28.us-west-2.compute.internal`
node 2: `ip-10-254-33-235.us-west-2.compute.internal`
node 3: `ip-10-254-7-124.us-west-2.compute.internal` (the 4th in the list, `underutilized`)
node 4 (tainted node): `ip-10-254-35-254.us-west-2.compute.internal`

```
 node.go:46] "Node lister returned empty list, now fetch directly"
 nodeutilization.go:167] "Node is overutilized" node="ip-10-254-25-28.us-west-2.compute.internal" usage=map[cpu:3905m memory:7604Mi pods:42] usagePercentage=map[cpu:99.61734693877551 memory:51.64679503829685 pods:72.41379310344827]
 nodeutilization.go:167] "Node is overutilized" node="ip-10-254-33-235.us-west-2.compute.internal" usage=map[cpu:2910m memory:5916Mi pods:15] usagePercentage=map[cpu:74.23469387755102 memory:40.64559710002493 pods:25.862068965517242]
 nodeutilization.go:170] "Node is appropriately utilized" node="ip-10-254-35-254.us-west-2.compute.internal" usage=map[cpu:2700m memory:2548Mi pods:5] usagePercentage=map[cpu:34.13400758533502 memory:13.08941319299865 pods:8.620689655172415]
 nodeutilization.go:164] "Node is underutilized" node="ip-10-254-7-124.us-west-2.compute.internal" usage=map[cpu:800m memory:1652Mi pods:4] usagePercentage=map[cpu:20.408163265306122 memory:11.349987560723662 pods:6.896551724137931]
 lownodeutilization.go:100] "Criteria for a node under utilization" CPU=25 Mem=25 Pods=25
 lownodeutilization.go:101] "Number of underutilized nodes" totalNumber=1
 lownodeutilization.go:114] "Criteria for a node above target utilization" CPU=50 Mem=50 Pods=50
 lownodeutilization.go:115] "Number of overutilized nodes" totalNumber=2
 nodeutilization.go:223] "Total capacity to be moved" CPU=1160 Mem=5898807296 Pods=25
 nodeutilization.go:226] "Evicting pods from node" node="ip-10-254-25-28.us-west-2.compute.internal" usage=map[cpu:3905m memory:7604Mi pods:42]
 nodeutilization.go:229] "Pods on node" node="ip-10-254-25-28.us-west-2.compute.internal" allPods=42 nonRemovablePods=16 removablePods=26
 nodeutilization.go:236] "Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="certmanager-system/cert-manager-cainjector-748dc889c5-tznrm"
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="certmanager-system/cert-manager-58bf978869-8kjdj"
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cert-manager/cert-manager-webhook-85fb68c79b-hp2cj"
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cert-manager/cert-manager-cainjector-d6cbc4d9-q5fwq"
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="certmanager-system/cert-manager-webhook-977c6494-wgbr4"
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="cert-manager/cert-manager-56b8fc4cb7-gk2vz"
...
 nodeutilization.go:240] "Evicted pods from node" node="ip-10-254-25-28.us-west-2.compute.internal" evictedPods=0 usage=map[cpu:3905m memory:7604Mi pods:42]
 nodeutilization.go:226] "Evicting pods from node" node="ip-10-254-33-235.us-west-2.compute.internal" usage=map[cpu:2910m memory:5916Mi pods:15]
 nodeutilization.go:229] "Pods on node" node="ip-10-254-33-235.us-west-2.compute.internal" allPods=15 nonRemovablePods=8 removablePods=7
 nodeutilization.go:236] "Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
...
 nodeutilization.go:258] "Skipping eviction for pod, doesn't tolerate node taint" pod="istio-operator/istio-operator-6f9dcd4469-dx97x"
 ...
 lownodeutilization.go:163] "Total number of pods evicted" evictedPods=0
 duplicates.go:99] "Processing node" node="ip-10-254-25-28.us-west-2.compute.internal"
 duplicates.go:99] "Processing node" node="ip-10-254-33-235.us-west-2.compute.internal"
 duplicates.go:99] "Processing node" node="ip-10-254-35-254.us-west-2.compute.internal"
 duplicates.go:99] "Processing node" node="ip-10-254-7-124.us-west-2.compute.internal"
 pod_antiaffinity.go:81] "Processing node" node="ip-10-254-25-28.us-west-2.compute.internal"
 pod_antiaffinity.go:81] "Processing node" node="ip-10-254-33-235.us-west-2.compute.internal"
 pod_antiaffinity.go:81] "Processing node" node="ip-10-254-35-254.us-west-2.compute.internal"
 pod_antiaffinity.go:81] "Processing node" node="ip-10-254-7-124.us-west-2.compute.internal"
 descheduler.go:152] "Number of evicted pods" totalEvicted=0
```

It feels like `descheduler` is evaluating the tainted node as any possible target node and decide to not evict even if the pods could be schedules on the other not-tainted node... 

am I missing something ? 
Is it because  `descheduler` is not nodePool aware ? 
should I start one `descheduler` per nodePool and use filters ? Or any other way to get this working ?

Many thanks

**Comment by damemi** [comment]
Hi @prune998, that's an odd behavior and it looks like the pods should be evicting. Based on the descheduler logs, the tainted node shouldn't even be considered as a possibility for the evicted pods since it is `appropriately utilized`. From what I can tell, it is trying to evict pods to fit onto the untainted node but failing on the taint check.

For one, it would be more helpful if we could update [that log line](https://github.com/kubernetes-sigs/descheduler/blob/0ff8ecb/pkg/descheduler/strategies/nodeutilization/nodeutilization.go#L258) to show which node and which taint are causing the problem. That would be a good TODO on our end

@prune998 could you provide the full yaml for each node and the nodepools? Is it possible that there are any other taints that could be on them?

**Comment by prune998** [comment]
I'll setup a test cluster and reproduce the problem. Will keep you posted here.
Maybe adding more precise logs here : https://github.com/kubernetes-sigs/descheduler/blob/0ff8ecb41ecf90ff2cfaa84a3e763ad0c800cb6d/pkg/utils/pod.go#L209

I will also run with higher verbosity :)

**Comment by prune998** [comment]
Re-run the same test with `-v 5`:

```
"Pod doesn't tolerate nodes taint" pod="knative-serving/autoscaler-84fcdc5449-9h6b7" nodeName="ip-10-254-4-239.us-west-2.compute.internal"
```

The node IS actually tainted by the autoscaler:
```
Taints:             DeletionCandidateOfClusterAutoscaler=1646230182:PreferNoSchedule
```

Damn... I guess my issue is just about finding the right level for the autoscaler and descheduller so they can work together...

Sorry for the noise. 

I looked at adding the `taint` that was blocking the eviction in the logs... but it's 3 chained function calls that returns `bool` values only... so adding the taint info would mean a change in the function signature. 
I don't want to dig more into it except if you see the value and agree we should change the functions ? Let me know and I will PR for it if you think int's worth it.

Thanks again for your support !

**Comment by damemi** [comment]
@prune998 no problem, I think it would be worth trying to improve that log with more info than just the pod. I see what you mean about it being tricky, but if you're interested in making the change and it's not too much work for you go for it! We can always review

**Comment by prune998** [comment]
ok, thanks @damemi, will PR soon then.

**Comment by prune998** [comment]
PR created as https://github.com/kubernetes-sigs/descheduler/pull/757 @damemi 

I actually copied the taint validation over and changed it to return the first taint that is blocking. This is easier and does not change the other function calls that are using the `filter` attribute.

Please let me know what you think.

**Comment by ingvagabund** [comment]
@prune998 https://github.com/kubernetes-sigs/descheduler/pull/757 merged. Is there anything else left for resolving?

**Comment by prune998** [comment]
nope. Closing this issue. Thanks @ingvagabund
