### ISSUE TITLE
Feature Request: NodeLifeTime Policy

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes-sigs/descheduler#754]
**Is your feature request related to a problem? Please describe.**

I would like to make sure nodes are regularly rolled, to pick up new AMI's, node configuration changes, or just as a means of prevent nodes from gaining too much "cruft", by existing for a long time.

**Describe the solution you'd like**

NodeLifeTime policy, similar to the PodLifeTime Policy

**Describe alternatives you've considered**

N/A

**What version of descheduler are you using?**

descheduler version: N/A

**Additional context**

**Comment by JaneLiuL** [comment]
podlifetime policy is for evict pod which time more than `MaxPodLifeTimeSeconds`.
For `NodeLifeTime`, for a node live long time, then evict the node?  Yet this is open discussion.

**Comment by ingvagabund** [comment]
The descheduler is pod oriented. Whenever a pod is evicted from a node, other pods can take its place instead. The descheduler does not implement any node protection against scheduling new pods. Is the expectation here to fully drain entire node? Or, rather decrease a chance of scheduling a pod on a node proportionally to its lifetime?

**Comment by ghostsquad** [comment]
> The descheduler is pod oriented. Whenever a pod is evicted from a node, other pods can take its place instead. The descheduler does not implement any node protection against scheduling new pods. Is the expectation here to fully drain entire node? Or, rather decrease a chance of scheduling a pod on a node proportionally to its lifetime?

I suppose you are right. The job of NodeLifeTime would be that of the cluster autoscaler, not this.
