### ISSUE TITLE
LowUtilization and HighUtilization Strategies both sort nodes in descending order

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes-sigs/descheduler#756]
**What version of descheduler are you using?**

descheduler version: 0.23.1

According to the source code: https://github.com/kubernetes-sigs/descheduler/blob/0b2c10d6cee917bc553f743c44c51e730f9b1205/pkg/descheduler/strategies/nodeutilization/nodeutilization.go#L319

both high and low utilization strategies use the same function, and nodes are cordoned/evicted based on this sorting.

For `HighNodeUtilization`, described as:

> This strategy finds nodes that are under utilized and evicts pods from the nodes in the hope that these pods will be scheduled compactly into fewer nodes.

It would make the _most_ sense to find/cordon/evict from the _least_ utilized nodes first, not the highest utilized nodes.

For `LowNodeUtilization`

> This strategy finds nodes that are under utilized and evicts pods, if possible, from other nodes in the hope that recreation of evicted pods will be scheduled on these underutilized nodes.

It would make sense to sort this way only for this strategy.

**Comment by JaneLiuL** [comment]
hi 
yet, thanks for raise it~ you are right, it would make sense to sort this way only for `LowNodeUtilization`

**Comment by damemi** [comment]
@ghostsquad if #725 covers your request here do you mind if we close this issue as a duplicate?

**Comment by ghostsquad** [comment]
Yes I agree. I will close this.
