### ISSUE TITLE
MountVolume.SetUp failed for volume "policy-volume" : object "kube-system"/"descheduler-policy-configmap" not registered

### ISSUE THREAD

**Issue by ThorManager** [kubernetes-sigs/descheduler#765]
MountVolume.SetUp failed for volume "policy-volume" : object "kube-system"/"descheduler-policy-configmap" not registered
???

**Comment by JaneLiuL** [comment]
hi.
could you provide some informations including how you install descheduler, to use helm or manifest?
which version that you use? including k8s version and descheduler version.
it would be better to provide me the installation command for me to troubleshooting :)

**Comment by ThorManager** [comment]
kubeadm 1.23 descheduler 0.9 The installation command follows the cronjob in the tutorial 3Q

**Comment by JaneLiuL** [comment]
is it this one: https://github.com/kubernetes-sigs/descheduler#run-as-a-cronjob ?

**Comment by ThorManager** [comment]
yes

**Comment by ThorManager** [comment]
kubectl create -n kube-system -k cronjob

**Comment by ThorManager** [comment]
![image](https://user-images.githubusercontent.com/96821352/158511376-574a7852-ffc4-4d99-9b1b-57c3db959897.png)
![image](https://user-images.githubusercontent.com/96821352/158511400-63338534-b765-4efb-b948-fbe979a2867e.png)
![image](https://user-images.githubusercontent.com/96821352/158511443-a4c1bade-4c69-4f3d-9993-a8ce0280f4cb.png)

**Comment by ThorManager** [comment]
It really can't be solved, so it's hard for you

**Comment by JaneLiuL** [comment]
seems like some race condition

**Comment by ThorManager** [comment]
sorry I don't understand

**Comment by JaneLiuL** [comment]
would you like to delete the cronjob and apply again?

**Comment by ThorManager** [comment]
![image](https://user-images.githubusercontent.com/96821352/158515484-7728be04-fa61-46bb-a5bb-0066c9ad067f.png)
Hi I've used logical volume. Please see if it's normal

**Comment by JaneLiuL** [comment]
sorry for i can not reproduce this issue.
would you help to provide your installation yaml file content and put it into here?

**Comment by ThorManager** [comment]
cronjob.yml
`
---
apiVersion: batch/v1  # for k8s version < 1.21.0, use batch/v1beta1
kind: CronJob
metadata:
  name: descheduler-cronjob
  namespace: kube-system
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: descheduler-pod
        spec:
          priorityClassName: system-cluster-critical
          containers:
          - name: descheduler
            image: k8s.gcr.io/descheduler/descheduler:v0.23.1
            volumeMounts:
            - name: descheduler-voll
              mountPath: /policy-dir
            command:
              - "/bin/descheduler"
            args:
              - "--policy-config-file"
              - "/policy-dir/policy.yaml"
              - "--v"
              - "3"
            resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /healthz
                port: 10258
                scheme: HTTPS
              initialDelaySeconds: 3
              periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
          restartPolicy: "Never"
          serviceAccountName: descheduler-sa
          volumes:
          - name: descheduler-voll
            persistentVolumeClaim:
              claimName: descheduler-pvc
`
rbac.yaml
`---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: descheduler-cluster-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: descheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descheduler-cluster-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-cluster-role
subjects:
  - name: descheduler-sa
    kind: ServiceAccount
    namespace: kube-system
`
polcy.yaml
`apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
      enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
      enabled: true
  "LowNodeUtilization":
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            "cpu" : 20
            "memory": 20
            "pods": 20
          targetThresholds:
            "cpu" : 50
            "memory": 50
            "pods": 50`

**Comment by ThorManager** [comment]
No expulsion

`I0316 05:02:02.091335       1 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1647406922\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1647406921\" (2022-03-16 04:02:01 +0000 UTC to 2023-03-16 04:02:01 +0000 UTC (now=2022-03-16 05:02:02.091298064 +0000 UTC))"
I0316 05:02:02.091411       1 secure_serving.go:200] Serving securely on [::]:10258
I0316 05:02:02.091505       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0316 05:02:02.107205       1 reflector.go:219] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.107222       1 reflector.go:255] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.107236       1 reflector.go:219] Starting reflector *v1.PriorityClass (0s) from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.107249       1 reflector.go:255] Listing and watching *v1.PriorityClass from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.107237       1 reflector.go:219] Starting reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.107274       1 reflector.go:255] Listing and watching *v1.Namespace from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.208100       1 node.go:46] "Node lister returned empty list, now fetch directly"
I0316 05:02:02.213641       1 descheduler.go:263] Building a pod evictor
I0316 05:02:02.214179       1 nodeutilization.go:164] "Node is underutilized" node="kube-nodes1" usage=map[cpu:1100m memory:240Mi pods:14] usagePercentage=map[cpu:13.75 memory:1.5113762798053414 pods:12.727272727272727]
I0316 05:02:02.214214       1 nodeutilization.go:164] "Node is underutilized" node="kube-nodes2" usage=map[cpu:750m memory:256Mi pods:10] usagePercentage=map[cpu:9.375 memory:1.6073425258793281 pods:9.090909090909092]
I0316 05:02:02.214235       1 nodeutilization.go:164] "Node is underutilized" node="kube-nodes3" usage=map[cpu:350m memory:90Mi pods:10] usagePercentage=map[cpu:4.375 memory:1.1497826441707168 pods:9.090909090909092]
I0316 05:02:02.214254       1 nodeutilization.go:164] "Node is underutilized" node="kube-nodes4" usage=map[cpu:250m memory:0 pods:11] usagePercentage=map[cpu:3.125 memory:0 pods:10]
I0316 05:02:02.214274       1 nodeutilization.go:164] "Node is underutilized" node="kube-nodes5" usage=map[cpu:250m memory:0 pods:2] usagePercentage=map[cpu:6.25 memory:0 pods:1.8181818181818181]
I0316 05:02:02.214294       1 nodeutilization.go:164] "Node is underutilized" node="kube-nodes6" usage=map[cpu:250m memory:0 pods:2] usagePercentage=map[cpu:6.25 memory:0 pods:1.8181818181818181]
I0316 05:02:02.214310       1 lownodeutilization.go:101] "Criteria for a node under utilization" CPU=20 Mem=20 Pods=30
I0316 05:02:02.214318       1 lownodeutilization.go:102] "Number of underutilized nodes" totalNumber=6
I0316 05:02:02.214332       1 lownodeutilization.go:115] "Criteria for a node above target utilization" CPU=20 Mem=20 Pods=30
I0316 05:02:02.214338       1 lownodeutilization.go:116] "Number of overutilized nodes" totalNumber=0
I0316 05:02:02.214349       1 lownodeutilization.go:129] "All nodes are underutilized, nothing to do here"
I0316 05:02:02.214362       1 duplicates.go:110] "Processing node" node="kube-nodes1"
I0316 05:02:02.214466       1 duplicates.go:110] "Processing node" node="kube-nodes2"
I0316 05:02:02.214518       1 duplicates.go:110] "Processing node" node="kube-nodes3"
I0316 05:02:02.214569       1 duplicates.go:110] "Processing node" node="kube-nodes4"
I0316 05:02:02.214623       1 duplicates.go:110] "Processing node" node="kube-nodes5"
I0316 05:02:02.214641       1 duplicates.go:110] "Processing node" node="kube-nodes6"
I0316 05:02:02.214694       1 pod_antiaffinity.go:92] "Processing node" node="kube-nodes1"
I0316 05:02:02.214783       1 pod_antiaffinity.go:92] "Processing node" node="kube-nodes2"
I0316 05:02:02.214910       1 pod_antiaffinity.go:92] "Processing node" node="kube-nodes3"
I0316 05:02:02.214989       1 pod_antiaffinity.go:92] "Processing node" node="kube-nodes4"
I0316 05:02:02.215227       1 pod_antiaffinity.go:92] "Processing node" node="kube-nodes5"
I0316 05:02:02.215250       1 pod_antiaffinity.go:92] "Processing node" node="kube-nodes6"
I0316 05:02:02.215266       1 descheduler.go:288] "Number of evicted pods" totalEvicted=0
I0316 05:02:02.215380       1 tlsconfig.go:255] "Shutting down DynamicServingCertificateController"
I0316 05:02:02.215444       1 reflector.go:225] Stopping reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0316 05:02:02.215475       1 secure_serving.go:311] Stopped listening on [::]:10258
`

**Comment by kingyang** [comment]
I have the same problem.

**Comment by JackSinclairT** [comment]
I have the same problem too. Please can we reopen this

**Comment by damemi** [comment]
@ThorManager I see you closed this, were you able to fix the original issue?

**Comment by dipakparmar** [comment]
I also have the same problem; @ThorManager can you share the fix if you found any?
