### ISSUE TITLE
PodLifeTime to include Terminating status

### ISSUE THREAD

**Issue by mateuszdrab** [kubernetes-sigs/descheduler#766]
Hi team

I have a feature suggestion to handle an issue that I'm experiencing in my environment.

**Is your feature request related to a problem? Please describe.**
The descheduler strategy PodLifeTime is limited to Running and Pending statuses.
I have repeated situations involving pods stuck in Terminating state due to storage unmounting when using Longhorn - usually happening when the node reboots unexpectedly. Manually removing the pod allows it to be rescheduled just fine, but without manual intervention, it's stuck in this state forever.
**Describe the solution you'd like**
Add a strategy to PodLifeTime to enable killing off pods stuck in terminating status.
**Describe alternatives you've considered**
None alternatives considered
**What version of descheduler are you using?**
descheduler version: 0.23.0

**Additional context**
Manually removing the pod is achieved by k9s, using the kill pod command. I believe that removes the resource from the cluster.
This feature could potentially qualify under the RemoveFailedPods strategy, depends if we consider a pod stuck in terminating status as failed.

Thanks

**Comment by damemi** [comment]
The descheduler uses the eviction API (rather than actually deleting pods), so this might not be able to get rid of terminating pods. We could consider a descheduling strategy that force-deletes, rather than evicts, but this could be risky and cause service disruptions if not used very carefully.

**Comment by mateuszdrab** [comment]
Could a new strategy be created instead to allow killing of pods in Terminating status?
I'm just wondering if that would be better than adding an support for a force parameter that could get misused or misunderstood on existing strategies. 
Theoretically, one shouldn't need to kill a pod unless a greaceful attempt to deschedule is stuck - suggesting a separate strategy like KillTerminatingPods for example.

**Comment by ingvagabund** [comment]
> I have repeated situations involving pods stuck in Terminating state due to storage unmounting when using Longhorn

Is force deleting these pods the only way how to get out from this situation? Is this a known issue with the Longhorn? Sometime the sig-storage community might help with?
