### ISSUE TITLE
helm chart multiple replicas

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/descheduler#773]
**Is your feature request related to a problem? Please describe.**
I want to run descheduler every 10s with a Deployment. However, helm chart is fixed to 1 replica. For higher availability deployment should be run with multiple replicas.

**Describe the solution you'd like**
Allow specifying multiple replicas and maybe use kube leases (like cluster autoscaler) or similar leader election system

**Comment by JaneLiuL** [comment]
hi @matti  thanks for open this issue, as i check there have a pull request for fix this issue:
https://github.com/kubernetes-sigs/descheduler/pull/722
you can watch this pr if you feel interest :)

**Comment by ingvagabund** [comment]
@matti Would you mind checking the helm part of https://github.com/kubernetes-sigs/descheduler/pull/722?

**Comment by matti** [comment]
@ingvagabund not sure how as an outsider to this project. I don't think merging breaks anything because this is an opt-in feature.

**Comment by ingvagabund** [comment]
I don't have much experience with the helm besides simple operations. So I was just wondering if you might have some to spare before the chart bits get merged.

**Comment by matti** [comment]
well, I don't have much experience running a non-released descheduler helm chart so I guess you'll have to merge and release and then I'll have to test after it :)

**Comment by ingvagabund** [comment]
@matti https://github.com/kubernetes-sigs/descheduler/pull/722 merged, happy hacking!!!

**Comment by ingvagabund** [comment]
/close
Fixed in https://github.com/kubernetes-sigs/descheduler/pull/722
