### ISSUE TITLE
Misisng parameter in user-guide doc for PodLifeTime strategy

### ISSUE THREAD

**Issue by pravarag** [kubernetes-sigs/descheduler#780]
The following user example: https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md#balance-cluster-by-pod-age is missing the parameter, `podLifeTime` under `PodLifeTime` strategy field. And if applied directly from the user doc, it throws the below error:

`pod_lifetime.go:62] "Invalid PodLifeTime parameters" err="MaxPodLifeTimeSeconds not set"`

I've created the following PR as a fix: https://github.com/kubernetes-sigs/descheduler/pull/779

**Comment by seanmalloy** [comment]
Looks like #779 was merged to fix this.

/kind documentation
/close
