### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#782]
We currently have very little measurement on how the Descheduler performs at scale. Issues like https://github.com/kubernetes-sigs/descheduler/issues/774 highlight this lack of information.

It would be good to provide benchmarks and identify changes/new strategies in particular that cause memory or performance degradation with a set of perf-scale tests similar to what the scheduler offers. To start these could measure descheduling throughput and memory consumption end-to-end as well as for individual strategies

**Comment by pravarag** [comment]
@damemi, I'm thinking if this could be broken into parts with tests either based on `strategies` or different criteria like types of cluster( KIND or managed K8s cluster by any cloud provider).

Can these be used as a starting reference: https://github.com/kubernetes/perf-tests ?

**Comment by damemi** [comment]
> @damemi, I'm thinking if this could be broken into parts with tests either based on `strategies` or different criteria like types of cluster( KIND or managed K8s cluster by any cloud provider).
> 
> Can these be used as a starting reference: https://github.com/kubernetes/perf-tests ?

@pravarag yeah, I think ideally this would be at least broken into tests for individual strategies (so we can identify which strategies suffer the most)
