### ISSUE TITLE
Make room for daemon sets (#303 again)

### ISSUE THREAD

**Issue by unacceptable** [kubernetes-sigs/descheduler#783]
**Is your feature request related to a problem? Please describe.**
---
As @runningman84 pointed out
> Sometimes daemon sets don't fit into existing nodes. In the case the descheduler should kill a pod which uses the least resources in order to allow the daemon set to run..

This exact use-case is what made me interested in descheduler in the first place.  

As @ingvagabund pointed out preemption and priorities would take care of this use case.  If that's the case then wouldn't podAffinities and podAntiAffinities take care of other use cases that descheduler addresses.

**Describe the solution you'd like**
---
As an SRE, I want to ensure that daemonset like security related workloads are scheduled.  IMHO if a pod on a node is preventing a daemonset pod from being scheduled and it's part of a ReplicaSet it should be nuked.

**Describe alternatives you've considered**
---
I considered writing my own descheduler...
![image](https://user-images.githubusercontent.com/18185488/162339760-5a6def75-ec5e-4288-8862-1cc68a712471.png)

Nothing fancy just a shell script running as a Kubernetes Cronjob.

**What version of descheduler are you using?**
---
descheduler version: 0.23.1

**Additional context**
---
none

**Comment by damemi** [comment]
Hi @unacceptable 
Just curious, have you tried solving this with preemption and found that it wasn't working for you? I ask because this still sounds like something that preemption in the scheduler should solve, so any more details you can share about the use case could help us address this feature gap.

**Comment by unacceptable** [comment]
@damemi Sorry I addressed that in the initial comment but misspelled it.

A lot of helm charts that have a DeamonSet that I deem as critical don't include the `priorityClassName` attribute.  Granted I could go put in PRs for everything that I deem as business-critical (e.g. log collection utilities, security scanning tools, identity & access management delegation workloads, etc.) but there's no guarantee that the maintainers of those third party projects will agree with and approve my PRs.  In that case, I could fork the chart but then that's another thing for me to maintain and patch.

What you're saying is very valid and if there were all internal projects that my team/org maintained I would just do use `preemption`.

It seems like there has to be a better way to manage this problem in my opinion.  I was hopeful when I first came across `descheduler` that this might be a project to help alleviate this pain point as well as a few others that it already solves.  

In my opinion, life is organized chaos.  I only have so much time that I can dedicate to certain problems, and the risk of missing a configuration setting is very real (as long as primates are involved).

It would be nice to have a fire-and-forget approach to solving this problem.

**Comment by ingvagabund** [comment]
> As an SRE, I want to ensure that daemonset like security related workloads are scheduled. IMHO if a pod on a node is preventing a daemonset pod from being scheduled and it's part of a ReplicaSet it should be nuked.

This requires a relation between the pod and the DS pod saying "this pod has higher priority than this pod". Which goes back to using preemption and priorities. In the case of descheduler, what would be the mechanism of saying such priority? Even when the descheduler eventually evicts the lower priority pod to make space for the DS pod, the kube-scheduler can decide to schedule another non-DS pod. Have you consider using mutating admission webhook to set the `priorityClassName` to all the DSs?
