### ISSUE TITLE
Cluster Node Skew Eviction Loop

### ISSUE THREAD

**Issue by jklaw90** [kubernetes-sigs/descheduler#785]
**Is your feature request related to a problem? Please describe.**

Yes, currently our clusters may have node skew to one AZ. In such cases the scheduler may try and place the pod back on the same az/sometimes even node it was just evicted from. This causes an eviction loop until the cluster rebalances it's AZs.

**Describe the solution you'd like**

The `RemovePodsViolatingTopologySpreadConstraint` should be stateful so it can prevent continuous eviction on the same nodes. (maybe even az). perhaps it should also take cluster node skew into constraint. 

**Describe alternatives you've considered**

Currently looking into why our clusters nodes are skewing heavily to some AZs, external of descheduler.

**What version of descheduler are you using?**

descheduler version: 1.23

**Comment by damemi** [comment]
@jklaw90 could you explain a bit more what you mean by this? Maybe an example scenario would help, I'm not clear what the node skew you're referring to is

**Comment by jklaw90** [comment]
@damemi we are using the cluster autoscaler with the [random expander](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders). we've seen times where one AZs autoscaling group has grown quite a bit larger than others, so the scheduler will continuously put the evicted pods back in that same AZ. This causes a loop of evictions until the cluster nodes balances out again.

**Comment by a7i** [comment]
Any chance this is a duplicate of #604?

AFAIT PR #636 seems pretty close to being ready 🤞🏼

**Comment by jklaw90** [comment]
i can close this out for now and we can wait till that pr is done, but i think this would still be in addition to that. 
If i understand correctly the scheduler may still pick the az that meets the requirements most based on weights of plugins which may still go against the topology spread constraint?

**Comment by damemi** [comment]
@jklaw90 the scheduler won't place pods in any domain that would violate a `DoNotSchedule` topology spread constraint. It can place them if the constraint is `ScheduleAnyway`, but this is just another scoring plugin that can be configured to have a higher weight than the other scoring plugins
