### ISSUE TITLE
descheduler when ReplicaSet=1

### ISSUE THREAD

**Issue by jiangxiaobin96** [kubernetes-sigs/descheduler#786]
**Is your feature request related to a problem? Please describe.**

Deployment often act as backend providing service. If one deployment only has single pod(replicas: 1), descheduler can still evict it. At that time, the service will be stopped while recreating.

**Describe the solution you'd like**

Add a filter to count the deployments' or jobs' replicas. If replicas=1, this pod can not be evict.

**Comment by jiangxiaobin96** [comment]
I consider it as a filter `minReplicas`. Users can set this param like `minReplicas:2` means if deployment or job only have less than or equal 2 replications, these pods do not need to evict. Because if there is one or two replications, the service will be stopped or overload when evicting and recreating new pod.

**Comment by jiangxiaobin96** [comment]
Refer to `RemoveDuplicates`, we need to calculate owerKey to distinguish different ownerRef pods by unique key `Namespace/Kind/Name/imageHash`. This ownerRef should be defined as global variable and be used at `pkg/descheduler/evictions/evictions.go` as a pod filter. 

At `func (pe *PodEvictor) Evictable()` in `evictions.go`, we can get  `minReplicas` like `priority`. To each pod, we need to get its replicas according to `ownerKeyOccurence` and compare it with `minReplicas`. If pod's replicas less than `minReplicas`, this pod can not be evict.

**Comment by ingvagabund** [comment]
This sounds reasonable. This will require to include ReplicaSet/RC/SS informers in the pod evictor to quickly get the number of ready instances. What's the target descheduler version you'd like to have this feature implement?

**Comment by rouke-broersma** [comment]
Perhaps I'm misunderstanding something but I thought the docs specify that descheduler will never deschedule a single pod?

**Comment by damemi** [comment]
> Perhaps I'm misunderstanding something but I thought the docs specify that descheduler will never deschedule a single pod?

@rouke-broersma could you share which part of the docs makes it sound that way? The descheduler [won't evict bare pods](https://github.com/kubernetes-sigs/descheduler#pod-evictions) (ie, single pods with no replica controller) by default, but that can be overridden

**Comment by jiangxiaobin96** [comment]
Is there any examples about one pod containing several ownerReferences?

**Comment by jiangxiaobin96** [comment]
`PodDisruptionBudget ` is better if deployed in user mode. Close this issue.

**Comment by yxiaoy6** [comment]
Sorry, I didn't find it in the documentation, I want to confirm, without PodDisruptionBudget, will evict the pod with ReplicaSet=1 in the latest stable version of descheduler?

**Comment by jiangxiaobin96** [comment]
Without PodDisruptionBudget, descheduler will evict the pod with ReplicaSet=1. ReplicaSet=1 is an example. In some scenes, we must assure there are n% active pods of deployment for serivce. Here, i am in dilemma if there is necessary to add this new filter for descheduler when kebernetes has already supported PodDisruptionBudget.

**Comment by yxiaoy6** [comment]
> PodDisruptionBudget

I think it's necessary, because we won't set PodDisruptionBudget except for stateful services. For clusters that have been in use for a long time, there are already many services, and it is a bit difficult to set PodDisruptionBudget for old services now.

**Comment by fanhaouu** [comment]
it is necessary to add this new filter for descheduler@jiangxiaobin96
