### ISSUE TITLE
A concern about the race condition during eviction cycle for CronJob

### ISSUE THREAD

**Issue by eminaktas** [kubernetes-sigs/descheduler#806]
Hi, dear Descheduler users and maintainers

We have a concern about the race condition. Running Descheduler as Deployment wouldn't have this problem as far as we know this problem wouldn't be the case since in [here](https://github.com/kubernetes-sigs/descheduler/blob/15794ba00d66edea786eeac06a6a4699f52fc34f/pkg/descheduler/descheduler.go#L234), it blocks the cycle until the current cycle finishes and it resets the timer for a new cycle. 

Unfortunately, It might be a problem for CronJob cases since it could start a new eviction while beforehand eviction isn't finished. Shouldn't we implement a lock mechanism to prevent such cases? We can also add these details to the readme. It can even make Descheduler safer to use.

Could it even be a slight chance to have a race condition for Deployment usage?

P.S: we are meaning for race condition as Descheduler could trigger a new cycle before the older cycle finishes.

cc @Dentrax

**Comment by a7i** [comment]
@eminaktas The default CronJob configuration is set to forbid concurrency ([here](https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/templates/cronjob.yaml#L14)).

Meaning that two concurrent Kubernetes Job will not run. which will eliminate this problem, correct?

**Comment by eminaktas** [comment]
I didn't realize it already had the config there. Thanks @a7i 

As you say, the problem never existed 🚀. I am closing this issue.
