### ISSUE TITLE
Logs are still redirected to stderr by default

### ISSUE THREAD

**Issue by tamir-allc** [kubernetes-sigs/descheduler#811]
**What version of descheduler are you using?**

descheduler version: v0.24.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
None

**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

I installed the latest v0.24.0 version using the provided helm chart (also v0.24.0).
The chart created a CronJob on the cluster.
The pods created by that CrobJob are indeed using v0.24.0 but they still log everything using stderr instead of stdout.

If I add the argument `--logtostderr=false`  it works but that's throws a deprecation warning and also misses the purpose of the fix.
Moreover, downloading the image locally and running it without flags, prints the following:
```
      --logtostderr                              log to standard error instead of files (default true) (DEPRECATED: will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components)
```

which seems like it still defaults to true

**What did you expect to see?**
After upgrading to v0.23.1 and v0.24.0, I expect to see logs being sent to stdout by default as #680 was fixed and was part of the v0.23.0 release notes.

**What did you see instead?**
Logs are still sent to stderr and considered as Errors in Datadog.

**Comment by damemi** [comment]
Mentioned in #815, we should investigate why `--logtostderr` was deprecated and what it is replaced with. I imagine we just need to change how our flags are being instantiated. @JaneLiuL do you have a chance to look at it? Open to anyone

**Comment by harshanarayana** [comment]
The suggestion in KEP regarding the flag deprecation of `klog` was to use something like [go-runner](https://github.com/kubernetes/release/tree/master/images/build/go-runner)

xref: [KEP-2845: Deprecate klog specific flags in Kubernetes Compnents](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components#user-stories)

`/go-runner --redirect-stderr=true /bin/descheduler <args>` could be done. That is how I am running it currently.

**Comment by damemi** [comment]
/remove-lifecycle rotten
Sorry this got stale, going to try to revive this as it might be related to https://github.com/kubernetes-sigs/descheduler/issues/965 (thanks @harshanarayana for pointing this out)
