### ISSUE TITLE
使用方法与提升用户体验

### ISSUE THREAD

**Issue by QiuToo** [kubernetes-sigs/descheduler#819]
你好！很高兴能接触到这个产品。我根据文档说明，使用deployment的方式成功将descheduler部署成功。然而，我并不知道如何使用它。如果能提供Wechat交流群，这将是一个非常棒的决定。

**Comment by damemi** [comment]
Hi, could you please post your issue in English?

**Comment by ingvagabund** [comment]
From google translator:
```
Hi! So happy to have access to this product. According to the documentation,
I successfully deployed the descheduler using the deployment method.
However, I don't know how to use it. It would be a great decision
to provide a Wechat communication group.
```

@QiuToo can you please more elaborate on your use case? Are you deploying the descheduler to learn more about it? About its principles and how it works?

**Comment by liangyuanpeng** [comment]
> 你好！很高兴能接触到这个产品。我根据文档说明，使用deployment的方式成功将descheduler部署成功。然而，我并不知道如何使用它。如果能提供Wechat交流群，这将是一个非常棒的决定。

It is mean @QiuToo have really deploy descheduler and have no idea to 'use it' .
