### ISSUE TITLE
Infinite restarts

### ISSUE THREAD

**Issue by michelefa1988** [kubernetes-sigs/descheduler#828]
**What version of descheduler are you using?**

descheduler version: 0.24.0

**Does this issue reproduce with the latest release?**
Didn't check

**Which descheduler CLI options are you using?**
Helm

</pre></details>

**What did you do?**

I have setup Descheduler using a helm chart. It is running as a deployment

It has been deployed for a while, but last night the `deschedulerRemoveDuplicatePods` kicked in because out of 3x pods 2x were placed on the same node. I am using a `maxSkew=1, whenUnsatisfiable=ScheduleAnyways`

The issue which occurred is that the scheduler keptprovisioning the pod of the same node, therefore descheduler kept restaring the pod infinitely.

My question is - is this supposed to happen or have I misconfigured something?
-->

**What did you expect to see?**

I don't expect a pod to be restarted forever.  (I know i can use a cron job as workaround)

**Logs**
```
I0601 07:30:36.620441       1 duplicates.go:168] "Duplicate found" pod="xxx-prod/xxx-xxx-xxxx-api-b9494cf8d-2rcgt"
I0601 07:30:36.727998       1 duplicates.go:199] "Adjusting feasible nodes" owner={xxx-xxx-prod kind:ReplicaSet xxx-xxxx-api-b9494cf8d imagesHash:crxxxxxxcommon.azurecr.io/xxxxxx/xxx-api:2.9.7-tags-2-9-6.1} from=5 to=4
I0601 07:30:36.728013       1 duplicates.go:207] "Average occurrence per node" node="aks-nodepool01-xxxxx-vmss00000d" ownerKey={namespace:xxxxxx-xxxxxx-prod kind:ReplicaSet name:xxxxxx-xxxxxx-xxx-api-b9494cf8d imagesHash:crxxxxxxcommon.azurecr.io/xxxxxx/xxx-api:2.9.7-tags-2-9-6.1} avg=1
I0601 07:30:36.799531       1 evictions.go:163] "Evicted pod" pod="xxxxxx-xxxxxx-prod/xxxxxx-xxxxxx-xxx-api-b9494cf8d-2rcgt" reason="RemoveDuplicatePods" strategy="RemoveDuplicatePods" node="aks-nodepool01-xxxxx-vmss00000d"
I0601 07:30:36.819365       1 event.go:294] "Event occurred" object="xxxxxx-xxxxxx-prod/xxxxxx-xxxxxx-xxx-api-b9494cf8d-2rcgt" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerRemoveDuplicatePods"
```

**Comment by damemi** [comment]
Sorry, commented this in your other issue before I saw you closed it. But here for reference too:

> @michelefa1988 not sure if you found this, but you should use `RemovePodsViolatingTopologySpreadConstraints` if you want to respect `maxSkew`. `RemoveDuplicates` ensures exactly 1 pod per node

**Comment by michelefa1988** [comment]
@damemi , thanks for your reply.  Replying here since I closed the other one as a duplicate. 

So if I undestand correctly I need to set `RemoveDuplicates=false` but then I need to set `RemovePodsViolatingTopologySpreadConstraints=true`? 

Let me know if you see anything wrong with the config below :)
```
deschedulerPolicy:
  # nodeSelector: "key1=value1,key2=value2"
  # maxNoOfPodsToEvictPerNode: 10
  # ignorePvcPods: true
  # evictLocalStoragePods: true
  strategies:
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: true
      params:
        includeSoftConstraints: false
    RemoveDuplicates:
      enabled: false


```

**Comment by damemi** [comment]
@michelefa1988 that's correct, but if the pods you're trying to balance have `whenUnsatisfiable=ScheduleAnyways`, you'll also need to set `includeSoftConstraints: true` in the descheduler policy

**Comment by damemi** [comment]
@michelefa1988 the opposite actually. Without `includeSoftConstraints: true`, you'll never see any pods with a `ScheduleAnyway` constraint get evicted, because the strategy won't consider them. 

With it set to `true`, it's possible that you could end up in another restart loop, but that will only happen if your topology domains exceed `maxSkew`. In contrast, `RemoveDuplicates` will evict pods as soon as there is more than 1 of the same pod on the same node.
