### ISSUE TITLE
Helm Tests + Kustomize

### ISSUE THREAD

**Issue by jklaw90** [kubernetes-sigs/descheduler#829]
If using kustomize to render the chart and add extra transformations you can't disable the tests with the normal --skip-tests, see [issue](https://github.com/kubernetes-sigs/kustomize/issues/3831).

We could add a helm value to get around this case ([kind of odd](https://github.com/kubernetes-sigs/descheduler/pull/804)), but in general i don't see much value form the test provided. 
I just tested it locally and it "passed" while the image wasn't able to pull so i do wondering if we should remove the helm test or improve it to be more useful?

**Comment by a7i** [comment]
@jklaw90 Curious why not use [this directory](https://github.com/kubernetes-sigs/descheduler/tree/master/kubernetes) for kustomize?

Agreed on improving the test. 👍🏼
