### ISSUE TITLE
Descheduler on insecure port

### ISSUE THREAD

**Issue by olivierpilotte** [kubernetes-sigs/descheduler#842]
Is there a way to run the descheduler on an insecure port? I'm just wondering what's the rationale behind running it on a secure port? Is there a way to provide a ssl certificate? I couldn't find any documentation on this.

**Comment by ingvagabund** [comment]
Serving KA/KS/KCM on an insecure port has been deprecated and removed to increase security measures. We followed the same. There's no plan to serve on an insecure port.

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/kubernetes/issues/91506

**Comment by olivierpilotte** [comment]
Ok, I understand. In this case, is there any way to provide a SSL certificate to the descheduler?

**Comment by ingvagabund** [comment]
@olivierpilotte unfortunately I am not properly educated in this area to answer the question. I will leave for others to chime in.
