### ISSUE TITLE
PodLifeTime: Only processes pods already scheduled on a node

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#858]
PodLifeTime strategy allows for 2 Pod phase status: Pending and Running

>Pending definition: The Pod has been accepted by the Kubernetes cluster, but one or more of the containers has not been set up and made ready to run. **This includes time a Pod spends waiting to be scheduled** as well as the time spent downloading container images over the network.

<br class="Apple-interchange-newline">

Is it possible for a Pod to be stuck on Pending but not scheduled onto a node? If so, this strategy uses `listOldPodsOnNode` which will ignore any pods not scheduled onto a node.

**Comment by damemi** [comment]
> Is it possible for a Pod to be stuck on Pending but not scheduled onto a node?

Yes, a pod is `Pending` before it is scheduled

>  If so, this strategy uses listOldPodsOnNode which will ignore any pods not scheduled onto a node.

I'm not sure what you mean, are you suggesting we change this to ignore unscheduled pods? If so, I agree

**Comment by a7i** [comment]
Duplicate of #832
