### ISSUE TITLE
Upgrade client-go to 0.24

### ISSUE THREAD

**Issue by fredkan** [kubernetes-sigs/descheduler#862]
Support Kubernetes 1.24 version environment.

**What version of descheduler are you using?**  1.24

descheduler version:  Latest

**Comment by damemi** [comment]
@fredkan the descheduler is built with client-go at 1.24: https://github.com/kubernetes-sigs/descheduler/blob/871a103/go.mod#L12

Are you referring to something else?

**Comment by a7i** [comment]
I noticed [kubectl](https://github.com/kubernetes-sigs/descheduler/blob/1eade5bf915e8921ca3267a0275975ef8398830b/go.mod#L17) is on an old version (0.20)

This is being upgraded to 0.25 in the 0.25 release

**Comment by damemi** [comment]
> I noticed [kubectl](https://github.com/kubernetes-sigs/descheduler/blob/1eade5bf915e8921ca3267a0275975ef8398830b/go.mod#L17) is on an old version (0.20)


That's a good catch, and I actually don't think we need that dependency on kubectl. The only place it's being used is [in an e2e](https://github.com/kubernetes-sigs/descheduler/blob/70df89601a943d18f96dad3fd911bea19f10a498/test/e2e/e2e_test.go#L1341) for [`GetPodQOS()`](https://github.com/kubernetes-sigs/descheduler/blob/70df89601a943d18f96dad3fd911bea19f10a498/vendor/k8s.io/kubectl/pkg/util/qos/qos.go#L35) and it's pretty similar to [another `GetPodQOS()` function](https://github.com/kubernetes-sigs/descheduler/blob/70df89601a943d18f96dad3fd911bea19f10a498/pkg/utils/qos.go#L22) we copied over.

We should look into dropping that if possible, it's kind of weird to be depending on kubectl

**Comment by a7i** [comment]
Agreed. I took a stab at it [here](https://github.com/kubernetes-sigs/descheduler/pull/938) but the builds are broken until 0.25 is merged.

**Comment by damemi** [comment]
fixed in #938 
/close
