### ISSUE TITLE
NodeFit doesn't skip checking of resources which are configured as ignoredByScheduler

### ISSUE THREAD

**Issue by uniemimu** [kubernetes-sigs/descheduler#863]
**What version of descheduler are you using?**

descheduler version: latest sources as of the date of filing this

Pods which get scheduled through scheduler extender(s) by using related resources configured as _ignoredByScheduler_, will not work properly with the Descheduler NodeFit -feature, which doesn't understand that the related resources should be ignored also by the Descheduler, when considering Pod fitting a node based on its resource requests.

Ref: https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/#kubescheduler-config-k8s-io-v1beta2-Extender
Says:

> If IgnoredByScheduler is set to true for a resource, kube-scheduler will skip checking the resource in predicates.

Given that calls to the NodeFit function are baked in the node-affinity strategy and thus are always called if that strategy is needed, avoiding the issue is rather impossible by attempts at disabling NodeFit. And of course, disabling NodeFit would only be a workaround anyhow. The resource checks can be valuable, just that not all resources should be treated equal.

So even if the scheduler is configured to skip said resources in its checks, the descheduler however will not skip checking the resource(s) in its predicates, because it has no knowledge of the kube-scheduler configuration. See the comment in function _PodRequestsAndLimits_:

https://github.com/kubernetes-sigs/descheduler/blob/d8897635b0767b8e63176dc578d215b882102d14/pkg/utils/pod.go#L145

In the end then, what happens is that NodeFit will always consider these pods as not fitting anywhere, as the resource merely exists in the Pod spec to indicate that some scheduler extender should be called when scheduling is done. Nodes don't have the resource.

Ideally, the descheduler would automatically mimic the skipping of checks for those same resources. Alternatively, it would at least allow for specifying its own list of resources to be skipped, so that the user could force things to match between the scheduler, and the descheduler.

**Comment by ingvagabund** [comment]
https://github.com/kubernetes-sigs/descheduler/issues/640#issuecomment-1216506965
