### ISSUE TITLE
LowNodeUtilization: cpu utilization don't precise.

### ISSUE THREAD

**Issue by Beherenowhjy** [kubernetes-sigs/descheduler#864]
What version of descheduler are you using?

descheduler version: v0.24.1

Does this issue reproduce with the latest release?
yes

Which descheduler CLI options are you using?

   
          
![image](https://user-images.githubusercontent.com/59044653/176817314-4a063968-533a-4e44-8963-6d3ad9c8101e.png)

Please provide a copy of your descheduler policy config file

![image](https://user-images.githubusercontent.com/59044653/176817535-c006a580-4343-4202-8e81-c38bd64b4367.png)

What k8s version are you using (kubectl version)?

kubectl version Output
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
What did you do?

I get the limit cpu info by kubectl. @damemi say: " the descheduler determines usage based only on pod requests/limits",but the result i got is wrong.the shell file content is :
![image](https://user-images.githubusercontent.com/59044653/176835379-63c48aab-4caf-4f65-b8fe-084ff634e735.png)
the result of cpu limit sum in my server 49-15-01 is 164. but the server 49-15-01 only have 80 cores actually.
![image](https://user-images.githubusercontent.com/59044653/176836114-583fef67-bda8-4e63-9495-fd394d7402c9.png)
actually the cpu limit sum is over 100%,but i get usagePercentage of cpu is 90%. that is a wrong result.
`I0701 06:20:21.308940       1 nodeutilization.go:224] "Node is overutilized" node="n49-15-01" usage=map[cpu:72662m memory:178608144385 pods:37] usagePercentage=map[cpu:90.8275 memory:88.81546469920734 pods:33.63636363636363]`
why i get a wrong result? do u need something more information?
#730 

What did you expect to see?

What did you see instead?

**Comment by damemi** [comment]
Sorry, the nodeutilization calculation is based only on the *requests* of the pods ([see here](https://github.com/kubernetes-sigs/descheduler/blob/d8897635b0767b8e63176dc578d215b882102d14/pkg/descheduler/node/node.go#L266)). (We should double check if this is consistent with the scheduler)

Can you run your script based on requests to see if the values are more in line with what you expect?

**Comment by Beherenowhjy** [comment]
yes. if I run the script based on Requests, value of requests sum is 80. It's closer than limit sum.
I don't know when it count by requests or limits.
if pods not set requests or limit, whether it will participate in the calculation. if it participate in the calculation, What is the basis for the calculation😊

**Comment by Beherenowhjy** [comment]
hi @damemi :
I have a new question about log.How can i persistent log？
I try to set "--log-dir" and "--log-file", but i didn't get the log file.
this is my deployment yaml:
![image](https://user-images.githubusercontent.com/59044653/177276906-6dc0200e-1186-45d0-9c35-e74b3bd8294a.png)
![image](https://user-images.githubusercontent.com/59044653/177277007-420d212b-79d7-4ec7-a51d-13dad0f60a9f.png)
i see some issues close:
#476

**Comment by JaneLiuL** [comment]
hi, refer to https://github.com/kubernetes/klog/pull/102/files, already change as below, we need to update the code for this bug.
log-file -> log_file
log-dir -> log_dir

**Comment by Beherenowhjy** [comment]
Hi @JaneLiuL :
I update the code "log-file -> log_file" and "log-dir -> log_dir".but i still didn't find the log_file.
my descheduler version is 1.21.   I only can use 1.21 now, because my kubectl version is 1.19.
Will the new version solve the problem that the log file cannot be generated?
![image](https://user-images.githubusercontent.com/59044653/177504703-8d7f2857-3bfe-40d3-ae23-3fb22b53d635.png)

**Comment by Beherenowhjy** [comment]
Hi @damemi :
  Thanks for your suggest! I will try to build code by myself.If there is a chance, I hope to develop descheduler with you guys.😃

**Comment by JaneLiuL** [comment]
@damemi  get, i will backport to  1.24, 1.23, and 1.22 now
