### ISSUE TITLE
nodeFit is set to true, but is still evicted for services with only one node available

### ISSUE THREAD

**Issue by yxiaoy6** [kubernetes-sigs/descheduler#890]
**What version of descheduler are you using?**

descheduler version:
0.20.0

**Does this issue reproduce with the latest release?**
I don't know.

**Which descheduler CLI options are you using?**
lownodeutilization

**Please provide a copy of your descheduler policy config file**
  "LowNodeUtilization":
    enabled: true
    params:
      nodeFit: true
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 70
          memory: 70
        thresholds:
          cpu: 20
          memory: 20

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"757dfe7e010afcfa31591df65f26b4b80540975e", GitTreeState:"clean", BuildDate:"2022-04-20T09:01:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

deployment is setting:
      nodeSelector:
        node-type: debezium-prod
There is only one node for this label：
![image](https://user-images.githubusercontent.com/43592152/181180364-c070ba9d-652b-47c4-b63d-623bfd45322d.png)
pod is evicted
I0727 00:31:54.392273       1 evictions.go:117] "Evicted pod" pod="debezium-prod/debezium-postgres-cp-kafka-connect-7c6f4b446b-mg255" reason=" (LowNodeUtilization)"
I0727 00:31:54.392327       1 lownodeutilization.go:376] "Evicted pods" pod="debezium-prod/debezium-postgres-cp-kafka-connect-7c6f4b446b-mg255" err=<nil>

**What did you expect to see?**
only one node for this label，do not evict pods for this service

**What did you see instead?**

**Comment by damemi** [comment]
Hi, NodeFit was added in [v0.21.0](https://github.com/kubernetes-sigs/descheduler/releases/tag/v0.21.0), so setting it in v0.20.0 will not work.

Please try again after upgrading your version of descheduler, and if the issue persists then please feel free to reopen this bug. Thanks!
/close

**Comment by yxiaoy6** [comment]
> Hi, NodeFit was added in [v0.21.0](https://github.com/kubernetes-sigs/descheduler/releases/tag/v0.21.0), so setting it in v0.20.0 will not work.
> 
> Please try again after upgrading your version of descheduler, and if the issue persists then please feel free to reopen this bug. Thanks! /close

hi，Can k8s v1.20 use deschduler v0.24?

**Comment by damemi** [comment]
> hi，Can k8s v1.20 use deschduler v0.24?

We don't technically support or test v0.24 on v1.20, so it may work, but if there are any issues then the recommendation is to upgrade
