### ISSUE TITLE
Add to metrics the pod name which was evicted

### ISSUE THREAD

**Issue by mczimm** [kubernetes-sigs/descheduler#919]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The metrics for premetheus should have pod name of application which was evicted

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version: v0.24.0

**Additional context**

**Comment by mczimm** [comment]
Hi @damemi, I'll show you what I mean.

In the metrics I see this

descheduler_pods_evicted{cloud="cloud", cluster="cluster", container="descheduler", endpoint="http-metrics", instance="10.10.28.101:10258", job="descheduler", namespace="back", node="cl13khna1utejao014uh-oqar", pod="descheduler-64f4ccfdb7-52fn4", prometheus="vm/vm-victoria-metrics-k8s-stack", result="success", service="descheduler", strategy="PodTopologySpread"}

and with this info I can't understand which service pod was evicted? So if I'll have the service pod name which was evicted I'll be able to make an alert for example or chart grouped by pods.

**Comment by damemi** [comment]
Yeah, `descheduler_pods_evicted` is meant as an aggregated count of the total pods evicted. So right now it would show an overall value like
```
descheduler_pods_evicted{...} 123
```

or since it's already grouped by node:
```
descheduler_pods_evicted{...node="node-a"} 5
descheduler_pods_evicted{...node="node-b"} 12
descheduler_pods_evicted{...node="node-c"} 8
```
(or namespace)

But if you add pod names into that as a label, then in clusters that use generated pod names, you're going to get all unique time series like
```
descheduler_pods_evicted{...,pod="my-pod-f43x7t} 1
descheduler_pods_evicted{...,pod="my-pod-e92nbf} 1
descheduler_pods_evicted{...,pod="my-pod-aay0dk} 1
descheduler_pods_evicted{...,pod="my-pod-pw890d} 1
...
```

So I am just confused by how you would handle that. Maybe if you could put together a PR with a sample demo of it in practice (like a screenshot) it will be clearer?

**Comment by damemi** [comment]
See also: https://prometheus.io/docs/practices/naming/#labels

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

The way Prometheus works, each of these individual pod names basically becomes a new metric, and they are all stored permanently in memory (in the descheduler's Prometheus handler). So this would be like a big memory leak, as it would be constantly growing and storing all of these single-point time series

**Comment by mczimm** [comment]
<img width="1673" alt="Screenshot 2022-08-22 at 11 49 10" src="https://user-images.githubusercontent.com/12083430/185881260-12bc83f0-98a9-46af-8c24-5f97a35c61e1.png">

**Comment by damemi** [comment]
@mczimm thanks, yes I understand what you are asking for. See my comment above, where following the Prometheus docs this is probably not a good idea given the high cardinality of pod names.

**Comment by mczimm** [comment]
Hi @damemi. What about to keep not an uniq pod name but app-name in the descheduler's Prometheus handler?
