### ISSUE TITLE
Plugin arguments defaulting + moving plugin arguments to each corresponding plugin

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-sigs/descheduler#925]
All plugin arguments need to be defaulted so a user is not required to specify every available argument. Also, to improve plugin modularity it's preferable to move corresponding plugin argument type to its plugin. So both defaulting and validation code is not separated from the plugin itself.

**Comment by damemi** [comment]
As a reference for anyone who wants to pick it up, https://github.com/kubernetes-sigs/descheduler/pull/900 is an example of what we mean by `Also, to improve plugin modularity it's preferable to move corresponding plugin argument type to its plugin. So both defaulting and validation code is not separated from the plugin itself.`

**Comment by damemi** [comment]
/close
done in #954

**Comment by ingvagabund** [comment]
https://github.com/kubernetes-sigs/descheduler/pull/1006/files#diff-0129f73a80ed727af36e1b6007786fd044191cafed0900875f5a90b38ea33739R86 for wiring the defaulting of arguments
