### ISSUE TITLE
New v1alpha2 configuration + conversion

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-sigs/descheduler#926]
The new framework comes with a concept of profiles which require new configuration type. The current v1alpha1 type is expected to be convertible into the new v1alpha2 type. With both v1alpha1 and v1alpha2 types the internal configuration types will get updated to conform to the v1alpha2 type. The old internal types will be removed. At the same time the v1alpha1 type will get deprecated.

When conversion from v1alpha1 to v1alpha2 is performed, every strategy in v1alpha1 gets converted into a separate v1alpha2 profile. Each profile has its own evictor configuration so all the v1alpha1 strategy parameters can be unambiguously mapped into v1alpha2 plugin arguments.

More about the profiles in the descheduling framework design proposal: https://docs.google.com/document/d/1tWpXoZ6YF3ksnmueM2POwASdxoiLW8y7TXuWFxT8NSo/edit#heading=h.ec817eouurjs

Previous efforts:
- https://github.com/kubernetes-sigs/descheduler/pull/314
- https://github.com/kubernetes-sigs/descheduler/pull/578
- https://github.com/kubernetes-sigs/descheduler/pull/587
- https://github.com/kubernetes-sigs/descheduler/pull/698

**Comment by knelasevero** [comment]
Documentation missing for this one:
- replace v1alpha1 docs with v1alpha2 docs
- add a notice about the v1alpha1 deprecation
- if we manage to have a mkdocs setup generating a gh-pages docs page would be nice, but acceptance criteria can be just the readme update for now

[cc @damemi @ingvagabund from community meeting]

**Comment by ingvagabund** [comment]
Once the docs and the deprecation are published, this issue can be closed.
