### ISSUE TITLE
PodLifeTime rule evicts Running pods after maxPodLifeTimeSeconds

### ISSUE THREAD

**Issue by mstefany** [kubernetes-sigs/descheduler#932]
**What version of descheduler are you using?**

descheduler version: `k8s.gcr.io/descheduler/descheduler:v0.24.1
`

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
```
  containers:
  - args:
    - --policy-config-file
    - /policy-dir/policy.yaml
    - --descheduling-interval
    - 10m
    - --v
    - "3"
    command:
    - /bin/descheduler
```

**Please provide a copy of your descheduler policy config file**
<details><summary><code>descheduler policy</code> config file</summary><br><pre>
apiVersion: v1
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      HighNodeUtilization:
        enabled: true
        params:
          nodeFit: true
          nodeResourceUtilizationThresholds:
            thresholds:
              cpu: 20
              memory: 20
              pods: 20
      LowNodeUtilization:
        enabled: true
        params:
          nodeFit: true
          nodeResourceUtilizationThresholds:
            targetThresholds:
              cpu: 70
              memory: 70
              pods: 70
            thresholds:
              cpu: 20
              memory: 20
              pods: 20
      PodLifeTime:
        enabled: true
        params:
          podLifeTime:
            maxPodLifeTimeSeconds: 7200
            states:
            - ContainerCreating
            - Pending
            - PodInitializing
      RemoveDuplicates:
        enabled: true
        params:
          namespaces:
            exclude:
            - namespace1
            - namespace2
            - namespace3
            - namespace4
          removeDuplicates:
            excludeOwnerKinds:
            - ReplicaSet
      RemoveFailedPods:
        enabled: true
        params:
          failedPods:
            excludeOwnerKinds:
            - Job
            includingInitContainers: true
            minPodLifetimeSeconds: 3600
      RemovePodsHavingTooManyRestarts:
        enabled: true
        params:
          namespaces:
            exclude:
            - namespace1
            - namespace2
            - namespace3
            - namespace4
          podsHavingTooManyRestarts:
            includingInitContainers: true
            podRestartThreshold: 10
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
        params:
                    namespaces:
            exclude:
            - namespace1
            - namespace2
            - namespace3
            - namespace4
      RemovePodsViolatingNodeAffinity:
        enabled: true
        params:
          namespaces:
            exclude:
            - namespace1
            - namespace2
            - namespace3
            - namespace4
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingNodeTaints:
        enabled: true
        params:
          namespaces:
            exclude:
            - namespace1
            - namespace2
            - namespace3
            - namespace4
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: true
        params:
          namespaces:
            exclude:
            - namespace1
            - namespace2
            - namespace3
            - namespace4
kind: ConfigMap
[...]
</pre></details>

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
I configured descheduler to evict pods in states: ContainerCreating, Pending or PodInitializing after 7200 seconds, according to documentation: https://github.com/kubernetes-sigs/descheduler#podlifetime - "You can also specify states parameter to only evict pods matching the following conditions:".

**What did you expect to see?**
I expected descheduler to evict only pods which are stuck in ContainerCreating, Pending or PodInitializing states for 7200 seconds.

**What did you see instead?**
Descheduler evicts pods also in Running state after 7200 seconds. But apparently not all of them. Some pods are Running for 40d, some of them are evicted by descheduler after 2 hours, repeatedly.

**Comment by mstefany** [comment]
@damemi thank you! My bad that I didn't notice it was for 0.25.0, sorry about that. I've changed the configuration and I will observe if it behaves well.

**Comment by damemi** [comment]
No problem, hope that helps! Gonna close this, feel free to reopen if you need.
/close
