### ISSUE TITLE
Add `states` filter parameter to `RemovePodsViolatingNodeTaints` strategy

### ISSUE THREAD

**Issue by ob-uk** [kubernetes-sigs/descheduler#934]
**Is your feature request related to a problem? Please describe.**

In our use case, we run several containers and store them post completion. This eventually leads to disk pressure on the node. When we run descheduler, it evicts all `Completed` pods, which is not ideal for us as we'd like to save the pods in the `Completed` state. K8S' automatic GC works pretty well for relieving disk-pressure, but it does end up blocking some of the running pods because disk IOPS reaches full utilization during cleanup. Practically, as long as we evict `Running` pods, this scenario is good for us, and I imagine it is good for others who might be running a lot of Jobs with some non trivial TTL post completion. 

It would be perfect if we could also add the `states` filter parameter to `RemovePodsViolatingNodeTaints`, so that we could elect to only kick pods that are either in the `Running` or `ContainerCreating` state. 

**Describe the solution you'd like**

The `states` parameter filter, similar to what `PodLifeTime` strategy has. This allows us to elect which pods are OK to evict by the descheduler. 

**Describe alternatives you've considered**

An alternative is to just use `nodeSelector` in the policy and only seek nodes with a `disk-pressure:true` label (for our case). We can then simply use `PodLifeTime` with appropriate `namespaces` and `labelSelector` with the `Running` `states` filter, which should only evict `Running` pods, only on the nodes that have `disk-pressure: true`. 

**What version of descheduler are you using?**

descheduler version: 0.24.1

**Additional context**

I am happy to work with the contributors and implement this feature myself, provided others see this as viable and interesting to the descheduler.

**Comment by damemi** [comment]
It seems reasonable to me that there are other strategies that could benefit. from the `states` parameter. This might take a back seat while we focus on the framework migration, though. At which point it will be easier to implement
