### ISSUE TITLE
Kubernetes 1.26 Release

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#940]
From https://github.com/kubernetes/sig-release/blob/master/releases/release-1.26/README.md:

The 1.26 release cycle is as follows:

- **Monday 5th September 2022**: Week 1 — Release cycle begins
- **Monday 24th - Friday 28th October 2022**: Week 8 - [KubeCon NA](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/)
- **Wednesday 9th November 2022**: Week 10 — Code Freeze
- **Tuesday 6th December 2022**: Week 14 — Kubernetes v1.26.0 released

---

## Pre-release Code Changes

Before publishing each release, the following code updates must be made:

- [ ] (Optional, but recommended) Bump `k8s.io` dependencies to the `-rc` tags. These tags are usually published around upstream code freeze. [Example](https://github.com/kubernetes-sigs/descheduler/pull/539)
- [ ] Bump `k8s.io` dependencies to GA tags once they are published (following the upstream release). [Example](https://github.com/kubernetes-sigs/descheduler/pull/615)
- [ ] Ensure that Go is updated to the same version as upstream. [Example](https://github.com/kubernetes-sigs/descheduler/pull/801)
- [ ] Make CI changes in [github.com/kubernetes/test-infra](https://github.com/kubernetes/test-infra) to add the new version's tests (note, this may also include a Go bump). [Example](https://github.com/kubernetes/test-infra/pull/25833)
- [ ] Update local CI versions for utils (such as golang-ci), kind, and go. [Example - e2e](https://github.com/kubernetes-sigs/descheduler/commit/ac4d576df8831c0c399ee8fff1e85469e90b8c44), [Example - helm](https://github.com/kubernetes-sigs/descheduler/pull/821)
- [ ] Update version references in docs and Readme. [Example](https://github.com/kubernetes-sigs/descheduler/pull/617)

**Comment by a7i** [comment]
I'd like to take the pre-release code changes to become more familiar with the process.

/assign

**Comment by damemi** [comment]
Thanks @a7i, fyi all for this release I'd like to organize our tasks through a Github project so we can better keep track of what is in progress. I'm looking into how we can set one up for our project

**Comment by a7i** [comment]
Yes, I saw your comment after the assignment. Makes sense 👍🏼

**Comment by damemi** [comment]
Got the project set up at https://github.com/orgs/kubernetes-sigs/projects/22 and filled in with draft issues

Let's wrap up v0.25.0 first, and then we can start organizing those. It will be great if we can get a dedicated meeting time set up for this from https://github.com/kubernetes-sigs/descheduler/issues/944

**Comment by JaneLiuL** [comment]
cool, looks more transparency and funny ~~

**Comment by damemi** [comment]
Just created new issues for this release: https://github.com/kubernetes-sigs/descheduler/issues/1007 https://github.com/kubernetes-sigs/descheduler/issues/1008 https://github.com/kubernetes-sigs/descheduler/issues/1009. Please feel free to self-assign if you are interested!

**Comment by damemi** [comment]
Last call: going to tag v0.26.0 this afternoon if there are no last minute changes waiting to get in (https://github.com/kubernetes-sigs/descheduler/issues/1021)
