### ISSUE TITLE
Recurrent meeting dedicated to this project

### ISSUE THREAD

**Issue by knelasevero** [kubernetes-sigs/descheduler#944]
Hey all!

I am seeing growing interest in this project, and, even though we don't have a lot, we have some active regular contributors here, which made me want to propose something:

So far, as far as I understand, this project has been using sig-scheduling community meetings and sometimes wg-batch meetings to share updates and some minor discussions. That is mostly fine in general, but I wanted to propose for us to have a dedicated meeting every 2 weeks (or any other interval that you might find fitting).

Sharing a meeting with sig-scheduling makes us feel like we can only bring discussions there when we have something "important enough", or, "something that might be relevant to other folks from other projects". I think this makes us avoid topics that are "too specific", but at the same time important for speeding up/improving the development of the descheduler.

I think this is specially useful now, during this descheduling framework effort, which influences too much of other discussions around the project.

cc Some people that are top contribs or commented in issues that I could quickly look around (sorry for the noise) [feel free to tag more people]:
@ingvagabund @damemi @a7i @seanmalloy @aveshagarwal @lixiang233 @JaneLiuL @jklaw90 @pravarag @eminaktas @harshanarayana @BinacsLee @uniemimu

I can take this over and run the initial meetings, but would be cool if anyone wants to enter in the rotation.

We can start this less officially initially, and gradually make this an official community meeting with recordings and all that gist.

Let me know what you all think, and if you would have the time for that. Maybe we decide to do this only while we are doing the framework effort, or indefinitely, who knows.

**Comment by damemi** [comment]
Thanks for taking the initiative to propose this @knelasevero, I think it's a great idea. I agree that sharing with sig-scheduling meetings not only shortens what we can talk about, but it also cuts into time that could be used to discuss core scheduling topics in those meetings.

Over the past ~3ish years I've definitely seen interest in the project grow a ton. A dedicated meeting time could be really helpful to demonstrate to new users that this is an active project being maintained by people with a vested interest in its success.

From a k8s-org perspective, I wonder if there is a proper way to organize meetings devoted to a subproject like this. Would a working group be appropriate? Or do we just set up a time on our own? I would like to hear from the rest of the sig-scheduling on what they think

**Comment by damemi** [comment]
cc @ahg-g @alculquicondor @Huang-Wei, your thoughts on starting dedicated descheduler meetings?

**Comment by pravarag** [comment]
> 
> Let me know what you all think, and if you would have the time for that. Maybe we decide to do this only while we are doing the framework effort, or indefinitely, who knows.

Great thought and a big +1 on this. I think we can plan for maybe every other Thursdays to sig-scheduling meetings (just a suggestion). Similar to what sig-release and release-engineering usually does :)

**Comment by alculquicondor** [comment]
sgtm

Are you settled on a bi-weekly cadence? Probably worth moving the discussion to https://github.com/kubernetes/community/
Or maybe just create the PR directly with the suggested dates and cadence.

**Comment by damemi** [comment]
> I think we can plan for maybe every other Thursdays to sig-scheduling meetings (just a suggestion). Similar to what sig-release and release-engineering usually does :)

if possible, I'd like to request not this time (as sig-scheduling already conflicts with another weekly meeting I have), but I know I'm not the only person here

> Probably worth moving the discussion to https://github.com/kubernetes/community/
Or maybe just create the PR directly with the suggested dates and cadence.

Would this go under `sig-scheduling` there? Or create our own directory?

**Comment by alculquicondor** [comment]
yes, sig-scheduling. See this for example: https://github.com/kubernetes/community/blob/master/sigs.yaml#L28

**Comment by ahg-g** [comment]
> cc @ahg-g @alculquicondor @Huang-Wei, your thoughts on starting dedicated descheduler meetings?

This sounds good, it is all about the overhead of managing it and making sure there is always a moderator attending the meeting.

**Comment by knelasevero** [comment]
@damemi I was thinking about starting with it unofficially in the beginning, with maybe just a Readme notice, and start moving to the official route of adding it to https://github.com/kubernetes/community/ once we decide it's time (after we optimize it's schedule based on attendee availability and we also decide that it should be a permanent thing).

I'm ok with pushing it already to https://github.com/kubernetes/community/ but wanted to check.

**Comment by damemi** [comment]
@knelasevero yeah I'd say we can go right to k/community. Good to be official from the start so we have a clear record.

**Comment by eminaktas** [comment]
cc @Dentrax

**Comment by Huang-Wei** [comment]
AFAIK, there is no required approval to host a sub-project dedicated meeting, so go ahead to kick it off. Once it's setup officially, update the community doc like https://github.com/kubernetes/community/pull/6507.

**Comment by damemi** [comment]
Sounds like there's support 🚀 @knelasevero do you want to take the lead on opening a PR against the community repo? We can discuss the time there

**Comment by knelasevero** [comment]
Will do! I will open a PR with a suggestion and we finalize a decision with the pr review then 🚀

**Comment by knelasevero** [comment]
PR created :point_up: Let's continue the discussion there

**Comment by knelasevero** [comment]
Hey all, don't forget to chime in the discussion over here:

https://github.com/kubernetes/community/pull/6867
