### ISSUE TITLE
Helm test with ct install is installing as CronJob and not Deployment

### ISSUE THREAD

**Issue by knelasevero** [kubernetes-sigs/descheduler#949]
While looking at https://github.com/kubernetes-sigs/descheduler/issues/946 I noticed that in the gh-actions output https://github.com/kubernetes-sigs/descheduler/pull/945/checks ct install is installing descheduler in CronJob mode, which does not get useful events and logs back to us (even though we have `helm-extra-set-args: "--set=kind=Deployment"` set in https://github.com/kubernetes-sigs/descheduler/blob/master/.github/ci/ct.yaml) . 

This worked at some point since we had this during reviews: https://github.com/kubernetes-sigs/descheduler/pull/895#pullrequestreview-1055672165 :thinking: 

Installing it as Deployment will be better to check info and possibly add subsequent simple tests against that pod.

**Comment by a7i** [comment]
/assign

@knelasevero would you take a look at https://github.com/kubernetes-sigs/descheduler/pull/953 and see if it makes sense?

**Comment by knelasevero** [comment]
Thanks @a7i ! And sorry for the delay on this one. For sure reason I totally missed the notification

**Comment by a7i** [comment]
No worries @knelasevero
