### ISSUE TITLE
filter pods with pvc volumes

### ISSUE THREAD

**Issue by caruccio** [kubernetes-sigs/descheduler#96]
https://github.com/kubernetes-incubator/descheduler/blob/af2198428e0f52c10d9bd58bc8f3173c80a45142/pkg/descheduler/pod/pods.go#L132

Hey!
It looks like PVCs should be marked as non-evictable, or there should be a user-defined flag to allow that behavior.
Greetings.

**Comment by aveshagarwal** [comment]
@caruccio i think having a flag would be better as that could be enabled/disabled as needed.

**Comment by kfirfer** [comment]
Would be great to see it

**Comment by seanmalloy** [comment]
@kfirfer so you want an option to tell the descheduler to not evict pods that have a PVC associated with them?

/reopen

**Comment by kfirfer** [comment]
@seanmalloy Yes, Its sounds great

**Comment by seanmalloy** [comment]
If this is implemented it will probably work similar to `evictLocalStoragePods`. See below link for docs.

https://github.com/kubernetes-sigs/descheduler#policy-and-strategies

**Comment by caruccio** [comment]
@seanmalloy that is exactly what I meant.

**Comment by damemi** [comment]
> If this is implemented it will probably work similar to `evictLocalStoragePods`. See below link for docs for details.
> 
> https://github.com/kubernetes-sigs/descheduler#policy-and-strategies

This is pretty straightforward, but something to consider is how we default this flag to preserve current behavior. Since we currently evict PVC pods, maybe the flag should be more like `ignorePvcPods` with a default=false? open to other ideas like `preserve`, `dontEvict`, etc

/assign

**Comment by damemi** [comment]
Opened #481 to add this
