### ISSUE TITLE
Allow Logging format to be changed

### ISSUE THREAD

**Issue by gallowaystorm** [kubernetes-sigs/descheduler#965]
**Is your feature request related to a problem? Please describe.**

Yes it is related to a problem.  When sending the logs to Datadog, all logs show as errors because I cannot switch them to a format that Datadog excepts.  This means that all logs are errors even if they are just info level logs.

**Describe the solution you'd like**

The ability to change the format of the logs.

**Describe alternatives you've considered**

none

**What version of descheduler are you using?**

descheduler version: Helm 0.24.1

**Additional context**

**Comment by damemi** [comment]
Hi @gallowaystorm, is the [`--logging-format` flag](https://github.com/kubernetes-sigs/descheduler/blob/0317be1b7672c511f5e2e53acaea1dd5cb74fd77/docs/user-guide.md#cli-options) possibly helpful? That supports text and json logging output.

**Comment by gallowaystorm** [comment]
How can I use that with the Helm chart?

**Comment by harshanarayana** [comment]
```bash
helm install ...... --set cmdOptions.logging-format=text
```
@gallowaystorm  This should get you going 

```bash
❯ helm install test . --dry-run --set cmdOptions.logging-format=text | grep -A2 logging
                - "--logging-format"
                - "text"
                - "--v"

```

**Comment by gallowaystorm** [comment]
Thank you I will try this!

**Comment by gallowaystorm** [comment]
Also that did not help the issue in Datadog.  It did change the log format however

**Comment by damemi** [comment]
@gallowaystorm could you give more details on what the issue in Datadog is? Some sample output or screenshots would help, I don't know if they are looking for a specific format or what that format you need is

**Comment by damemi** [comment]
We just use the [klog](https://github.com/kubernetes/klog) library to set our logs, which should also handle the json formatting, so I'm not sure why it wouldn't be passing the severity.

Could you try setting `--skip-headers` as well? I found [this issue](https://github.com/kubernetes/klog/issues/145) and it looks like maybe the klog headers are in your logs... still don't see the severity in the JSON format, but this could be a start

**Comment by harshanarayana** [comment]
@damemi Might be related to the discussion on https://github.com/kubernetes-sigs/descheduler/issues/811 ?

**Comment by gallowaystorm** [comment]
@damemi   I tried to set the skip headers via our helm release in Terraform (how we do helm releases) and it does not seem possible to do so:

```
resource "helm_release" "descheduler" {
  chart      = local.service_name
  name       = "${local.service_name}-${var.environment}"
  namespace  = local.namespace
  repository = "https://kubernetes-sigs.github.io/descheduler/"
  version    = "0.24.1" # APP VERSION v0.24.1

  set {
    name  = "cmdOptions.skip-headers"
    value = true
  }
}
```

Log from DD:

Error: unknown command "true" for "descheduler"

**Comment by damemi** [comment]
@gallowaystorm I think the problem is actually closer to https://github.com/kubernetes-sigs/descheduler/issues/811 like @harshanarayana mentioned. But it's worth unsticking this just to see

Running locally, the following commands work:
```
$ descheduler --skip-headers=true
$ descheduler --skip-headers
```

but this one gives the `unknown command` error:
```
$ descheduler --skip-headers true
```

since we [don't add a `=` when we parse cmdOptions](https://github.com/kubernetes-sigs/descheduler/blob/ae20b5b034d0db4ff1319f25c60a6e30a5b17890/charts/descheduler/templates/deployment.yaml#L53-L56) can you try just setting an empty value `""` for this? ie

```
  set {
    name  = "cmdOptions.skip-headers"
    value = ""
  }
```

**Comment by gallowaystorm** [comment]
That did not make the logging error any better, however it did make the logs easier to read...  I then tried the logtostderr method with:

```yaml
resource "helm_release" "descheduler" {
  chart      = local.service_name
  name       = "${local.service_name}-${var.environment}"
  namespace  = local.namespace
  repository = "https://kubernetes-sigs.github.io/descheduler/"
  version    = "0.24.1" # APP VERSION v0.24.1

  set {
    name  = "cmdOptions.logtostderr"
    value = "false"
  }
}
```


This still seemed to not do the trick...

**Comment by damemi** [comment]
Hi @gallowaystorm, thanks for bumping this. This issue is in our usage of logging libraries from upstream Kubernetes and their default output streams.

I dug around some more and found this issue which also had to do with DataDog integration: https://github.com/kubernetes-sigs/descheduler/issues/676

It sounds like https://github.com/kubernetes-sigs/descheduler/issues/676#issuecomment-1013178391 describes a datadog workaround to redirect logs to the right log level based on parsing the lines. This might un stick you until we fix our own implementation.

**Comment by damemi** [comment]
@gallowaystorm have you tried a combination of `logtostderr=false` and `logging-format=json`?

**Comment by gallowaystorm** [comment]
Yes I did try that @damemi.  Let me look at #676 and see whats happening there

**Comment by gallowaystorm** [comment]
That workaround in #676 did the trick for our needs.  However, because of the workaround depending on the headers being on the logs, we can now no longer remove the headers.  Will this be fixed in any future releases?

**Comment by damemi** [comment]
@gallowaystorm I'm glad that worked for you. Yes, there appears to be some issue in our logging as others have also reported issues with logs so we will be discussing this at our next project meeting
