### ISSUE TITLE
Error evicting pod

### ISSUE THREAD

**Issue by iamdevnull** [kubernetes-sigs/descheduler#972]
**What version of descheduler are you using?**

descheduler version: 0.25.1

**Does this issue reproduce with the latest release?**

yes

**Which descheduler CLI options are you using?**

`--policy-config-file /policy-dir/policy.yaml --v 3
`

**Please provide a copy of your descheduler policy config file**

`apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  HighNodeUtilization:
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        thresholds:
          cpu: 30
          memory: 20
          pods: 100    
  LowNodeUtilization:
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
  RemoveDuplicates:
    enabled: true
  RemovePodsHavingTooManyRestarts:
    enabled: true
    params:
      podsHavingTooManyRestarts:
        includingInitContainers: true
        podRestartThreshold: 100
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: true
    params:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
  RemovePodsViolatingNodeTaints:
    enabled: true
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: true
    params:
      includeSoftConstraints: false`

**What k8s version are you using (`kubectl version`)?**

EKS

`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

**What did you expect to see?**

I wanted to see that on nodes with 100% pods usage some pods would be evicted und started on nodes with lower pods usage than 100% 

**What did you see instead?**

see attatchment
[debug-descheduler.txt](https://github.com/kubernetes-sigs/descheduler/files/9726305/debug-descheduler.txt)

**Comment by damemi** [comment]
Hi @iamdevnull, it looks like your EKS version is 1.17, so the descheduler version 0.25.1 is [not supported for your cluster](https://github.com/kubernetes-sigs/descheduler#compatibility-matrix). The latest supported descheduler version for k8s 1.17 is v0.19.0

**Comment by iamdevnull** [comment]
Thx a lot. I will test it.

**Comment by iamdevnull** [comment]
it works as expected.
