### ISSUE TITLE
Logo proposal for the project

### ISSUE THREAD

**Issue by knelasevero** [kubernetes-sigs/descheduler#978]
https://github.com/knelasevero/descheduler-logo-proposals

![image](https://user-images.githubusercontent.com/2432275/195164678-0b55c322-fe7c-4d61-ac8f-a71e8a765c8c.png)

From the [11 Oct community meeting](https://docs.google.com/document/d/1Ang5shAFxuylO2RXMFGO7uxSe-IX3Y3PxoKIn1yPIEQ/edit#) we discussed adding this logo as the descheduler project logo. 

It was generated with the AI image generation, with the process described in the [readme](https://github.com/knelasevero/descheduler-logo-proposals). Basically using stable diffusion with some tweaks.

If the community has any other great image that we might use, or if they have feedback regarding all this, this is the issue to discuss it :D

Then we need to check the legality of using this, and then how to donate to [CNCF](https://github.com/cncf/artwork).

**Comment by damemi** [comment]
I think a month is good enough soak time for people to see this :) As long as we have confirmation that there are no copyright issues (ie, you own the entire rights to that picture) then I'm good moving forward

**Comment by knelasevero** [comment]
https://stability.ai/stablediffusion-terms-of-service#:~:text=accepted%20the%20full-,CC0%201.0%20Universal%20Public%20Domain%20Dedication,-(available%20at%20https

It seems that it is public domain by default, when generated on the DreamStudio Beta. But it is owned by me (and @iurisevero) since we generated in our infra with little tweaks.

I guess now we need to donate to CNCF so they include it in https://github.com/cncf/artwork and then we can use or something like that.

@amye sorry to tag you here, we did something similar for External Secrets Operator, but I am not sure how it would go for an already sig sponsored project, can you help us with that?

**Comment by knelasevero** [comment]
Hey we interacted with a few other people that understand these things better, and we came up with two other options for us to choose:

![image](https://user-images.githubusercontent.com/2432275/203845374-1dfa5c47-e913-4a65-9027-3e7abcedd107.png)

![image](https://user-images.githubusercontent.com/2432275/203845427-ea5954e9-10fb-4874-b55d-284aff0c8cea.png)

This is the horizontal text version so we can also see the font (we have to provide stacked and horizontal to cncf). 

Let's vote (vote open to anyone in the community, even if you never touched descheduler) 

Send a :heart: if you like the red box one (first one), send a :rocket:  if you like the stylized frame one (second one)

**Comment by knelasevero** [comment]
I forgot to set a deadline. Let's say by the end of this week we make a final decision based on the votes. 

Be sure to get your votes in if you have a preference.

**Comment by knelasevero** [comment]
Ok, Option one is the winner! :D

![image](https://user-images.githubusercontent.com/2432275/206726158-eba83097-d6be-43f6-a68d-fc4ab50008c0.png)


Gonna prepare the PR soon and we can go forward with this

**Comment by knelasevero** [comment]
PR submitted :point_up:  When we have it merged there, we can add to the readme and other stuff :)
