### ISSUE TITLE
Does the descheduler evict pods if the pods themselves are not idle?

### ISSUE THREAD

**Issue by sdmattheww** [kubernetes-sigs/descheduler#980]
I'm wondering if a pod is running and busy but part of a deployment with only one replica could it be evicted or does the scheduler check at a pod level to see if it's safe to move them?

**Comment by damemi** [comment]
There are a number of checks that the descheduler does before evicting a pod: https://github.com/kubernetes-sigs/descheduler#pod-evictions

But I'm not sure what you mean by "idle", could you explain what you mean or maybe give an example? I'd think it would be tough for it to determine what it means for a pod to be busy

**Comment by sdmattheww** [comment]
Thanks for your prompt response!  I agree it would be difficult to determine, but ideally we'd like to see some sort of check to see if an application is processing data for example to exempt it from eviction.  If this isn't possible we just want to confirm that.

**Comment by damemi** [comment]
@sdmattheww yeah there's nothing like that now, unfortunately.

It would be a cool idea for a new strategy though. I'm not sure what mechanism it would use to check if a pod is actually doing work. CPU/memory usage come to mind, but you could also just have very high-consumption idle components. Maybe a configurable threshold to define what is idle would work.
