### ISSUE TITLE
Add changelogs for feature && bug tracing

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/descheduler#981]
Will we consider add changelogs to descheduler similar to kubernetes https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG,
this will be useful in searching and browsing. Currently, if I want to search 
such things, I'll browse the release pages.

**Comment by kerthcet** [comment]
cc @damemi

**Comment by kerthcet** [comment]
Or just I didn't find. 🙃

**Comment by damemi** [comment]
@kerthcet we do post the changes for each release on the Github release page, for example https://github.com/kubernetes-sigs/descheduler/releases/tag/v0.25.0. Is this what you were looking for, or do you think having the generated changelogs like what you linked would also be good?

**Comment by kerthcet** [comment]
Yes, I browsed the release page for details. IMO, it's less convenient to search across multiple release. Considering we already post the changes for each release, I think it‘s just a copy-paste work.

**Comment by kerthcet** [comment]
FYI: this is how kueue works here https://github.com/kubernetes-sigs/kueue/tree/main/CHANGELOG.

**Comment by kerthcet** [comment]
By the way, I pinged you on slack, please take a look. ^_^

**Comment by damemi** [comment]
> Yes, I browsed the release page for details. IMO, it's less convenient to search across multiple release. Considering we already post the changes for each release, I think it‘s just a copy-paste work.

Makes sense to me, that would be more convenient. It would be nice to backfill with our changelogs from past releases
