### ISSUE TITLE
Can't change log level using --v cli option

### ISSUE THREAD

**Issue by poojasj** [kubernetes-sigs/descheduler#991]
**What version of descheduler are you using?**

descheduler version:
v0.24.1

**Which descheduler CLI options are you using?**
```  
          containers:
            - args:
              - --policy-config-file
              - /policy-dir/policy.yaml
              - --logging-format
              - json
              - --v
              - "4"
```
**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

 I was trying to get pod eviction logs of descheduler, so I increased the log level to 4. But that doesn't seem to work, there were only 3 log events in each descheduler pod logs.
 We recently upgraded to descheduler v0.24 and started using `--logging-format=json` option. So I tried removing `--logging-format=json` from the cronjob and I started seeing correct logs as per level set in the cli option.

**What did you expect to see?**
Info level descheduler logs, in json format

**What did you see instead?**
Logs:
<pre>
{"ts":1666025401338.376,"caller":"server/secure_serving.go:210","msg":"Serving securely on [::]:10258\n","v":0}
{"ts":1666025401338.4546,"caller":"dynamiccertificates/tlsconfig.go:240","msg":"Starting DynamicServingCertificateController","v":0}
{"ts":1666025405001.4187,"caller":"dynamiccertificates/tlsconfig.go:255","msg":"Shutting down DynamicServingCertificateController","v":0}
</pre>

**Comment by poojasj** [comment]
@damemi That doesn't work.
I changed the arguments like this:
<pre>            - args:
              - --policy-config-file
              - /policy-dir/policy.yaml
              - --logging-format
              - json
              - --v
              - "5"
              - --logtostderr=false
</pre>
logs after the change:
<pre>
$ k logs -n kube-system descheduler-cronjob-27768154-qgdg6
Flag --logtostderr has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
{"ts":1666089242007.3384,"caller":"server/secure_serving.go:210","msg":"Serving securely on [::]:10258\n","v":0}
{"ts":1666089242007.3962,"caller":"dynamiccertificates/tlsconfig.go:240","msg":"Starting DynamicServingCertificateController","v":0}
{"ts":1666089246026.032,"caller":"dynamiccertificates/tlsconfig.go:255","msg":"Shutting down DynamicServingCertificateController","v":0}
</pre>

**Comment by damemi** [comment]
Thanks for confirming that @poojasj, there seems to be some issue with our logging as there have been several reports of odd behavior recently. We'll be looking into this and trying to fix it asap

**Comment by monotek** [comment]
I also loose eviction logs as soon as i switch to logging-format json in v0.26.0.
