### ISSUE TITLE
I hope the descheduler can support some functions such as namespaces filtering and pods filtering in the LowNodeUtilization strategy

### ISSUE THREAD

**Issue by tomsunyu** [kubernetes-sigs/descheduler#992]
Hello:
    During the use of descheduler, I encountered the following problem: I have many pods providing redis service, the redis service depends on memory of k8s nodes. Once the descheduler reschedules these pods by the LowNodeUtilization strategy, these redis pods will restart, and datas of redis pods have lost. Of course, I have some another methods to store the memory data, but I hope the descheduler can support some functions such as namespaces filtering and pods filtering in the LowNodeUtilization strategy.
In addition to the above scenarios, I still have many K8S pods that cannot be restarted during the service period. If the descheduler's LowNodeUtilization strategy is used, there may be a risk of business interruption.
   
 I have read the official dos, the descheduler does not support pod filtering in the LowNodeUtilizatin strategy. Such as namespace filtering, only support the following strategy:    

-     PodLifeTime
-     RemovePodsHavingTooManyRestarts
-     RemovePodsViolatingNodeTaints
-     RemovePodsViolatingNodeAffinity
-     RemovePodsViolatingInterPodAntiAffinity
-     RemoveDuplicates
-     RemovePodsViolatingTopologySpreadConstraint
-     RemoveFailedPods

    So can you help me ?

**Comment by JaneLiuL** [comment]
hi 
thanks for use descheduler and bring suggestions.
yes till now `LowNodeUtilization` does not support namespace filter or LabelSelector.

and i check we already have a pr to support namespace filter, you can have a look here: https://github.com/kubernetes-sigs/descheduler/pull/967

**Comment by damemi** [comment]
closing based on https://github.com/kubernetes-sigs/descheduler/issues/992#issuecomment-1281792129, namespace filtering should be available in the next release
/close
